### ISSUE TITLE
Oracle Linux 7.9 - installing python issue 

### ISSUE THREAD

**Issue by asobeeh** [vitabaks/postgresql_cluster#105]
OS: Oracle Linux 7.9 

'TASK [packages : Install system packages] *****************************************************************************************************
failed: [172.16.10.217] (item=['python', 'python-devel', 'python-psycopg2', 'python-setuptools', 'libselinux-python', 'libsemanage-python', 'policycoreutils-python']) => {"ansible_loop_var": "item", "changed": true, "changes": {"installed": ["python-devel"], "updated": []}, "item": ["python", "python-devel", "python-psycopg2", "python-setuptools", "libselinux-python", "libsemanage-python", "policycoreutils-python"], "msg": "Error: Package: python-devel-2.7.5-90.el7.x86_64 (updates)\n           Requires: python(x86-64) = 2.7.5-90.el7\n           Installed: python-2.7.5-90.0.1.el7.x86_64 (@ol7_latest)\n               python(x86-64) = 2.7.5-90.0.1.el7\n           Available: python-2.7.5-68.0.1.el7.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-68.0.1.el7\n           Available: python-2.7.5-69.0.1.el7_5.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-69.0.1.el7_5\n           Available: python-2.7.5-76.0.1.el7.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-76.0.1.el7\n           Available: python-2.7.5-77.0.1.el7_6.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-77.0.1.el7_6\n           Available: python-2.7.5-79.0.1.el7_6.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-79.0.1.el7_6\n           Available: python-2.7.5-80.0.1.el7_6.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-80.0.1.el7_6\n           Available: python-2.7.5-86.0.1.el7.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-86.0.1.el7\n           Available: python-2.7.5-86.0.3.el7.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-86.0.3.el7\n           Available: python-2.7.5-88.0.1.el7.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-88.0.1.el7\n           Available: python-2.7.5-89.el7.x86_64 (base)\n               python(x86-64) = 2.7.5-89.el7\n           Available: python-2.7.5-90.el7.x86_64 (updates)\n               python(x86-64) = 2.7.5-90.el7\n", "rc": 1, "results": ["All packages providing python are up to date", "All packages providing python-psycopg2 are up to date", "All packages providing python-setuptools are up to date", "All packages providing libselinux-python are up to date", "All packages providing libsemanage-python are up to date", "All packages providing policycoreutils-python are up to date", "Loaded plugins: langpacks, ulninfo\nPackage matching python-2.7.5-90.el7.x86_64 already installed. Checking for update.\nPackage python-psycopg2-2.7.5-1.rhel7.1.x86_64 already installed and latest version\nPackage python-setuptools-0.9.8-7.el7.noarch already installed and latest version\nPackage libselinux-python-2.5-15.el7.x86_64 already installed and latest version\nPackage libsemanage-python-2.5-14.el7.x86_64 already installed and latest version\nPackage policycoreutils-python-2.5-34.0.1.el7.x86_64 already installed and latest version\nResolving Dependencies\n--> Running transaction check\n---> Package python-devel.x86_64 0:2.7.5-90.el7 will be installed\n--> Processing Dependency: python(x86-64) = 2.7.5-90.el7 for package: python-devel-2.7.5-90.el7.x86_64\n--> Processing Dependency: python2-rpm-macros > 3-30 for package: python-devel-2.7.5-90.el7.x86_64\n--> Running transaction check\n---> Package python-devel.x86_64 0:2.7.5-90.el7 will be installed\n--> Processing Dependency: python(x86-64) = 2.7.5-90.el7 for package: python-devel-2.7.5-90.el7.x86_64\n---> Package python2-rpm-macros.noarch 0:3-34.el7 will be installed\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}
ok: [172.16.10.217] => (item=python3)
changed: [172.16.10.217] => (item=python3-devel)
changed: [172.16.10.217] => (item=python3-psycopg2)
ok: [172.16.10.217] => (item=python3-setuptools)
ok: [172.16.10.217] => (item=python3-pip)
ok: [172.16.10.217] => (item=curl)
ok: [172.16.10.217] => (item=less)
ok: [172.16.10.217] => (item=sudo)
ok: [172.16.10.217] => (item=vim)
ok: [172.16.10.217] => (item=gcc)
ok: [172.16.10.217] => (item=jq)
ok: [172.16.10.217] => (item=iptables)
ok: [172.16.10.217] => (item=acl)
failed: [172.16.10.218] (item=['python', 'python-devel', 'python-psycopg2', 'python-setuptools', 'libselinux-python', 'libsemanage-python', 'policycoreutils-python']) => {"ansible_loop_var": "item", "changed": true, "changes": {"installed": ["python-devel"], "updated": []}, "item": ["python", "python-devel", "python-psycopg2", "python-setuptools", "libselinux-python", "libsemanage-python", "policycoreutils-python"], "msg": "Error: Package: python-devel-2.7.5-90.el7.x86_64 (updates)\n           Requires: python(x86-64) = 2.7.5-90.el7\n           Installed: python-2.7.5-90.0.1.el7.x86_64 (@ol7_latest)\n               python(x86-64) = 2.7.5-90.0.1.el7\n           Available: python-2.7.5-68.0.1.el7.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-68.0.1.el7\n           Available: python-2.7.5-69.0.1.el7_5.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-69.0.1.el7_5\n           Available: python-2.7.5-76.0.1.el7.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-76.0.1.el7\n           Available: python-2.7.5-77.0.1.el7_6.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-77.0.1.el7_6\n           Available: python-2.7.5-79.0.1.el7_6.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-79.0.1.el7_6\n           Available: python-2.7.5-80.0.1.el7_6.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-80.0.1.el7_6\n           Available: python-2.7.5-86.0.1.el7.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-86.0.1.el7\n           Available: python-2.7.5-86.0.3.el7.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-86.0.3.el7\n           Available: python-2.7.5-88.0.1.el7.x86_64 (cal_ol7_UEKR5_latest_latest)\n               python(x86-64) = 2.7.5-88.0.1.el7\n           Available: python-2.7.5-89.el7.x86_64 (base)\n               python(x86-64) = 2.7.5-89.el7\n           Available: python-2.7.5-90.el7.x86_64 (updates)\n               python(x86-64) = 2.7.5-90.el7\n", "rc": 1, "results": ["All packages providing python are up to date", "All packages providing python-psycopg2 are up to date", "All packages providing python-setuptools are up to date", "All packages providing libselinux-python are up to date", "All packages providing libsemanage-python are up to date", "All packages providing policycoreutils-python are up to date", "Loaded plugins: langpacks, ulninfo\nPackage matching python-2.7.5-90.el7.x86_64 already installed. Checking for update.\nPackage python-psycopg2-2.7.5-1.rhel7.1.x86_64 already installed and latest version\nPackage python-setuptools-0.9.8-7.el7.noarch already installed and latest version\nPackage libselinux-python-2.5-15.el7.x86_64 already installed and latest version\nPackage libsemanage-python-2.5-14.el7.x86_64 already installed and latest version\nPackage policycoreutils-python-2.5-34.0.1.el7.x86_64 already installed and latest version\nResolving Dependencies\n--> Running transaction check\n---> Package python-devel.x86_64 0:2.7.5-90.el7 will be installed\n--> Processing Dependency: python(x86-64) = 2.7.5-90.el7 for package: python-devel-2.7.5-90.el7.x86_64\n--> Processing Dependency: python2-rpm-macros > 3-30 for package: python-devel-2.7.5-90.el7.x86_64\n--> Running transaction check\n---> Package python-devel.x86_64 0:2.7.5-90.el7 will be installed\n--> Processing Dependency: python(x86-64) = 2.7.5-90.el7 for package: python-devel-2.7.5-90.el7.x86_64\n---> Package python2-rpm-macros.noarch 0:3-34.el7 will be installed\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}
changed: [172.16.10.218] => (item=python3)
changed: [172.16.10.218] => (item=python3-devel)
changed: [172.16.10.218] => (item=python3-psycopg2)
ok: [172.16.10.218] => (item=python3-setuptools)
ok: [172.16.10.218] => (item=python3-pip)
ok: [172.16.10.218] => (item=curl)
ok: [172.16.10.218] => (item=less)
ok: [172.16.10.218] => (item=sudo)
ok: [172.16.10.218] => (item=vim)
ok: [172.16.10.218] => (item=gcc)
ok: [172.16.10.218] => (item=jq)
ok: [172.16.10.218] => (item=iptables)
ok: [172.16.10.218] => (item=acl)
'

**Comment by vitabaks** [comment]
> Package: python-devel-2.7.5-90.el7.x86_64 Requires: python(x86-64) = 2.7.5-90.el7 
Installed: python-2.7.5-90.0.1.el7.x86_64 

At first glance, the problem in the versions of the dependent packages at the OL repository.

@asobeeh  Have you tried to put python-devel package manually? 
I could not reproduce this problem, all Python packages were successfully installed.

**Comment by vitabaks** [comment]
```
[root@pgnode01 /]# cat /etc/oracle-release
Oracle Linux Server release 7.9

[root@pgnode01 /]# yum list python-devel
Loaded plugins: ovl, ulninfo
Available Packages
python-devel.x86_64                         2.7.5-90.0.3.el7                          ol7_latest

[root@pgnode01 /]# yum list python
Loaded plugins: ovl, ulninfo
Installed Packages
python.x86_64                      2.7.5-90.0.3.el7                      @ol7_latest/$releasever
```

**Comment by asobeeh** [comment]
> > Package: python-devel-2.7.5-90.el7.x86_64 Requires: python(x86-64) = 2.7.5-90.el7
> > Installed: python-2.7.5-90.0.1.el7.x86_64
> 
> At first glance, the problem in the versions of the dependent packages at the OL repository.
> i have removed OL repository and add centos one :)
> @asobeeh Have you tried to put python-devel package manually?
> I could not reproduce this problem, all Python packages were successfully installed.
yes i tried but same error 
so i changed OL repo with centos repo 
i faced other problems but solved and everything is working fine now as usual thanks alot
