### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by Anton-PG** [vitabaks/postgresql_cluster#11]
Good afternoon!
Please create a complete list of all packages for the packages_from _file variable. Specify the packages in the correct order. Thanks for the work you've done!

Добрый день!
Пожалуйста, создайте полный список всех пакетов для переменной packages_from _file. Укажите пакеты в правильном порядке. Спасибо за проделанную работу!

**Comment by vitabaks** [comment]
this is a duplicate of the task https://github.com/vitabaks/postgresql_cluster/issues/10
