### ISSUE TITLE
Performance degradation caused by haproxy

### ISSUE THREAD

**Issue by owen-xie** [vitabaks/postgresql_cluster#111]
Pgbench is used to test the database performance. It is connected to port 5000 of the VIP and port 6432 of the master node respectively. It is found that after haproxy forwarding, the TPS index decreases by 80%.Why does performance drop so much？

**Comment by vitabaks** [comment]
@owen-xie Thanks for your test.
Please feel free to describe the details of your test and its results in this issue. 

When using haproxy, additional latency is possible, which in turn can affect performance (TPS), but there should not be an 80% drop in TPS.

First of all, describe your infrastructure: 
Are the servers located in the same region and there is no high latency between the servers? 
When connecting to port 5000 (master), on which server was the VIP address located?

**Comment by owen-xie** [comment]
@vitabaks There are three hosts: 71, 72 and 73. 71 is the master node, VIP is 75, and VIP is on 73. I tried to change the number of connections and threads tested, and the results are basically the same
![pgbench](https://user-images.githubusercontent.com/66617478/129124479-6688561b-1f00-4334-97a1-b80487fb5c13.jpg)

**Comment by owen-xie** [comment]
After seeing your reply, I tried to transfer the VIP to the primary node 71, and then conducted the above test on 71 again. The new test result reached 728 (TPS)

**Comment by vitabaks** [comment]
@owen-xie 

You did not answer my question:
> Are the servers located in the same region and there is no high latency between servers?

Pay attention to the "latency average", which means that there is a rather high latency between servers, and therefore, load balancing gives additional overhead.
If you do not need load balancing for reading, but only need access to the master, I recommend considering the TypeB schema (with_haproxy_load_balancing: false).

By the way, to minimize latency when using pgbouncer, I plan to switch from TCP - localhost (127.0.0.1) to unix socket (/var/run/postgresql). Here is a test showing that using a unix socket for a local pool can provide a performance advantage by reducing latency.
https://gitlab.com/postgres-ai/postgresql-consulting/tests-and-benchmarks/-/issues/10#note_619514423 

It will be great if you check it out too.
