### ISSUE TITLE
Patroni cluster problem (pg_rewind and psycopg2.OperationalError: timeout expired)

### ISSUE THREAD

**Issue by oguzhansrky** [vitabaks/postgresql_cluster#117]
Ubuntu 20.04.03 LTS
PostgreSQL 13
Patroni Latest

------------------------

Hi,

Patroni cluster problem

patronictl restart = error 
  2021-09-12 00:46:03,596 - WARNING - /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

-----------
System Log
------------
Sep 12 00:48:19 localhost patroni[651]: 2021-09-12 00:48:19,497 WARNING: Postgresql is not running.
Sep 12 00:48:19 localhost patroni[651]: 2021-09-12 00:48:19,497 INFO: Lock owner: pgnode03; I am pgnode01
Sep 12 00:48:19 localhost patroni[651]: 2021-09-12 00:48:19,499 INFO: pg_controldata:
Sep 12 00:48:19 localhost patroni[651]:   pg_control version number: 1300
Sep 12 00:48:19 localhost patroni[651]:   Catalog version number: 202007201
Sep 12 00:48:19 localhost patroni[651]:   Database system identifier: 7006790696745470787
Sep 12 00:48:19 localhost patroni[651]:   Database cluster state: shut down in recovery
Sep 12 00:48:19 localhost patroni[651]:   pg_control last modified: Sun Sep 12 00:46:09 2021
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint location: 0/8000028
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's REDO location: 0/8000028
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's REDO WAL file: 000000030000000000000008
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's TimeLineID: 3
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's PrevTimeLineID: 3
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's full_page_writes: on
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's NextXID: 0:490
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's NextOID: 16387
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's NextMultiXactId: 1
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's NextMultiOffset: 0
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's oldestXID: 479
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's oldestXID's DB: 1
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's oldestActiveXID: 0
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's oldestMultiXid: 1
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's oldestMulti's DB: 1
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's oldestCommitTsXid: 0
Sep 12 00:48:19 localhost patroni[651]:   Latest checkpoint's newestCommitTsXid: 0
Sep 12 00:48:19 localhost patroni[651]:   Time of latest checkpoint: Sun Sep 12 00:31:34 2021
Sep 12 00:48:19 localhost patroni[651]:   Fake LSN counter for unlogged rels: 0/3E8
Sep 12 00:48:19 localhost patroni[651]:   Minimum recovery ending location: 0/80000A0
Sep 12 00:48:19 localhost patroni[651]:   Min recovery ending loc's timeline: 3
Sep 12 00:48:19 localhost patroni[651]:   Backup start location: 0/0
Sep 12 00:48:19 localhost patroni[651]:   Backup end location: 0/0
Sep 12 00:48:19 localhost patroni[651]:   End-of-backup record required: no
Sep 12 00:48:19 localhost patroni[651]:   wal_level setting: replica
Sep 12 00:48:19 localhost patroni[651]:   wal_log_hints setting: on
Sep 12 00:48:19 localhost patroni[651]:   max_connections setting: 1000
Sep 12 00:48:19 localhost patroni[651]:   max_worker_processes setting: 8
Sep 12 00:48:19 localhost patroni[651]:   max_wal_senders setting: 10
Sep 12 00:48:19 localhost patroni[651]:   max_prepared_xacts setting: 0
Sep 12 00:48:19 localhost patroni[651]:   max_locks_per_xact setting: 64
Sep 12 00:48:19 localhost patroni[651]:   track_commit_timestamp setting: off
Sep 12 00:48:19 localhost patroni[651]:   Maximum data alignment: 8
Sep 12 00:48:19 localhost patroni[651]:   Database block size: 8192
Sep 12 00:48:19 localhost patroni[651]:   Blocks per segment of large relation: 131072
Sep 12 00:48:19 localhost patroni[651]:   WAL block size: 8192
Sep 12 00:48:19 localhost patroni[651]:   Bytes per WAL segment: 16777216
Sep 12 00:48:19 localhost patroni[651]:   Maximum length of identifiers: 64
Sep 12 00:48:19 localhost patroni[651]:   Maximum columns in an index: 32
Sep 12 00:48:19 localhost patroni[651]:   Maximum size of a TOAST chunk: 1996
Sep 12 00:48:19 localhost patroni[651]:   Size of a large-object chunk: 2048
Sep 12 00:48:19 localhost patroni[651]:   Date/time type storage: 64-bit integers
Sep 12 00:48:19 localhost patroni[651]:   Float8 argument passing: by value
Sep 12 00:48:19 localhost patroni[651]:   Data page checksum version: 1
Sep 12 00:48:19 localhost patroni[651]:   Mock authentication nonce: e41d09d2aacd4a1b9a94f7178c32fbe43dabb35193885fc27d6fb88b4e881dd9
Sep 12 00:48:19 localhost patroni[651]: 2021-09-12 00:48:19,501 INFO: Lock owner: pgnode03; I am pgnode01
Sep 12 00:48:19 localhost patroni[651]: 2021-09-12 00:48:19,540 INFO: running pg_rewind from pgnode03
Sep 12 00:48:19 localhost kernel: [  393.425865] Dropped by firewall: IN=ens18 OUT= MAC=f6:3e:67:cf:eb:c2:ba:7e:3b:6d:3f:50:08:00 SRC=10.10.10.153 DST=10.10.10.151 LE 

==> /var/log/kern.log <==
Sep 12 00:48:20 localhost kernel: [  394.433510] Dropped by firewall: IN=ens18 OUT= MAC=f6:3e:67:cf:eb:c2:ba:7e:3b:6d:3f:50:08:00 SRC=10.10.10.153 DST=10.10.10.151 LE 

==> /var/log/syslog <==
Sep 12 00:48:20 localhost kernel: [  394.433510] Dropped by firewall: IN=ens18 OUT= MAC=f6:3e:67:cf:eb:c2:ba:7e:3b:6d:3f:50:08:00 SRC=10.10.10.153 DST=10.10.10.151 LE 

==> /var/log/kern.log <==
Sep 12 00:48:22 localhost kernel: [  396.450432] Dropped by firewall: IN=ens18 OUT= MAC=f6:3e:67:cf:eb:c2:ba:7e:3b:6d:3f:50:08:00 SRC=10.10.10.153 DST=10.10.10.151 LE 

==> /var/log/syslog <==
Sep 12 00:48:22 localhost patroni[651]: 2021-09-12 00:48:22,549 ERROR: Exception when working with leader
Sep 12 00:48:22 localhost patroni[651]: Traceback (most recent call last):
Sep 12 00:48:22 localhost patroni[651]:   File "/usr/local/lib/python3.8/dist-packages/patroni/postgresql/rewind.py", line 60, in check_leader_is_not_in_recovery
Sep 12 00:48:22 localhost patroni[651]:     with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
Sep 12 00:48:22 localhost patroni[651]:   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
Sep 12 00:48:22 localhost patroni[651]:     return next(self.gen)
Sep 12 00:48:22 localhost patroni[651]:   File "/usr/local/lib/python3.8/dist-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Sep 12 00:48:22 localhost patroni[651]:     conn = psycopg2.connect(**kwargs)
Sep 12 00:48:22 localhost patroni[651]:   File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
Sep 12 00:48:22 localhost patroni[651]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Sep 12 00:48:22 localhost patroni[651]: psycopg2.OperationalError: timeout expired
Sep 12 00:48:22 localhost kernel: [  396.450432] Dropped by firewall: IN=ens18 OUT= MAC=f6:3e:67:cf:eb:c2:ba:7e:3b:6d:3f:50:08:00 SRC=10.10.10.153 DST=10.10.10.151 LE 
^C

**Comment by vitabaks** [comment]
> urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!

try updating the requests package:

`sudo pip3 install requests --upgrade`

**Comment by vitabaks** [comment]
>Sep 12 00:48:19 localhost patroni[651]: 2021-09-12 00:48:19,540 INFO: running pg_rewind from pgnode03
Sep 12 00:48:22 localhost patroni[651]: 2021-09-12 00:48:22,549 ERROR: Exception when working with leader

Please attach Patroni and PostgreSQL log from pgnode03

**Comment by vitabaks** [comment]
> Sep 12 00:48:22 localhost patroni[651]: psycopg2.OperationalError: timeout expired

This is also interesting. Is pgnode03 available on port 5432 from pgnode01? Try `telnet`

**Comment by oguzhansrky** [comment]
I'm still continuing my tests. After the clean install, I ran this command "apt install python3-pip -y && sudo pip3 install requests --upgrade" and installed the cluster.

I restarted node1, node2 and node3 gradually.
Finally I restarted them all at once and waited for it to work and it worked.

There are no barriers between them. In the log file I sent before, it says that it cannot access the external 54000-odd ports and drops the log. It was telneting.

**Comment by oguzhansrky** [comment]
![image](https://user-images.githubusercontent.com/52497227/132966256-67a5b498-09d2-4bf8-a133-ed974b80cbde.png)

Interesting

"sudo pip3 install requests --upgrade" I was doing 3 node installation before this update and shutting down node1 and node2 machine respectively. When I entered the command "patronictl topology" on the node3 machine, I was getting the screen I shared in the other problem. And no matter what I did after that, the cluster wouldn't come back. For now, the problem seems to be fixed, I'm still continuing the tests. When my problem is solved, I will close this as solved.

https://github.com/vitabaks/postgresql_cluster/issues/113

I was having the same problem, just so you know.

**Comment by oguzhansrky** [comment]
Hi,

![image](https://user-images.githubusercontent.com/52497227/132987996-bbeb0f1d-d191-4c86-b567-6fc904a15f13.png)

The problem has reappeared

![image](https://user-images.githubusercontent.com/52497227/132988014-91b019be-4340-4e9a-a2af-308cc64c1b69.png)

Node1 postgresql

![image](https://user-images.githubusercontent.com/52497227/132988030-9db325c3-81d3-491c-9f4f-c9173756f729.png)


------------------------------------
Sep 12 15:42:34 pgnode01 patroni[3242]:   Mock authentication nonce: 0e3deca02823035277cb7274513058ceb1083626a3431284c83e1d505e61f2fd
Sep 12 15:42:34 pgnode01 patroni[3242]: 2021-09-12 15:42:34,617 INFO: Lock owner: pgnode02; I am pgnode01
Sep 12 15:42:34 pgnode01 patroni[3242]: 2021-09-12 15:42:34,630 INFO: running pg_rewind from pgnode02
Sep 12 15:42:37 pgnode01 patroni[3242]: 2021-09-12 15:42:37,635 ERROR: Exception when working with leader
Sep 12 15:42:37 pgnode01 patroni[3242]: Traceback (most recent call last):
Sep 12 15:42:37 pgnode01 patroni[3242]:   File "/usr/local/lib/python3.8/dist-packages/patroni/postgresql/rewind.py", line 60, in check_leader_is_not_in_recovery
Sep 12 15:42:37 pgnode01 patroni[3242]:     with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
Sep 12 15:42:37 pgnode01 patroni[3242]:   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
Sep 12 15:42:37 pgnode01 patroni[3242]:     return next(self.gen)
Sep 12 15:42:37 pgnode01 patroni[3242]:   File "/usr/local/lib/python3.8/dist-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Sep 12 15:42:37 pgnode01 patroni[3242]:     conn = psycopg2.connect(**kwargs)
Sep 12 15:42:37 pgnode01 patroni[3242]:   File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
Sep 12 15:42:37 pgnode01 patroni[3242]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Sep 12 15:42:37 pgnode01 patroni[3242]: psycopg2.OperationalError: timeout expired
Sep 12 15:42:44 pgnode01 patroni[3242]: 2021-09-12 15:42:44,612 WARNING: Postgresql is not running.
Sep 12 15:42:44 pgnode01 patroni[3242]: 2021-09-12 15:42:44,612 INFO: Lock owner: pgnode02; I am pgnode01
Sep 12 15:42:44 pgnode01 patroni[3242]: 2021-09-12 15:42:44,614 INFO: pg_controldata:
Sep 12 15:42:44 pgnode01 patroni[3242]:   pg_control version number: 1300
Sep 12 15:42:44 pgnode01 patroni[3242]:   Catalog version number: 202007201
Sep 12 15:42:44 pgnode01 patroni[3242]:   Database system identifier: 7006821959499499555
Sep 12 15:42:44 pgnode01 patroni[3242]:   Database cluster state: shut down
Sep 12 15:42:44 pgnode01 patroni[3242]:   pg_control last modified: Sun Sep 12 15:36:43 2021
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint location: 0/28000028
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's REDO location: 0/28000028
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's REDO WAL file: 0000000A0000000000000028
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's TimeLineID: 10
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's PrevTimeLineID: 10
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's full_page_writes: on
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's NextXID: 0:43683
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's NextOID: 20973
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's NextMultiXactId: 1
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's NextMultiOffset: 0
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's oldestXID: 479
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's oldestXID's DB: 1
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's oldestActiveXID: 0
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's oldestMultiXid: 1
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's oldestMulti's DB: 1
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's oldestMulti's DB: 1
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's oldestCommitTsXid: 0
Sep 12 15:42:44 pgnode01 patroni[3242]:   Latest checkpoint's newestCommitTsXid: 0
Sep 12 15:42:44 pgnode01 patroni[3242]:   Time of latest checkpoint: Sun Sep 12 15:36:43 2021
Sep 12 15:42:44 pgnode01 patroni[3242]:   Fake LSN counter for unlogged rels: 0/3E8
Sep 12 15:42:44 pgnode01 patroni[3242]:   Minimum recovery ending location: 0/0
Sep 12 15:42:44 pgnode01 patroni[3242]:   Min recovery ending loc's timeline: 0
Sep 12 15:42:44 pgnode01 patroni[3242]:   Backup start location: 0/0
Sep 12 15:42:44 pgnode01 patroni[3242]:   Backup end location: 0/0
Sep 12 15:42:44 pgnode01 patroni[3242]:   End-of-backup record required: no
Sep 12 15:42:44 pgnode01 patroni[3242]:   wal_level setting: replica
Sep 12 15:42:44 pgnode01 patroni[3242]:   wal_log_hints setting: on
Sep 12 15:42:44 pgnode01 patroni[3242]:   max_connections setting: 1000
Sep 12 15:42:44 pgnode01 patroni[3242]:   max_worker_processes setting: 8
Sep 12 15:42:44 pgnode01 patroni[3242]:   max_wal_senders setting: 10
Sep 12 15:42:44 pgnode01 patroni[3242]:   max_prepared_xacts setting: 0
Sep 12 15:42:44 pgnode01 patroni[3242]:   max_locks_per_xact setting: 64
Sep 12 15:42:44 pgnode01 patroni[3242]:   track_commit_timestamp setting: off
Sep 12 15:42:44 pgnode01 patroni[3242]:   Maximum data alignment: 8
Sep 12 15:42:44 pgnode01 patroni[3242]:   Database block size: 8192
Sep 12 15:42:44 pgnode01 patroni[3242]:   Blocks per segment of large relation: 131072
Sep 12 15:42:44 pgnode01 patroni[3242]:   WAL block size: 8192
Sep 12 15:42:44 pgnode01 patroni[3242]:   Bytes per WAL segment: 16777216
Sep 12 15:42:44 pgnode01 patroni[3242]:   Maximum length of identifiers: 64
Sep 12 15:42:44 pgnode01 patroni[3242]:   Maximum columns in an index: 32
Sep 12 15:42:44 pgnode01 patroni[3242]:   Maximum size of a TOAST chunk: 1996
Sep 12 15:42:44 pgnode01 patroni[3242]:   Size of a large-object chunk: 2048
Sep 12 15:42:44 pgnode01 patroni[3242]:   Date/time type storage: 64-bit integers
Sep 12 15:42:44 pgnode01 patroni[3242]:   Float8 argument passing: by value
Sep 12 15:42:44 pgnode01 patroni[3242]:   Data page checksum version: 1
Sep 12 15:42:44 pgnode01 patroni[3242]:   Mock authentication nonce: 0e3deca02823035277cb7274513058ceb1083626a3431284c83e1d505e61f2fd
Sep 12 15:42:44 pgnode01 patroni[3242]: 2021-09-12 15:42:44,617 INFO: Lock owner: pgnode02; I am pgnode01
Sep 12 15:42:44 pgnode01 patroni[3242]: 2021-09-12 15:42:44,630 INFO: running pg_rewind from pgnode02
Sep 12 15:42:47 pgnode01 patroni[3242]: 2021-09-12 15:42:47,638 ERROR: Exception when working with leader
Sep 12 15:42:47 pgnode01 patroni[3242]: Traceback (most recent call last):
Sep 12 15:42:47 pgnode01 patroni[3242]:   File "/usr/local/lib/python3.8/dist-packages/patroni/postgresql/rewind.py", line 60, in check_leader_is_not_in_recovery
Sep 12 15:42:47 pgnode01 patroni[3242]:     with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
Sep 12 15:42:47 pgnode01 patroni[3242]:   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
Sep 12 15:42:47 pgnode01 patroni[3242]:     return next(self.gen)
Sep 12 15:42:47 pgnode01 patroni[3242]:   File "/usr/local/lib/python3.8/dist-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Sep 12 15:42:47 pgnode01 patroni[3242]:     conn = psycopg2.connect(**kwargs)
Sep 12 15:42:47 pgnode01 patroni[3242]:   File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
Sep 12 15:42:47 pgnode01 patroni[3242]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Sep 12 15:42:47 pgnode01 patroni[3242]: psycopg2.OperationalError: timeout expired
--------------------------------------------

**Comment by vitabaks** [comment]
> Sep 12 15:42:34 pgnode01 patroni[3242]: 2021-09-12 15:42:34,630 INFO: running pg_rewind from pgnode02
Sep 12 15:42:37 pgnode01 patroni[3242]: 2021-09-12 15:42:37,635 ERROR: Exception when working with leader
...
Sep 12 15:42:37 pgnode01 patroni[3242]: psycopg2.OperationalError: timeout expired'

@oguzhansrky 

I do not see how this problem is related to the cluster deployment with this playbook, and I have not met such an error.

1. Make sure you have no problems with the network.
2. Open issue in the Patroni project [repository](https://github.com/zalando/patroni/issues).
3. As a temporary solution, execute `patronictl reinit` for pgnode01.
