### ISSUE TITLE
Can you use latest version of etcd

### ISSUE THREAD

**Issue by orisvscs** [vitabaks/postgresql_cluster#12]
Hi,

Your solution is using older version of etcd (etcd_ver: "v3.3.15"). Can you pls look into using the latest version of etcd?  BTW, pls note that etcdctl command to check cluster health may not work in the latest version of etcd, and there might be a different approach.

**Comment by vitabaks** [comment]
Hello! @orisvscs 
Patroni (version 1.6.0) does not yet support etcd v3.4.x
https://github.com/zalando/patroni/issues/1163

there is a pull request implementing support of etcd v3 protocol:
https://github.com/zalando/patroni/pull/1162 
and perhaps after the release of the next version of patroni, we can specify etcd v3.4.2

For now, I can advise you to specify v3.3.17

**Comment by orisvscs** [comment]
ok, thanks.

**Comment by orisvscs** [comment]
Can I use postgres 12 by changing your variable file?  Does Patroni support that?

**Comment by vitabaks** [comment]
> 
> 
> Can I use postgres 12 by changing your variable file? Does Patroni support that?

Yes.
