### ISSUE TITLE
Error etcd and Patroni (ReadTimeoutError("HTTPConnectionPool(host='xxx', port=2379): Read timed out.)

### ISSUE THREAD

**Issue by DenisK32** [vitabaks/postgresql_cluster#135]
hi,getting persistent error:

```
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.1.3', port=2379): Read timed out. (read timeout=3.3321133383336323)
Dec 09 09:55:56 pgsql1 patroni[15197]: During handling of the above exception, another exception occurred:
Dec 09 09:55:56 pgsql1 patroni[15197]: Traceback (most recent call last):
Dec 09 09:55:56 pgsql1 patroni[15197]: File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 211, in _do_http_request
Dec 09 09:55:56 pgsql1 patroni[15197]: response = request_executor(method, base_uri + path, **kwargs)
Dec 09 09:55:56 pgsql1 patroni[15197]: File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 79, in request
Dec 09 09:55:56 pgsql1 patroni[15197]: method, url, fields=fields, headers=headers, **urlopen_kw
Dec 09 09:55:56 pgsql1 patroni[15197]: File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 170, in request_encode_body
Dec 09 09:55:56 pgsql1 patroni[15197]: return self.urlopen(method, url, **extra_kw)
Dec 09 09:55:56 pgsql1 patroni[15197]: File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 375, in urlopen
Dec 09 09:55:56 pgsql1 patroni[15197]: response = conn.urlopen(method, u.request_uri, **kw)
Dec 09 09:55:56 pgsql1 patroni[15197]: File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
Dec 09 09:55:56 pgsql1 patroni[15197]: method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
Dec 09 09:55:56 pgsql1 patroni[15197]: File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
Dec 09 09:55:56 pgsql1 patroni[15197]: raise MaxRetryError(_pool, url, error or ResponseError(cause))
Dec 09 09:55:56 pgsql1 patroni[15197]: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.3', port=2379): Max retries exceeded with url: /v2/keys/service/postgres-cluster/status (Caused by Read
Dec 09 09:55:56 pgsql1 patroni[15197]: During handling of the above exception, another exception occurred:
Dec 09 09:55:56 pgsql1 patroni[15197]: Traceback (most recent call last):
Dec 09 09:55:56 pgsql1 patroni[15197]: File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 564, in wrapper
Dec 09 09:55:56 pgsql1 patroni[15197]: retval = func(self, *args, **kwargs) is not None
Dec 09 09:55:56 pgsql1 patroni[15197]: File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 690, in _write_status
Dec 09 09:55:56 pgsql1 patroni[15197]: return self._client.set(self.status_path, value)
Dec 09 09:55:56 pgsql1 patroni[15197]: File "/usr/local/lib/python3.6/site-packages/etcd/client.py", line 721, in set
Dec 09 09:55:56 pgsql1 patroni[15197]: return self.write(key, value, ttl=ttl)
Dec 09 09:55:56 pgsql1 patroni[15197]: File "/usr/local/lib/python3.6/site-packages/etcd/client.py", line 500, in write
Dec 09 09:55:56 pgsql1 patroni[15197]: response = self.api_execute(path, method, params=params)
Dec 09 09:55:56 pgsql1 patroni[15197]: File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 256, in api_execute
Dec 09 09:55:56 pgsql1 patroni[15197]: response = self._do_http_request(retry, machines_cache, request_executor, method, path, **kwargs)
Dec 09 09:55:56 pgsql1 patroni[15197]: File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 230, in _do_http_request
Dec 09 09:55:56 pgsql1 patroni[15197]: raise etcd.EtcdException('{0} {1} request failed'.format(method, path))
Dec 09 09:55:56 pgsql1 patroni[15197]: etcd.EtcdException: PUT /v2/keys/service/postgres-cluster/status request failed
Dec 09 09:55:57 pgsql1 patroni[15197]: 2021-12-09 09:55:57,258 INFO: no action. I am (pgsql1), the leader with the lock
Dec 09 09:55:57 pgsql1 patroni[15197]: 2021-12-09 09:55:57,260 WARNING: Loop time exceeded, rescheduling immediately.
Dec 09 09:56:01 pgsql1 patroni[15197]: 2021-12-09 09:56:01,249 INFO: no action. I am (pgsql1), the leader with the lock
Dec 09 09:56:10 pgsql1 patroni[15197]: 2021-12-09 09:56:07,264 INFO: Lock owner: pgsql1; I am pgsql1
Request to server http://192.168.1.2:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'192.168.1.2\', port=2379): Max retries exceeded wi
Dec 09 09:56:10 pgsql1 patroni[15197]: 2021-12-09 09:56:10,604 INFO: Reconnection allowed, looking for another server.
Dec 09 09:56:10 pgsql1 patroni[15197]: 2021-12-09 09:56:10,604 INFO: Retrying on http://192.168.1.4:2379
Dec 09 09:56:11 pgsql1 patroni[15197]: 2021-12-09 09:56:11,377 INFO: Selected new etcd server http://192.168.1.4:2379
Dec 09 09:56:14 pgsql1 patroni[15197]: 2021-12-09 09:56:14,791 INFO: no action. I am (pgsql1), the leader with the lock
Dec 09 09:56:20 pgsql1 patroni[15197]: 2021-12-09 09:56:20,951 INFO: no action. I am (pgsql1), the leader with the lock
Dec 09 09:56:30 pgsql1 patroni[15197]: 2021-12-09 09:56:27,265 INFO: Lock owner: pgsql1; I am pgsql1
lines 544-586/1001 59%
Dec 09 09:55:56 pgsql1 patroni[15197]: self, url, "Read timed out. (read timeout=%s)" % timeout_value


```
I tried to move etcd to ssd disks, the problem remained. Patroni periodically restarts postgresql. And in the etcd logs it writes:
Etcd: Node healthcheck failed.

**Comment by DenisK32** [comment]
CentOS7
Postgresql 13

**Comment by DenisK32** [comment]
Dec 09 11:22:46 pgsql1 patroni[22108]: 2021-12-09 11:22:42,881 INFO: Lock owner: pgsql1; I am pgsql1
Dec 09 11:22:46 pgsql1 patroni[22108]: 2021-12-09 11:22:46,222 ERROR: Request to server http://192.168.1.2:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'192.168.1.2\', port=2379): Max retries exceeded with url: /v2/keys/service/postgres-cluster/leader (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'192.168.1.2\', port=2379): Read timed out. (read timeout=3.3329069173390358)",))',)
Dec 09 11:22:46 pgsql1 patroni[22108]: 2021-12-09 11:22:46,222 INFO: Reconnection allowed, looking for another server.
Dec 09 11:22:46 pgsql1 patroni[22108]: 2021-12-09 11:22:46,222 INFO: Retrying on http://192.168.1.4:2379
Dec 09 11:22:49 pgsql1 patroni[22108]: 2021-12-09 11:22:49,562 ERROR: Request to server http://192.168.1.4:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'192.168.1.4\', port=2379): Max retries exceeded with url: /v2/keys/service/postgres-cluster/leader (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'192.168.1.4\', port=2379): Read timed out. (read timeout=3.3317284073321694)",))',)
Dec 09 11:22:49 pgsql1 patroni[22108]: 2021-12-09 11:22:49,562 INFO: Reconnection allowed, looking for another server.

**Comment by vitabaks** [comment]
Hi @DenisK32 

Please attach the etcd logs from all cluster servers Etcd

`sudo journalctl -u etcd -n 50 --output=short-precise`

**Comment by DenisK32** [comment]
pgsql1:

**Comment by DenisK32** [comment]
etcd Version: 3.5.1
Git SHA: e8732fb5f
Go Version: go1.16.3
Go OS/Arch: linux/amd64

**Comment by vitabaks** [comment]
pgsql1 - the local etcd version 3.3.25 is not up-to-date

**Comment by DenisK32** [comment]
root@pgsql1 /usr/local/bin #./etcd --version
etcd Version: 3.5.1
Git SHA: e8732fb5f
Go Version: go1.16.3
Go OS/Arch: linux/amd64

**Comment by vitabaks** [comment]
restart the etcd service on this server

**Comment by DenisK32** [comment]
Dec 09 15:48:41.420438 pgsql1 systemd[1]: Started Etcd Server.
Dec 09 15:48:41.427701 pgsql1 bash[8949]: {"level":"info","ts":"2021-12-09T15:48:40.414+0300","caller":"embed/serve.go:140","msg":"serving client traffic insecurely; this is strongly discourage
Dec 09 15:48:41.428274 pgsql1 bash[8949]: {"level":"info","ts":"2021-12-09T15:48:40.414+0300","caller":"embed/serve.go:140","msg":"serving client traffic insecurely; this is strongly discourage
Dec 09 15:48:41.456040 pgsql1 bash[8949]: {"level":"warn","ts":"2021-12-09T15:48:41.454+0300","caller":"wal/wal.go:802","msg":"slow fdatasync","took":"1.019218386s","expected-duration":"1s"}
Dec 09 15:48:57.506305 pgsql1 bash[8949]: {"level":"warn","ts":"2021-12-09T15:48:57.505+0300","caller":"wal/wal.go:802","msg":"slow fdatasync","took":"1.03607368s","expected-duration":"1s"}
Dec 09 15:49:01.622165 pgsql1 bash[8949]: {"level":"warn","ts":"2021-12-09T15:49:01.621+0300","caller":"wal/wal.go:802","msg":"slow fdatasync","took":"1.157869735s","expected-duration":"1s"}

**Comment by vitabaks** [comment]
> "slow fdatasync","took":"1.013852853s","expected-duration":"1s"

Is the etcd data exactly on the SSD? 
Please check the path in the `ETCD_DATA_DIR` parameter in the etcd.conf

**Comment by DenisK32** [comment]
As I understand it, I need to move a separate etcd cluster to ssd disks. At the moment, I have everything spinning on three hosts.

**Comment by DenisK32** [comment]
This etcd jn SSD:

**Comment by vitabaks** [comment]
> server is likely overloaded

Avoid storing etcd data on the same drive along with other processes (such as the database) that are intensively using the resources of the disk subsystem! Store the etcd and postgresql data on different disks (see etcd_data_dir variable).

Overloaded (highload) database clusters may require the installation of the etcd cluster on dedicated servers, separate from the database servers.

**Comment by DenisK32** [comment]
Okay, thanks for answering my inquiries!
