### ISSUE TITLE
scale etcd and remove old node

### ISSUE THREAD

**Issue by mihsergeev** [vitabaks/postgresql_cluster#148]
Hello, tell me, is there any documentation or how-to ?

**Comment by vitabaks** [comment]
Hello @mihsergeev

etcd docs: 

https://etcd.io/docs/v3.3

**Comment by mihsergeev** [comment]
Thank you, it`s very cool playbook

**Comment by RDonii** [comment]
Hello. Is there any update in this repo that automates scaling the etcd cluster?

**Comment by vitabaks** [comment]
Not yet. TODO https://github.com/vitabaks/postgresql_cluster/issues/503
