### ISSUE TITLE
[Question] Is there a fork or similar project that uses Hashicorp Consul instead of etcd?

### ISSUE THREAD

**Issue by gc-ss** [vitabaks/postgresql_cluster#150]
Curious if there's a fork or similar project that uses Hashicorp Consul instead of etcd?

This would be invaluable to teams already using the Hashistack Consul (Nomad, Terraform, Vault and Waypoint)

**Comment by vitabaks** [comment]
Done. https://github.com/vitabaks/postgresql_cluster/pull/238
