### ISSUE TITLE
[Feature request] Could you upload role to galaxy.ansible.com?

### ISSUE THREAD

**Issue by patsevanton** [vitabaks/postgresql_cluster#151]
Hello!
Thanks for role!
Could you upload role to galaxy.ansible.com?

**Comment by vitabaks** [comment]
I did not plan to do this as it is not a single role but a set of several roles for performing cluster deployment

use meta/[main.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/meta/main.yml)


```
---
- src: https://github.com/vitabaks/postgresql_cluster.git
  scm: git
  version: master
  path: ./roles/
```

https://github.com/vitabaks/postgresql_cluster/issues/95

**Comment by vitabaks** [comment]
@patsevanton  well, it seems like the playbook was imported successfully

https://galaxy.ansible.com/vitabaks/postgresql_cluster

**Comment by vitabaks** [comment]
or specify an explicit role version to install

**Comment by vitabaks** [comment]
I recommend installing the version from the master branch as it has some fixes and improvements
