### ISSUE TITLE
Использование keepalived вместо vip-manager

### ISSUE THREAD

**Issue by kkrasnov1** [vitabaks/postgresql_cluster#156]
Здравствуйте!

Может стоит ли использовать keepelived с `vrrp_script check_patroni_primary { script "/usr/bin/curl -X GET -I --fail http://10.3.63.18:8008/primary"}` вместо vip-manager?

Дело в том что vip-manager определяет статус по DCS и если DCS недоступен, то виртуальный IP выключается через 1 сек, в то время как patroni ещё остановил postgres и может и не остановить если DCS станет доступен. keepalived в указанной конфигурации проверяет статус patroni и это, возможно, более правильный подход, т.к. учитывает таймауты patroni.

**Comment by vitabaks** [comment]
При не доступности DCS, Patroni перезапустит Leader в качели реплики.

**Comment by vitabaks** [comment]
Вы можете использовать схему с балансировкой нагрузки, там используется keepalived и haproxy .

**Comment by kkrasnov1** [comment]
> 

Перезапустит в качели через retry_timeout. Этого времени может хватить, чтобы DCS восстановился, но vip-manager уже уберет IP.

**Comment by kkrasnov1** [comment]
> Вы можете использовать схему с балансировкой нагрузки, там используется keepalived и haproxy .

При использовании haproxy есть следующие особенности:
1. в postgres не виден IP-адрес клиента
2. непонятно как использовать pg_hba и из-за этого возникают проблемы безопасности
3. при высокой нагрузке haproxy достаточно активно использует процессор

Хотелось бы избежать использования haproxy.

**Comment by vitabaks** [comment]
Попробуйте увеличить `vip_manager_interval`

time (in milliseconds) after which vip-manager wakes up and checks if it needs to register or release ip addresses.

**Comment by kkrasnov1** [comment]
> Попробуйте увеличить `vip_manager_interval`
> 
> time (in milliseconds) after which vip-manager wakes up and checks if it needs to register or release ip addresses.

Тогда даже при switchover переключение VIP будет с задержкой.

Возможно, источником информации для VIP должен быть не DCS, а Patroni, т.к. он использует DCS для определения лидера, но вносит свои задержки.
