### ISSUE TITLE
little fix for vip_manager repo

### ISSUE THREAD

**Issue by nwaddon** [vitabaks/postgresql_cluster#158]
current url 
vip_manager_package_repo: "https://github.com/cybertec-postgresql/vip-manager/releases/download/v{{ vip_manager_version }}/vip-manager-{{ vip_manager_version }}-1.x86_64.rpm"

**Comment by vitabaks** [comment]
@nwaddon thanks

fixed 333bbbc6be07640924770036d0dc3459accfb8b3
