### ISSUE TITLE
Zabbix to postgres connection problems

### ISSUE THREAD

**Issue by sojjan1337** [vitabaks/postgresql_cluster#178]
Hi!

If i connect to one of the postgres directly it works fine.
But when i connect to the VIP i get this in the log:

Zabbix log:

`  4978:20220607:091718.781 slow query: 120.218657 sec, "select oid from pg_type where typname='bytea'"
  4978:20220607:091718.781 database is down: reconnecting in 10 seconds
  4979:20220607:091718.781 database is down: reconnecting in 10 seconds
  4972:20220607:091718.781 [Z3005] query failed: [0] PGRES_FATAL_ERROR:FATAL:  query_wait_timeout
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
 [select oid from pg_type where typname='bytea']
  4972:20220607:091718.781 slow query: 120.223575 sec, "select oid from pg_type where typname='bytea'"
  4977:20220607:091718.781 database is down: reconnecting in 10 seconds
  4972:20220607:091718.781 database is down: reconnecting in 10 seconds`

pgbouncer.log

`2022-06-07 09:19:29.112 CEST [1158] WARNING C-0x562c435187c0: zabbix/zabbix@x.x.x.x:40910 pooler error: query_wait_timeout
`

And when i manually connect it works, but i get a timeout when i list database.

`psql -U zabbix -d zabbix -p 5000 -h VIP-IP
Password for user zabbix: 
psql (10.21, server 14.3)
WARNING: psql major version 10, server major version 14.
         Some psql features might not work.
Type "help" for help.

zabbix=> \l
`
`The connection to the server was lost. Attempting reset: Succeeded.`

**Comment by vitabaks** [comment]
https://github.com/vitabaks/postgresql_cluster/issues/89#issuecomment-772424588
