### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by sojjan1337** [vitabaks/postgresql_cluster#179]
Hi!

I'm done connecting the cluster towards Zabbix. Looking good. But i have a few questions about location of patroni and the error in pg_bouncer.

For troubleshooting.

Patroni
/var/log/patroni/patroni.log  <- **Couldn't find this one.**

PgBouncer
/var/log/pgbouncer/pgbouncer.log <- Found a problem in here for the leader in the cluster.

`2022-06-09 12:34:06.145 CEST [1084] WARNING C-0x555b08c9bb70: (nodb)/(nouser)@10.1.7.27:24222 pooler error: unsupported startup parameter: options`

Keepalived
journalctl -u keepalived.service

Postgres
/var/log/postgresql/postgresql-14-main.log

Thanks!

**Comment by vitabaks** [comment]
> /var/log/patroni/patroni.log <- Couldn't find this one.

See `patroni_log_destination: stderr  # or 'logfile'` in vars/main.yml

stderr by default

`sudo journalctl -u patroni`

> /var/log/pgbouncer/pgbouncer.log <- Found a problem in here:

try ti add `options` to `pgbouncer_ignore_startup_parameters`

example:
https://github.com/Athou/commafeed/issues/559


----

- etcd
- - `sudo journalctl -u etcd `
- haproxy 
- - `journalctl -u haproxy.service`
- Keepalived
- - `sudo journalctl -u keepalived.service`

**Comment by sojjan1337** [comment]
Thanks will try.
