### ISSUE TITLE
postgresql_data_dir: change it to another drive

### ISSUE THREAD

**Issue by sojjan1337** [vitabaks/postgresql_cluster#180]
Hi!
I have added a separate drive /sdb1 for postgres-data.

Is there a way to specify so the data will be created on that drive?

I mounted the new lvm drive and pointed it to that dir in the playbook, but after i run it, it didn't put the files on that drive. Instead it is located on the main drive as usual but to another location on that drive. And also it unmounted my drive.

Thanks alot!

**Comment by vitabaks** [comment]
Have you already tried changing the path in this variable? Did it not work for you?

Similar issue: https://github.com/vitabaks/postgresql_cluster/issues/169

**Comment by vitabaks** [comment]
playbook not removing mount points. 

this is a strange behavior for which I don't have an answer right now.  Have you tried deploying the cluster on a separate disk several times?

**Comment by sojjan1337** [comment]
I can try again!

**Comment by sojjan1337** [comment]
Works fine. I did something wrong
