### ISSUE TITLE
'dict object' has no attribute 'dev' in etcd_cluster.yml

### ISSUE THREAD

**Issue by chlordk** [vitabaks/postgresql_cluster#184]
Hi 

I have this error which firstly looks like a typo in vars/main.yml but that file it looks right.

Versions:
- postgresql_cluster 1.6.0 tar.gz
- Ansible 2.9.27
- Oracle Linux 8.6

> fatal: [fdbdmcnpxdd03]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'dev'\n\nThe error appears to be in '/home/hs/postgresql_cluster/etcd_cluster.yml': line 42, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Build a firewall_ports_dynamic_var\n      ^ here\n"}

msg:

> The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'dev'
> 
> The error appears to be in '/home/hs/postgresql_cluster/etcd_cluster.yml': line 42, column 7, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
>     - name: Build a firewall_ports_dynamic_var
>       ^ here

If I then set `dcs_exists: true` the error appears to be in `deploy_pgcluster.yml` and still the same variable `firewall_ports_dynamic_var`. It is like it tries to gather port numbers but the default list is then empty.

**Comment by vitabaks** [comment]
Please try the playbook from master

**Comment by chlordk** [comment]
I changed `hosts: all` to `hosts: postgres_cluster` otherwise it included all the servers in my inventory.

Previously I only ran `ansible --check` and did not get an error but a real run gave the 'dict object' error again. 

If I set `dcs_exists: true` the error is then:

> ok: [fdbdmcnpxdd01] => (item=balancers)
> fatal: [fdbdmcnpxdd01]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'dev'\n\nThe error appears to be in '/home/hs/postgresql_cluster/deploy_pgcluster.yml': line 76, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Build a firewall_ports_dynamic_var\n      ^ here\n"}

It seems like the gathering should occur somewhere else in the file.

**Comment by chlordk** [comment]
Solution: Use ip-numbers
