### ISSUE TITLE
Support for Transparent Data Encryption

### ISSUE THREAD

**Issue by colundrum** [vitabaks/postgresql_cluster#19]
Hello,
Can you tell me how to support Transparent Data Encryption inside this setup?
Regards

**Comment by vitabaks** [comment]
Hello @colundrum 
As far as I know, the PostgreSQL kernel does not provide TDE functions.

There is a patch from CYBERTEC for versions 9.6.12 and 12.1

> Transparent Data Encryption (TDE) is a CYBERTEC patch to PostgreSQL. It is currently the only implementation out there, to fully support transparent and cryptographically safe data (cluster) level encryption, independent of operating system or file system encryption.

Learn more: https://www.cybertec-postgresql.com/en/products/postgresql-transparent-data-encryption/

But this is already beyond the scope of this automation to deploy a high availability cluster.
