### ISSUE TITLE
add repo gpgcheck

### ISSUE THREAD

**Issue by HGCH81** [vitabaks/postgresql_cluster#191]
Hello,

when using variable "gpgcheck = no"  gpgkey is always necessaire 

- block:  # RedHat/CentOS
    - name: Add repository
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
    ** gpgkey: "{{ item.gpgkey }}"
        gpgcheck: "{{ item.gpgcheck }}"
      loop: "{{ yum_repository | flatten(1) }}"
      when: yum_repository | length > 0

- block:  # RedHat/CentOS
    - name: Add repository
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
    ** gpgkey: "{{ item.gpgkey | default(omit) }}"
        gpgcheck: "{{ item.gpgcheck || default('true') }}"
      loop: "{{ yum_repository | flatten(1) }}"
      when: yum_repository | length > 0

**Comment by vitabaks** [comment]
I will be grateful for your PR
