### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by seceylan** [vitabaks/postgresql_cluster#192]
What procedure should we follow to upgrade from PostgreSQL 13 to 14?

**Comment by vitabaks** [comment]
while on our own, since automation is not yet doing a postgresql upgrade, but this is in the plans https://github.com/vitabaks/postgresql_cluster/issues/147 , https://github.com/vitabaks/postgresql_cluster/issues/162

**Comment by vitabaks** [comment]
Please test https://github.com/vitabaks/postgresql_cluster/pull/301

**Comment by vitabaks** [comment]
Done.

https://github.com/vitabaks/postgresql_cluster/blob/master/roles/upgrade/README.md
