### ISSUE TITLE
Error while deploying

### ISSUE THREAD

**Issue by RoyGRad** [vitabaks/postgresql_cluster#197]
Hi, I'm getting this error while deploying the cluster no matter what I try. Can you assist, please?
Those it affects the cluster efficiency in any way?

![image](https://user-images.githubusercontent.com/104019377/187663271-de0b6ead-7acd-40d5-b8fe-7104a1a73bcf.png)

**Comment by vitabaks** [comment]
Hi @RoyGRad !

please show what you have specified in vars/system.yml

`sysctl_conf` variable

**Comment by vitabaks** [comment]
Yes, you can ignore it, but I would like to understand the reason for the error

**Comment by vitabaks** [comment]
In my case it works (ubuntu 22.04)

```
TASK [sysctl : Setting kernel parameters] ********************************************************************************************************************************************************************
ok: [172.31.17.229] => (item={'name': 'vm.overcommit_memory', 'value': '2'})
ok: [172.31.17.229] => (item={'name': 'vm.swappiness', 'value': '1'})
ok: [172.31.17.229] => (item={'name': 'vm.min_free_kbytes', 'value': '102400'})
ok: [172.31.17.229] => (item={'name': 'vm.dirty_expire_centisecs', 'value': '1000'})
ok: [172.31.17.229] => (item={'name': 'vm.dirty_background_bytes', 'value': '67108864'})
ok: [172.31.17.229] => (item={'name': 'vm.dirty_bytes', 'value': '536870912'})
ok: [172.31.17.229] => (item={'name': 'vm.zone_reclaim_mode', 'value': '0'})
ok: [172.31.17.229] => (item={'name': 'kernel.numa_balancing', 'value': '0'})
ok: [172.31.17.229] => (item={'name': 'kernel.sched_autogroup_enabled', 'value': '0'})
ok: [172.31.17.229] => (item={'name': 'net.ipv4.ip_nonlocal_bind', 'value': '1'})
ok: [172.31.17.229] => (item={'name': 'net.ipv4.ip_forward', 'value': '1'})
ok: [172.31.17.229] => (item={'name': 'net.ipv4.ip_local_port_range', 'value': '10000 65535'})
ok: [172.31.17.229] => (item={'name': 'net.core.netdev_max_backlog', 'value': '10000'})
ok: [172.31.17.229] => (item={'name': 'net.ipv4.tcp_max_syn_backlog', 'value': '8192'})
ok: [172.31.17.229] => (item={'name': 'net.core.somaxconn', 'value': '65535'})
ok: [172.31.17.229] => (item={'name': 'net.ipv4.tcp_tw_reuse', 'value': '1'})
```

**Comment by RoyGRad** [comment]
I’m running it on 20.04

[Radware]
Roy Ghuy
DevOps Engineer
Email: ***@***.******@***.***>
T:----------------
M:050-9476175
F:----------------
[Check out the latest and greatest from Radware]<https://www.radware.com/Resources/CampaignRedirector.html>

www.radware.com<https://www.radware.com/>

[Blog]<https://blog.radware.com/>  ***@***.*** <https://www.linkedin.com/companies/165642>  ***@***.*** <https://twitter.com/radware>   [youtube] <https://www.youtube.com/user/radwareinc>
Confidentiality note: This message, and any attachments to it, contains privileged/confidential information of RADWARE Ltd./RADWARE Inc. and may not be disclosed, used, copied, or transmitted in any form or by any means without prior written permission from RADWARE. If you are not the intended recipient, delete the message and any attachments from your system without reading or copying it, and kindly notify the sender by e-mail. Thank you.
We take data protection seriously. Check out our Privacy Policy<https://www.radware.com/privacypolicy.aspx>.
P Please consider your environmental responsibility before printing this e-mail

**Comment by RoyGRad** [comment]
Hi Vitaly,

I'm running it on Ubuntu 20.04.
Here is the system.yml

[system.txt](https://github.com/vitabaks/postgresql_cluster/files/9463750/system.txt)

**Comment by vitabaks** [comment]
at first glance, the variables are specified correctly

if you don't use iptables, I recommend commenting out the "net.netfilter.nf_conntrack_max" parameter

See commit a911cb56c6680c25b7b0cc2c08033ccacb4b6a07

**Comment by vitabaks** [comment]
please provide information for debugging

`ansible-playbook deploy_pgcluster.yml --tag sysctl -vvv >> ansible_sysctl.log`
