### ISSUE TITLE
disaster recovery

### ISSUE THREAD

**Issue by owen-xie** [vitabaks/postgresql_cluster#199]
Can this solution be used in a remote disaster recovery scenario? If so, how to configure the etcd cluster to ensure that the disaster recovery center can arbitrate normally after a data center is disconnected

**Comment by vitabaks** [comment]
Hi @owen-xie 

Yes, you can host a cluster in different data centers.

#### 1. Placement of cluster members in different data centers:
If you’d prefer a cross-data center setup, where the replicating databases are located in different data centers, etcd member placement becomes critical.

There are quite a lot of things to consider if you want to create a really robust etcd cluster, but there is one rule: do not placing all etcd members in your primary data center. See some [examples](https://www.cybertec-postgresql.com/en/introduction-and-how-to-etcd-clusters-for-patroni/).


#### 2. Disaster Recovery

A high availability cluster provides an automatic failover mechanism, and does not cover all disaster recovery scenarios. You must take care of backing up your data yourself.

**etcd**

Patroni nodes are dumping the state of the DCS options to disk upon for every change of the configuration into the file patroni.dynamic.json located in the Postgres data directory. The master (patroni leader) is allowed to restore these options from the on-disk dump if these are completely absent from the DCS or if they are invalid.
However, I recommend that you read the disaster recovery guide for the etcd cluster:

[etcd disaster recovery](https://etcd.io/docs/v3.3.12/op-guide/recovery)

**PostgreSQL (databases)**

I can recommend the following backup and restore tools:

[pgbackrest](https://github.com/pgbackrest/pgbackrest)
[pg_probackup](https://github.com/postgrespro/pg_probackup)
[wal-g](https://github.com/wal-g/wal-g)
Do not forget to validate your backups (for example [pgbackrest auto](https://github.com/vitabaks/pgbackrest_auto)).
