### ISSUE TITLE
Problem with add-repository.yml task

### ISSUE THREAD

**Issue by ziedb** [vitabaks/postgresql_cluster#20]
Hi

- **With ansible installed on Centos 7 :**

$ansible --version
ansible 2.9.1
 .....
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

- **pgnode01 and pgnode02 on Debian 9**
# uname -a
Linux pgnode01 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux
# python --version
Python 2.7.13

- **problem with add-reposotory.yml task** : 
TASK [Add repository] ***********************************************************************
task path: /home/iset/postgresql_cluster/tasks/add-repository.yml:19
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_apt_repository_payload_mZNQU0/ansible_apt_repository_payload.zip/ansible/modules/packaging/os/apt_repository.py", line 548, in main
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 464, in update
    raise FetchFailedException(e)

failed: [192.168.4.175] (item={u'repo': u'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main'}) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "codename": null, 
            "filename": null, 
            "install_python_apt": true, 
            "mode": null, 
            "repo": "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main", 
            "state": "present", 
            "update_cache": true, 
            "validate_certs": true
        }
    }, 
    "item": {
        "repo": "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main"
    }, 
    "msg": "apt cache update failed"
}

.......

task path: /home/iset/postgresql_cluster/tasks/add-repository.yml:19
failed: [192.168.4.175] (item={u'repo': u'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main'}) => {"ansible_loop_var": "item", "changed": false, "item": {"repo": "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main"}, "msg": "apt cache update failed"}
failed: [192.168.4.174] (item={u'repo': u'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main'}) => {"ansible_loop_var": "item", "changed": false, "item": {"repo": "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main"}, "msg": "apt cache update failed"}

**Best regards**

**Comment by vitabaks** [comment]
Hi @ziedb 
Please execute the command on pgnode01 server:
`sudo apt-get update`

and send me the result.

**Comment by ziedb** [comment]
Thank you vitabaks  for your response
here the results
root@pgnode01:~# apt-get update
Ign:1 http://ftp.de.debian.org/debian stretch InRelease                                                                   
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease                                                
Hit:3 http://ftp.de.debian.org/debian stretch-updates InRelease          
Hit:4 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease     
Hit:5 http://ftp.de.debian.org/debian stretch Release                    
Reading package lists... Done

**Comment by vitabaks** [comment]
there’s no problem ...

try again `ansible-playbook deploy_pgcluster.yml`

**Comment by ziedb** [comment]
Thank you for your help it's ok now
And I can display cluster members 
root@pgnode01:~# patronictl -c /etc/patroni/patroni.yml list  postgres-cluster 
+------------------+----------+---------------+--------+---------+----+-----------+
|     Cluster      |  Member  |      Host     |  Role  |  State  | TL | Lag in MB |
+------------------+----------+---------------+--------+---------+----+-----------+
| postgres-cluster | pgnode01 | 192.168.4.176 | Leader | running |  1 |           |
| postgres-cluster | pgnode02 | 192.168.4.177 |        | running |  1 |         0 |
+------------------+----------+---------------+--------+---------+----+-----------+

But I have error message related to  cluster ip address, can you help me how to fix these problems ?


TASK [wait for the cluster ip address (VIP) "10.128.64.145" is running] ***************************************************
ok: [192.168.4.176]
fatal: [192.168.4.177]: FAILED! => {"changed": false, "elapsed": 61, "msg": "Timeout when waiting for 10.128.64.145:22"}

Please find attached  the out put of ansible-playbook deploy_pgcluster.yml
[Output.pdf](https://github.com/vitabaks/postgresql_cluster/files/3999045/Output.pdf)

Best regards

**Comment by vitabaks** [comment]
> Thank you for your help it's ok now

Ok.

Thus, the cause of the “apt cache cache failed” problem is still unknown. I can not reproduce this problem.
Therefore, I can only recall the [recommendation](https://github.com/vitabaks/postgresql_cluster#recommendations):
`Update your operating system on your target servers before deploying`

**Comment by vitabaks** [comment]
> But I have error message related to cluster ip address, can you help me how to fix these problems ?

You did not provide an IP address for your subnet.

"10.128.64.145" is the address for example, you must specify your IP address in the variable cluster_vip.

Specify the cluster_vip variable, then run the playbook with the tags so that it completes the deployment.

`ansible-playbook deploy_pgcluster.yml --tags "vip_manager, postgresql_users, postgresql_databases, postgresql_extensions, cluster_info"`

**Comment by ziedb** [comment]
Thank you, 
It is ok  now for cluster_vip,
