### ISSUE TITLE
Feature request: vm.nr_hugepages

### ISSUE THREAD

**Issue by chlordk** [vitabaks/postgresql_cluster#202]
Hi

To use huge_pages one has to manually enable it on all PostgreSQL servers.

I have made a playbook to do it but it would be a little better if it was part of deploy_cluster.yml.
And it should only be executed when 'huge_pages' are 'true' in prostgresql.conf
The task has to be executed before Patroni is started.

> ---
> - hosts: postgres_cluster
>  become: true
>  tasks:
>    - name: Set huges_pages
>     sysctl:
>        name: vm.nr_hugepages
>        value: '2048'
>        sysctl_file: /etc/sysctl.d/50-hugepages.conf
>        sysctl_set: yes
>       state: present
>       reload: yes

**Comment by vitabaks** [comment]
@chlordk Make a PR please

**Comment by vitabaks** [comment]
Please see sysctl_conf: variables .
