### ISSUE TITLE
how to add a new database user using a playbook

### ISSUE THREAD

**Issue by nishantcha1997** [vitabaks/postgresql_cluster#204]
we have created new user via a cli & pgadmin4 also .but during access the db from new user we get SASL authentication error .

**Comment by nishantcha1997** [comment]
if we create psql user at the time of installation through vars/main.yaml then we are able to login through this user then why we cant add a new user after installation & use it?

**Comment by vitabaks** [comment]
Hi @nishantcha1997 

If you are using pgbouncer, then after adding a new user, you also need to add this user to the pgbouncer configuration `/etc/pgbouncer/userlist.txt`.

#### how to add a new database user using a playbook:

1. Specify the user in the `postgresql_users` variable (vars/main.yml)
2. Run playbook with tag: 

`ansible-playbook deploy_pgcluster.yml --tags "postgresql_users"`

If you use pgbouncer

`ansible-playbook deploy_pgcluster.yml --tags "postgresql_users, pgbouncer_generate_userlist"`


See the list of available tags:

https://github.com/vitabaks/postgresql_cluster/blob/master/tags.md
