### ISSUE TITLE
Can pgAdmin connect to the Virtual IP?

### ISSUE THREAD

**Issue by chlordk** [vitabaks/postgresql_cluster#205]
The problem is that from pgAdmin I don't know who is the *leader*, so I have to connect to all 3 nodes. Otherwise I would connect to virtual IP but that is managed by pgbouncer and pgAdmin does not support that.

I'm running a cluster like this.

IP - ports - name
- 10.42.69.5 - 6432 - virtual IP
- 10.42.69.6 - 5432 6432 - node 1
- 10.42.69.7 - 5432 6432 - node 2
- 10.42.69.8 - 5432 6432 - node 3

pgAdmin can fine connect to node 1 on port 5432.
pgAdmin can not connect through pgbouncer but that's another problem.
The virtual IP only listen on port 6432 (pgbouncer) not 5432, is this the way it is supposed work?

I guess I could remove pgbouncer and make it work but I like to have pgbouncer for use.

**Comment by vitabaks** [comment]
Hi @chlordk 

As I understand it, you use the "[Type B](https://github.com/vitabaks/postgresql_cluster#type-b-postgresql-high-availability-only)" scheme.

You connect pgAdmin the same way you do for the application servers using VIP

VIP: 10.42.69.5 
Port: 6432 

> pgAdmin can not connect through pgbouncer but that's another problem.

What error are you getting?

Maybe it's related to adding a new user, like in this issue?https://github.com/vitabaks/postgresql_cluster/issues/204


> The virtual IP only listen on port 6432 (pgbouncer) not 5432, is this the way it is supposed work?

yes that's how it should work.

**Comment by chlordk** [comment]
> As I understand it, you use the "[Type B](https://github.com/vitabaks/postgresql_cluster#type-b-postgresql-high-availability-only)" scheme.

Yes, my app doesn't support "reading connection".

> > pgAdmin can not connect through pgbouncer but that's another problem.
> 
> What error are you getting?

I found out afterwards that pgAdmin can not go through pgbouncer. 
pgbouncer filter something out which make pgAdmin not working.

> > The virtual IP only listen on port 6432 (pgbouncer) not 5432, is this the way it is supposed work?
> 
> yes that's how it should work.

Well, then pgAdmin must be connected to each node, not only virtual IP.
One has to poke around for any errors or check out who is the leader in an another way.

**Comment by vitabaks** [comment]
I don't use pgAdmin, try [dbeaver](https://dbeaver.io)

**Comment by vitabaks** [comment]
for errors, see the pgbouncer logs
