### ISSUE TITLE
TASK [patroni : Wait for port 8008 to become open on the host]

### ISSUE THREAD

**Issue by davideferrero** [vitabaks/postgresql_cluster#207]
Hi, i'm trying to use your code to build my own cluster, I can't get out of this problem.
I have installed 3 VM (Ubuntu 22.04) from a template with Terraform, and near the end of a playbook, there came out that errors.

`TASK [patroni : Wait for port 8008 to become open on the host]`

Probably the problem is on postgresql that wont start.
If i try to launch the `psql` command on the master host it give me that:

`psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?`

I simply modify the invenotry and the main where needed.
Do someone have some ideas? Or do you need more info? Ty <3

**Comment by AleksandrMalinovskiy** [comment]
I have the same problem. But here is what I found in log patroni.
Patroni doesn't work after executing task

Oct 13 11:46:35 pgnode02 patroni[13357]: Traceback (most recent call last):
Oct 13 11:46:35 pgnode02 patroni[13357]:   File "/usr/local/bin/patroni", line 10, in <module>
Oct 13 11:46:35 pgnode02 patroni[13357]:     sys.exit(main())
Oct 13 11:46:35 pgnode02 patroni[13357]:   File "/usr/local/lib/python3.7/dist-packages/patroni/__main__.py", line 143, in main
Oct 13 11:46:35 pgnode02 patroni[13357]:     return patroni_main()
Oct 13 11:46:35 pgnode02 patroni[13357]:   File "/usr/local/lib/python3.7/dist-packages/patroni/__main__.py", line 135, in patroni_main
Oct 13 11:46:35 pgnode02 patroni[13357]:     abstract_main(Patroni, schema)
Oct 13 11:46:35 pgnode02 patroni[13357]:   File "/usr/local/lib/python3.7/dist-packages/patroni/daemon.py", line 75, in abstract_main
Oct 13 11:46:35 pgnode02 patroni[13357]:     from .config import Config, ConfigParseError
Oct 13 11:46:35 pgnode02 patroni[13357]:   File "/usr/local/lib/python3.7/dist-packages/patroni/config.py", line 13, in <module>
Oct 13 11:46:35 pgnode02 patroni[13357]:     from patroni.postgresql.config import CaseInsensitiveDict, ConfigHandler
Oct 13 11:46:35 pgnode02 patroni[13357]:   File "/usr/local/lib/python3.7/dist-packages/patroni/postgresql/__init__.py", line 14, in <module>
Oct 13 11:46:35 pgnode02 patroni[13357]:     from psutil import TimeoutExpired
Oct 13 11:46:35 pgnode02 patroni[13357]: ModuleNotFoundError: No module named 'psutil'

**Comment by vitabaks** [comment]
make sure that you have specified private IP addresses in inventory and not public ones. The ports specified [here](https://github.com/vitabaks/postgresql_cluster#port-requirements) must be open between the servers.

**Comment by vitabaks** [comment]
`systemctl status patroni`

and please attuch the full Patroni log

`sudo cat /var/log/syslog | grep patroni`

**Comment by AleksandrMalinovskiy** [comment]
Installed on ubuntu everything works.
what is the entry point for the cluster?
