### ISSUE TITLE
fatal: The task includes an option with an undefined variable.

### ISSUE THREAD

**Issue by tbalbers** [vitabaks/postgresql_cluster#211]
Hiya!
Thanks for a cool collection, I've run into an error that I think surfaced after I updated ansible to version:
ansible [core 2.13.5]
python version = 3.9.2
jinja version = 3.1.2

This is what I'm seeing:
`FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'str object' has no attribute 'name'\n\nThe error appears to be in 'roles/sysctl/tasks/main.yml': line 12, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Setting kernel parameters\n      ^ here\n"}`

It seems to come from roles/sysctl/tasks/main.yml, where the line
`sysctl_conf_dynamic_var: "{{ sysctl_conf_dynamic_var |default([]) }} + {{ sysctl_conf[item] | flatten(1) }}"`  might be the culprit(because it looks like an undefined variable to me).

However I can't really figure out what to do about it.

Any suggestions are appreciated, thanks.

/tony

**Comment by vitabaks** [comment]
Hello @tbalbers 

ave you tried using the latest version of the playbook from the master branch?

**Comment by linuxfreakus** [comment]
I printed debug output and found it was treating the concatenated lists as a string and then forcing it to a list was flattening it to a list of characters but you can build the list this way instead and then you don't need to force it to a list in the second step either:

```
sysctl_conf_dynamic_var: "{{ sysctl_conf_dynamic_var | default([]) + (sysctl_conf[item] | flatten(1)) }}"
```

**Comment by vitabaks** [comment]
Thanks @linuxfreakus 

could you prepare a PR?

**Comment by linuxfreakus** [comment]
@vitabaks here you go: https://github.com/vitabaks/postgresql_cluster/pull/214

**Comment by vitabaks** [comment]
merged
