### ISSUE TITLE
Pgbouncer didn't listen Cluster-VIP with VIP-Manager deployment

### ISSUE THREAD

**Issue by pronichev** [vitabaks/postgresql_cluster#219]
Hello!
I'm using 3 nodes deployment with VIP-Manager. 
There is a WARN in pgbouncer log just after deployment:
```
2022-11-18 06:52:20.177 UTC [23431] LOG listening on 172.16.163.75:6432
2022-11-18 06:52:20.177 UTC [23431] WARNING cannot listen on 172.16.163.151:6432: bind(): Cannot assign requested address

```
172.16.163.151 - is my cluster_vip

Pgbouncer is not listening on cluster_vip after failover to another node also. 
How to automate restart of pgbouncer after deployment and after failover?

**Comment by vitabaks** [comment]
> Cannot assign requested address

VIP is automatically launched to the server with the master role, this address will not be on all other servers.

check if there is an ip address on the server with the leader role (`ip a`) and the pgbouncer log.

**Comment by pronichev** [comment]
In deployment steps:
First run pgbouncer and there no cluster_vip on master  because no running vip_manager.
Second run vip-manager and `ip a` return 2 IP's on interface

After deployment finished there are no port binding on cluster_ip port 6432 on master (`ss -ln | grep tcp | grep LISTEN`)

**Comment by pronichev** [comment]
> > Cannot assign requested address
> 
> VIP is automatically launched to the server with the master role, this address will not be on the replica servers.
> 
> check if there is an ip address on the server with the leader role (`ip a`) and the pgbouncer log.

Log from first message is from master (leader) after deployment.

**Comment by vitabaks** [comment]
Thanks , i will check it out.

**Comment by pronichev** [comment]
> if the `cluster_vip` variable is set then pgbouncer listens the VIP address https://github.com/vitabaks/postgresql_cluster/blob/master/roles/pgbouncer/templates/pgbouncer.ini.j2#L12

My workaround is set listen_addr = 0.0.0.0

**Comment by davidmehren** [comment]
I can confirm the issue:
After a switch of the leader, the virtual IP gets transferred correctly to the new leading host, but pgbouncer does not start actually using it until a restart. Setting `listen_addr = 0.0.0.0` in pgbouncer.ini works around the problem.

**Comment by vitabaks** [comment]
Added the `pgbouncer_listen_addr` variable with default value: `0.0.0.0`
