### ISSUE TITLE
Question about "start failed " status

### ISSUE THREAD

**Issue by ziedb** [vitabaks/postgresql_cluster#22]
Hi
I deployed a cluster with 3 members;

[master]
clusterProd  (debian-9,postgresql-10)

[replica]
poolback2 (debian-9,postgresql-10)
TomcatSlave (CentOS Linux release 7.6, postgresql-10)

- output of the task excution
TASK [PostgreSQL Cluster health] ******************************************************
ok: [197.13.12.131] => {
    "patronictl_result.stdout_lines": [
        "+------------------+-------------+--------------------+--------+--------------+-----+-----------+", 
        "|     Cluster      |    Member   |        Host        |  Role  |    State     |  TL | Lag in MB |", 
        "+------------------+-------------+--------------------+--------+--------------+-----+-----------+", 
        "| postgres-cluster | TomcatSlave |HidenIP:5434 |        | start failed |     |   unknown |", 
        "| postgres-cluster | clusterProd | HidenIP:5434 | Leader |   running    | 118 |           |", 
        "| postgres-cluster |  poolback2  | HidenIP:5434 |        |   running    | 118 |         0 |", 
        "+------------------+-------------+--------------------+--------+--------------+-----+-----------+"
    ]
}

I can not start the postgresql server on centos node:

_[root@TomcatSlave ~]# systemctl start postgresql-10
Job for postgresql-10.service failed because the control process exited with error code. See "systemctl status postgresql-10.service" and "journalctl -xe" for details.
[root@TomcatSlave ~]# systemctl status postgresql-10.service
● postgresql-10.service - PostgreSQL 10 database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql-10.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2020-01-30 20:43:39 CET; 9s ago
     Docs: https://www.postgresql.org/docs/10/static/
  Process: 29512 ExecStart=/usr/pgsql-10/bin/postmaster -D ${PGDATA} (code=exited, status=1/FAILURE)
  Process: 29505 ExecStartPre=/usr/pgsql-10/bin/postgresql-10-check-db-dir ${PGDATA} (code=exited, status=0/SUCCESS)
 Main PID: 29512 (code=exited, status=1/FAILURE)

Jan 30 20:43:39 TomcatSlave systemd[1]: Starting PostgreSQL 10 database server...
Jan 30 20:43:39 TomcatSlave postmaster[29512]: 2020-01-30 19:43:39.334 GMT [29512] LOG:  could not open...tory
Jan 30 20:43:39 TomcatSlave postmaster[29512]: 2020-01-30 19:43:39.334 GMT [29512] LOG:  could not open...tory
Jan 30 20:43:39 TomcatSlave systemd[1]: postgresql-10.service: main process exited, code=exited, status...LURE
Jan 30 20:43:39 TomcatSlave systemd[1]: Failed to start PostgreSQL 10 database server.
Jan 30 20:43:39 TomcatSlave systemd[1]: Unit postgresql-10.service entered failed state.
Jan 30 20:43:39 TomcatSlave systemd[1]: postgresql-10.service failed.
Hint: Some lines were ellipsized, use -l to show in full._

During the deployment, I removed the content of /var/lib/postgresql/10/main/* directory. 
because I have the following error
TASK [fail] ***************************************************************************
fatal: [IP-OF-poolback2-NODE]: FAILED! => {"changed": false, "msg": "Whoops! data directory /var/lib/postgresql/10/main is already initialized"}
fatal: [IP-OF-TomcatSlave-NODE]: FAILED! => {"changed": false, "msg": "Whoops! data directory /var/lib/pgsql/10/data is already initialized"}

Thank you

**Comment by ziedb** [comment]
Resolved when  postgresql_exists='true' for replica node.

**Comment by vitabaks** [comment]
The variable postgresql_exists = 'true' should be specified only for the master node.

It is assumed that the servers in the [replica] group are unprepared (operating system is installed only). On the servers in the [replica] group there should not be an installed and running postgresql service.

Thank you for your issue, I have an idea how this can be improved.
