### ISSUE TITLE
simplify the installation of a timescaledb cluster

### ISSUE THREAD

**Issue by vitabaks** [vitabaks/postgresql_cluster#235]
> Can i enable timescale from start in a configuration-file?
The same way as you enable ha-proxy?
enable_timescale = True

https://github.com/vitabaks/postgresql_cluster/issues/31#issuecomment-1141335355

---
_Make your contribution to the development of the project, become a [sponsor](https://github.com/vitabaks/postgresql_cluster#sponsor-this-project)_

**Comment by sojjan1337** [comment]
This is gonna be awesome when it's done!

**Comment by vitabaks** [comment]
PR: https://github.com/vitabaks/postgresql_cluster/pull/335

**Comment by vitabaks** [comment]
Done.
