### ISSUE TITLE
Wait for port 8008 to become open on the host

### ISSUE THREAD

**Issue by derejeabdissa** [vitabaks/postgresql_cluster#240]
TASK [patroni : Wait for port 8008 to become open on the host] ******************************

FAILED - RETRYING: Check that the patroni is healthy on the replica server (1200 retries left).
FAILED - RETRYING: Check that the patroni is healthy on the replica server (1200 retries left).

I don't know why this health check is keep failing. I waited  more than 20 minutes for this, no change

**Comment by vitabaks** [comment]
@derejeabdissa check the patroni log to find out why it didn't start

`sudo journalctl -u patroni -n 100 -f`

and maybe also a PostgreSQL log.

**Comment by derejeabdissa** [comment]
Thank you very much for the quick response. Here is the logs from Patroni's side.

an 08 20:59:56 dbnode02 patroni[146179]: 2023-01-08 20:59:56,292 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:00:04 dbnode02 systemd[1]: Stopping Runners to orchestrate a high-availability PostgreSQL - Patroni...
Jan 08 21:01:04 dbnode02 systemd[1]: patroni.service: State 'stop-sigterm' timed out. Killing.
Jan 08 21:01:04 dbnode02 systemd[1]: patroni.service: Killing process 146179 (patroni) with signal SIGKILL.
Jan 08 21:01:04 dbnode02 systemd[1]: patroni.service: Main process exited, code=killed, status=9/KILL
Jan 08 21:01:04 dbnode02 systemd[1]: patroni.service: Failed with result 'timeout'.
Jan 08 21:01:04 dbnode02 systemd[1]: Stopped Runners to orchestrate a high-availability PostgreSQL - Patroni.
Jan 08 21:15:37 dbnode02 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL - Patroni.
Jan 08 21:15:37 dbnode02 patroni[215212]: 2023-01-08 21:15:37,753 INFO: Selected new etcd server http://172.18.7.233:2379
Jan 08 21:15:37 dbnode02 patroni[215212]: 2023-01-08 21:15:37,756 INFO: No PostgreSQL configuration items changed, nothing to reload.
Jan 08 21:15:37 dbnode02 patroni[215212]: 2023-01-08 21:15:37,763 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:15:37 dbnode02 patroni[215212]: 2023-01-08 21:15:37,766 INFO: trying to bootstrap from leader 'dbnode01'
Jan 08 21:15:47 dbnode02 patroni[215212]: 2023-01-08 21:15:47,762 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:15:47 dbnode02 patroni[215212]: 2023-01-08 21:15:47,764 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:15:57 dbnode02 patroni[215212]: 2023-01-08 21:15:57,761 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:15:57 dbnode02 patroni[215212]: 2023-01-08 21:15:57,763 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:16:07 dbnode02 patroni[215212]: 2023-01-08 21:16:07,761 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:16:07 dbnode02 patroni[215212]: 2023-01-08 21:16:07,763 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:16:17 dbnode02 patroni[215212]: 2023-01-08 21:16:17,761 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:16:17 dbnode02 patroni[215212]: 2023-01-08 21:16:17,763 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:16:27 dbnode02 patroni[215212]: 2023-01-08 21:16:27,761 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:16:27 dbnode02 patroni[215212]: 2023-01-08 21:16:27,763 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:16:37 dbnode02 patroni[215212]: 2023-01-08 21:16:37,761 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:16:37 dbnode02 patroni[215212]: 2023-01-08 21:16:37,763 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:16:47 dbnode02 patroni[215212]: 2023-01-08 21:16:47,761 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:16:47 dbnode02 patroni[215212]: 2023-01-08 21:16:47,764 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:16:57 dbnode02 patroni[215212]: 2023-01-08 21:16:57,761 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:16:57 dbnode02 patroni[215212]: 2023-01-08 21:16:57,764 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:17:07 dbnode02 patroni[215212]: 2023-01-08 21:17:07,761 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:17:07 dbnode02 patroni[215212]: 2023-01-08 21:17:07,764 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:17:17 dbnode02 patroni[215212]: 2023-01-08 21:17:17,761 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:17:17 dbnode02 patroni[215212]: 2023-01-08 21:17:17,763 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:17:27 dbnode02 patroni[215212]: 2023-01-08 21:17:27,761 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:17:27 dbnode02 patroni[215212]: 2023-01-08 21:17:27,763 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:17:37 dbnode02 patroni[215212]: 2023-01-08 21:17:37,761 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:17:37 dbnode02 patroni[215212]: 2023-01-08 21:17:37,763 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:17:47 dbnode02 patroni[215212]: 2023-01-08 21:17:47,761 INFO: Lock owner: dbnode01; I am dbnode02
Jan 08 21:17:47 dbnode02 patroni[215212]: 2023-01-08 21:17:47,763 INFO: bootstrap from leader 'dbnode01' in progress
Jan 08 21:17:47 dbnode02 patroni[215212]: 2023-01-08 21:17:47,903 ERROR: Error when fetching backup: pg_basebackup exited with code=1

**Comment by derejeabdissa** [comment]
I removed Etcd in case it keeps information that the cluster was already initialized. Here is patroni's logs after 
Jan 08 22:42:35 dbnode01 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL - Patroni.
Jan 08 22:42:35 dbnode01 patroni[203080]: 2023-01-08 22:42:35,589 INFO: Selected new etcd server http://xxx.xx.x.xxx:2379
Jan 08 22:42:35 dbnode01 patroni[203080]: 2023-01-08 22:42:35,593 INFO: No PostgreSQL configuration items changed, nothing to reload.
Jan 08 22:42:35 dbnode01 patroni[203080]: 2023-01-08 22:42:35,600 INFO: Lock owner: None; I am dbnode01
Jan 08 22:42:35 dbnode01 patroni[203080]: 2023-01-08 22:42:35,605 INFO: trying to bootstrap a new cluster
Jan 08 22:42:35 dbnode01 patroni[203121]: The files belonging to this database system will be owned by user "postgres".
Jan 08 22:42:35 dbnode01 patroni[203121]: This user must also own the server process.
Jan 08 22:42:35 dbnode01 patroni[203121]: The database cluster will be initialized with locale "en_US.UTF-8".
Jan 08 22:42:35 dbnode01 patroni[203121]: The default text search configuration will be set to "english".
Jan 08 22:42:35 dbnode01 patroni[203121]: Data page checksums are enabled.
Jan 08 22:42:35 dbnode01 patroni[203121]: fixing permissions on existing directory /var/lib/pgsql/14/data ... ok
Jan 08 22:42:35 dbnode01 patroni[203121]: creating subdirectories ... ok
Jan 08 22:42:35 dbnode01 patroni[203121]: selecting dynamic shared memory implementation ... posix
Jan 08 22:42:35 dbnode01 patroni[203121]: selecting default max_connections ... 100
Jan 08 22:42:35 dbnode01 patroni[203121]: selecting default shared_buffers ... 128MB
Jan 08 22:42:35 dbnode01 patroni[203121]: selecting default time zone ... America/New_York
Jan 08 22:42:35 dbnode01 patroni[203121]: creating configuration files ... ok
Jan 08 22:42:35 dbnode01 patroni[203121]: running bootstrap script ... ok
Jan 08 22:42:36 dbnode01 patroni[203121]: performing post-bootstrap initialization ... ok
Jan 08 22:42:36 dbnode01 patroni[203121]: syncing data to disk ... ok
Jan 08 22:42:36 dbnode01 patroni[203121]: initdb: warning: enabling "trust" authentication for local connections
Jan 08 22:42:36 dbnode01 patroni[203121]: You can change this by editing pg_hba.conf or using the option -A, or
Jan 08 22:42:36 dbnode01 patroni[203121]: --auth-local and --auth-host, the next time you run initdb.
Jan 08 22:42:36 dbnode01 patroni[203121]: Success. You can now start the database server using:
Jan 08 22:42:36 dbnode01 patroni[203121]:     /usr/pgsql-14/bin/pg_ctl -D /var/lib/pgsql/14/data -l logfile start
Jan 08 22:42:36 dbnode01 patroni[203080]: 2023-01-08 22:42:36,572 INFO: postmaster pid=203136
Jan 08 22:42:37 dbnode01 patroni[203136]: 2023-01-08 22:42:37 EST [203136-1]  LOG:  redirecting log output to logging collector process
Jan 08 22:42:37 dbnode01 patroni[203136]: 2023-01-08 22:42:37 EST [203136-2]  HINT:  Future log output will appear in directory "/var/log/postgresql".
Jan 08 22:42:37 dbnode01 patroni[203080]: 2023-01-08 22:42:37,610 INFO: establishing a new patroni connection to the postgres cluster
Jan 08 22:42:37 dbnode01 patroni[203080]: 2023-01-08 22:42:37,619 INFO: running post_bootstrap
Jan 08 22:42:37 dbnode01 patroni[203080]: 2023-01-08 22:42:37,658 INFO: initialized a new cluster
Jan 08 22:42:47 dbnode01 patroni[203080]: 2023-01-08 22:42:47,650 INFO: no action. I am (dbnode01), the leader with the lock
Jan 08 22:42:57 dbnode01 patroni[203080]: 2023-01-08 22:42:57,661 INFO: no action. I am (dbnode01), the leader with the lock
Jan 08 22:43:07 dbnode01 patroni[203080]: 2023-01-08 22:43:07,649 INFO: no action. I am (dbnode01), the leader with the lock
Jan 08 22:43:17 dbnode01 patroni[203080]: 2023-01-08 22:43:17,648 INFO: no action. I am (dbnode01), the leader with the lock
Jan 08 22:43:27 dbnode01 patroni[203080]: 2023-01-08 22:43:27,649 INFO: no action. I am (dbnode01), the leader with the lock
Jan 08 22:43:37 dbnode01 patroni[203080]: 2023-01-08 22:43:37,649 INFO: no action. I am (dbnode01), the leader with the lock
Jan 08 22:43:47 dbnode01 patroni[203080]: 2023-01-08 22:43:47,648 INFO: no action. I am (dbnode01), the leader with the lock

**Comment by vitabaks** [comment]
> Error when fetching backup: pg_basebackup exited with code=1

An error occurred when copying data to a replica using pg_basebackup. 

Please check the PostgreSQL log on the leader.

**Comment by vitabaks** [comment]
> I removed Etcd in case it keeps information that the cluster was already initialized.

When your cluster is successfully initialized, the leader is available, and the problem is only with the replica, it is not necessary to completely remove the cluster from DCS (etcd).

**Comment by vitabaks** [comment]
Feel free to open the issue if the problem is still relevant.
