### ISSUE TITLE
Please add install wal-g if wal-g = true

### ISSUE THREAD

**Issue by patsevanton** [vitabaks/postgresql_cluster#25]

**Comment by vitabaks** [comment]
Install wal-g package only?
No need to prepare wal-g configuration?

Please provide a link to the rpm and deb packages.

**Comment by vitabaks** [comment]
> Please provide a link to the rpm and deb packages.

Ok, can use a binary file.

https://github.com/wal-g/wal-g#installation

**Comment by vitabaks** [comment]
Pull Request  https://github.com/vitabaks/postgresql_cluster/pull/28

**Comment by vitabaks** [comment]
Done https://github.com/vitabaks/postgresql_cluster/commit/1e461f9d77dd65e416dcd23cff5ecf61e33da330
