### ISSUE TITLE
Does ansible playbooks/roles allow adding permissions for multiple users to particular databases?

### ISSUE THREAD

**Issue by kokosandim** [vitabaks/postgresql_cluster#251]
Thanks for that great playbook!

The question:
does ansible playbooks/roles allow adding permissions for multiple users to particular databases?

I did not find the answer in the documentation, I admit that I read it inattentively

Thanks in advance

**Comment by vitabaks** [comment]
Hi @kokosandim 

Yes. Module `postgresql_privs` \
Doc: https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_privs_module.html

> for multiple users to particular databases

Use [loop](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html)

Currently postgresql_privs not in my playbook, but you can add such functionality.

**Comment by kokosandim** [comment]
Thanks, got it!
