### ISSUE TITLE
Consul dependency installation task fails on ec2

### ISSUE THREAD

**Issue by oxycash** [vitabaks/postgresql_cluster#252]
I have already updated the user on inventory file to ubuntu. I have manually checked the instance and pip/pip3 exists.

EC2 AMI 
```
ubuntu@pgnode01:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

Ansible verbose: 
```
TASK [consul : Install netaddr dependency on controlling host (with --user)] **************************************************************************************************************************************************************************************************
task path: /home/ubuntu/postgresql_cluster/roles/consul/tasks/main.yml:17
fatal: [172.31.73.79 -> 127.0.0.1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "chdir": null,
            "editable": false,
            "executable": null,
            "extra_args": "--user",
            "name": [
                "netaddr"
            ],
            "requirements": null,
            "state": "present",
            "umask": null,
            "version": null,
            "virtualenv": null,
            "virtualenv_command": "virtualenv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    },
    "msg": "Unable to find any of pip3 to use.  pip needs to be installed."
}

```

**Comment by vitabaks** [comment]
controlling host is the server from which you run ansible.  Please make sure pip is installed.

**Comment by vitabaks** [comment]
controlling host is the server from which you run ansible.  Please make sure pip is installed.

TODO: I think this can be improved by automating the installation of python3-pip on the controlling host.

**Comment by oxycash** [comment]
Thanks, i definitely missed that in the rush.

**Comment by vitabaks** [comment]
> TODO: I think this can be improved by automating the installation of python3-pip on the controlling host.

Done 12812fba1a37b36f4947da9d1c52dda3269af64d

**Comment by oxycash** [comment]
Hi,

I would like to understand few things. Kindly help.

Does pg_hba get modified with standby node ip info after master node db init?

**Comment by vitabaks** [comment]
@oxycash please note that you are asking a question in an issue that is already closed and the topic of which is completely different. \
Feel free to open a new issue.
