### ISSUE TITLE
Deploy and managing multiple clusters

### ISSUE THREAD

**Issue by P1ton** [vitabaks/postgresql_cluster#261]
Hi, I want to deploy and manage multiple clusters with different settings from one playbook, but I can't figure out how to properly organize inventory and settings because there is only one vars/main.yml file and group one exemplare group_vars. 
I am new to ansible, thanks in advance for your help

**Comment by vitabaks** [comment]
Hi @P1ton 

There are at least two approaches here:

1) copy the repository for each cluster (own inventory and its own variable values)
2) create several [inventory](https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html) and move variables to the group_vars level for each server group (test, staging, production, etc).

**Comment by P1ton** [comment]
> Hi @P1ton
> 
> There are at least two approaches here:
> 
>     1. copy the repository for each cluster (own inventory and its own variable values)
> 
>     2. create several [inventory](https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html) and move variables (unique to this host group) to the `group_vars` level for each server group (test, staging, production, etc).
> 
> 
> Example:
> 
>     * inventory/**test**
> 
>     * inventory/**staging**
> 
>     * inventory/**production**
> 
>     * inventory/group_vars/**test**
> 
>     * inventory/group_vars/**staging**
> 
>     * inventory/group_vars/**production**
> 
>     * inventory/group_vars/all
> 
>     * inventory/group_vars/master
> 
>     * inventory/group_vars/replica
> 
> 
> then you specify the required inventory when deploying
> 
> `ansible-playbook -i inventory/test deploy_pgcluster.yml`

Hi, I want to have different variable values which are in var/main.yml , like postgresql_version.
I created the following structure
├── inventory
│  └── test
│  ├── group_vars
│  │  ├── all
│  │  ├── master
│  │  ├── replica
│  │  └── test
│  └── test

postgresql_version added in inventory/test/group_vars/test but it is ignored.
I also tried adding this parameter to inventory/test/group_vars/{all, master, replica}, it is also ignored
Please tell me what I'm doing wrong

**Comment by vitabaks** [comment]
`inventory/group_vars/test` Instead of inventory/test/group_vars/test

**Comment by mrsrvman** [comment]
> Please tell me what I'm doing wrong

This is due to the forced import of variables.
Look here https://github.com/vitabaks/postgresql_cluster/blob/master/deploy_pgcluster.yml#L92

**Comment by P1ton** [comment]
> `inventory/group_vars/test`Вместо inventory/test/group_vars/test

That doesn't work either. I understand that vars_files has a higher priority than inventory
https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence

**Comment by P1ton** [comment]
Thank all for help.


> > Please tell me what I'm doing wrong
> 
> This is due to the forced import of variables. Look here https://github.com/vitabaks/postgresql_cluster/blob/master/deploy_pgcluster.yml#L92
> 
> I use something like this in playbooks
> 
> ```
>     - name: Include specific variables
>       include_vars:
>        dir: "{{ansible_inventory_sources[0]}}/group_vars/all"
>        depth: 0
>       tags: always
> ```

Thank all for help.
Used this option to variant only those variables that change
