### ISSUE TITLE
etcd error

### ISSUE THREAD

**Issue by nekulin** [vitabaks/postgresql_cluster#27]
Debian Buster (GNU/Linux 4.19.0-6-amd64 x86_64 ) 

TASK [etcd cluster | enable and start systemd service] *******************************************************************************************************
fatal: [ip1]: FAILED! => {"changed": false, "msg": "Unable to start service etcd: Job for etcd.service failed because a timeout was exceeded.\nSee \"systemctl status etcd.service\" and \"journalctl -xe\" for details.\n"}
fatal: [ip2]: FAILED! => {"changed": false, "msg": "Unable to start service etcd: Job for etcd.service failed because a timeout was exceeded.\nSee \"systemctl status etcd.service\" and \"journalctl -xe\" for details.\n"}
fatal: [ip3]: FAILED! => {"changed": false, "msg": "Unable to start service etcd: Job for etcd.service failed because a timeout was exceeded.\nSee \"systemctl status etcd.service\" and \"journalctl -xe\" for details.\n"}

Restart
ansible-playbook deploy_pgcluster.yml

TASK [etcd cluster | wait until the etcd cluster is healthy] *************************************************************************************************
fatal: [ip1]: FAILED! => {"attempts": 10, "changed": false, "cmd": ["/usr/local/bin/etcdctl", "cluster-health"], "delta": "0:00:02.014084", "end": "2020-02-03 19:11:56.270724", "msg": "non-zero return code", "rc": 4, "start": "2020-02-03 19:11:54.256640", "stderr": "Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:4001: connect: connection refused\n; error #1: client: endpoint http://127.0.0.1:2379 exceeded header timeout\n\nerror #0: dial tcp 127.0.0.1:4001: connect: connection refused\nerror #1: client: endpoint http://127.0.0.1:2379 exceeded header timeout", "stderr_lines": ["Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:4001: connect: connection refused", "; error #1: client: endpoint http://127.0.0.1:2379 exceeded header timeout", "", "error #0: dial tcp 127.0.0.1:4001: connect: connection refused", "error #1: client: endpoint http://127.0.0.1:2379 exceeded header timeout"], "stdout": "cluster may be unhealthy: failed to list members", "stdout_lines": ["cluster may be unhealthy: failed to list members"]}

Restart
ansible-playbook deploy_pgcluster.yml

**Comment by vitabaks** [comment]
Hi! @nekulin 

Could you attach the full etcd service log?

`sudo journalctl -u etcd.service | tail -n 500`

**Comment by nekulin** [comment]
fatal: []: FAILED! => {"changed": false, "msg": "Unable to start service etcd: Job for etcd.service failed because a timeout was exceeded. See \"systemctl status etcd.service\" and \"journalctl -xe\" for details.\n"}

Feb 04 08:49:35 pgnode02 etcd[3196]: health check for peer a716305f6f3d3445 could not connect: dial tcp ip1:2380: connect: connection refused (prober "ROUND_TRIPPER_SNAPSHOT")
Feb 04 08:49:35 pgnode02 etcd[3196]: health check for peer a716305f6f3d3445 could not connect: dial tcp ip1:2380: connect: connection refused (prober "ROUND_TRIPPER_RAFT_MESSAGE")
Feb 04 08:49:40 pgnode02 etcd[3196]: health check for peer 255710af74345fd could not connect: dial tcp ip2:2380: connect: connection refused (prober "ROUND_TRIPPER_SNAPSHOT")
Feb 04 08:49:40 pgnode02 etcd[3196]: health check for peer 255710af74345fd could not connect: dial tcp ip2:2380: connect: connection refused (prober "ROUND_TRIPPER_RAFT_MESSAGE")
Feb 04 08:49:40 pgnode02 etcd[3196]: health check for peer a716305f6f3d3445 could not connect: dial tcp ip1:2380: connect: connection refused (prober "ROUND_TRIPPER_SNAPSHOT")
Feb 04 08:49:40 pgnode02 etcd[3196]: health check for peer a716305f6f3d3445 could not connect: dial tcp ip1:2380: connect: connection refused (prober "ROUND_TRIPPER_RAFT_MESSAGE")
Feb 04 08:49:41 pgnode02 etcd[3196]: 2e1ca65e52abc005 is starting a new election at term 16
Feb 04 08:49:41 pgnode02 etcd[3196]: 2e1ca65e52abc005 became candidate at term 17
Feb 04 08:49:41 pgnode02 etcd[3196]: 2e1ca65e52abc005 received MsgVoteResp from 2e1ca65e52abc005 at term 17
Feb 04 08:49:41 pgnode02 etcd[3196]: 2e1ca65e52abc005 [logterm: 1, index: 3] sent MsgVote request to 255710af74345fd at term 17
Feb 04 08:49:41 pgnode02 etcd[3196]: 2e1ca65e52abc005 [logterm: 1, index: 3] sent MsgVote request to a716305f6f3d3445 at term 17
Feb 04 08:49:45 pgnode02 etcd[3196]: publish error: etcdserver: request timed out
Feb 04 08:49:45 pgnode02 etcd[3196]: health check for peer 255710af74345fd could not connect: dial tcp ip2:2380: connect: connection refused (prober "ROUND_TRIPPER_RAFT_MESSAGE")
Feb 04 08:49:45 pgnode02 etcd[3196]: health check for peer 255710af74345fd could not connect: dial tcp ip2:2380: connect: connection refused (prober "ROUND_TRIPPER_SNAPSHOT")
Feb 04 08:49:45 pgnode02 etcd[3196]: health check for peer a716305f6f3d3445 could not connect: dial tcp ip1:2380: connect: connection refused (prober "ROUND_TRIPPER_SNAPSHOT")
Feb 04 08:49:45 pgnode02 etcd[3196]: health check for peer a716305f6f3d3445 could not connect: dial tcp ip1:2380: connect: connection refused (prober "ROUND_TRIPPER_RAFT_MESSAGE")

**Comment by nekulin** [comment]
@vitabaks  Can you help ?

**Comment by vitabaks** [comment]
> could not connect: dial tcp ip1:2380: connect: connection refused

This is a network problem, the nodes are not accessible to each other on TCP port 2380.
And this is very strange, since this playbook opens the necessary ports in iptables.

Please show the result of the command:
`iptables --list`

Please tell me, are your servers (on which you deploy etcd) located on different subnets?
Is it possible that there is a firewall between them that blocks traffic on ports 2379 and 2380?

Try to telnet between these hosts:
`telnet ip_address 2380`

**Comment by nekulin** [comment]
On digitalocean earned, strange, thank you
