### ISSUE TITLE
Several pg clusters with one etcd cluster

### ISSUE THREAD

**Issue by a-b-v** [vitabaks/postgresql_cluster#283]
Hi!
I'm trying to make this setup, but then the patroni from the secondary cluster starting, the log messages appeared:

```
Mar 20 08:16:14 pg02-node01 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL - Patroni.
Mar 20 08:16:14 pg02-node01 patroni[12816]: 2023-03-20 08:16:14,681 INFO: Selected new etcd server http://172.16.16.14:2379
Mar 20 08:16:14 pg02-node01 patroni[12816]: 2023-03-20 08:16:14,690 INFO: No PostgreSQL configuration items changed, nothing to reload.
Mar 20 08:16:14 pg02-node01 patroni[12816]: 2023-03-20 08:16:14,703 INFO: Lock owner: pg01-node01; I am pg02-node01
Mar 20 08:16:14 pg02-node01 patroni[12816]: 2023-03-20 08:16:14,709 INFO: trying to bootstrap from leader 'pg01-node01'
```

How i can to make setup like this?

**Comment by vitabaks** [comment]
Hi @a-b-v 

I don't see any errors in the log, please attach more Patroni logs

`sudo journalctl -u patroni`

**Comment by a-b-v** [comment]
I Have read the patrony documentation. looks like he can't do that

**Comment by a-b-v** [comment]
> Hi @a-b-v
> 
> I don't see any errors in the log, please attach more Patroni logs
> 
> `sudo journalctl -u patroni`

Patroni from second cluster tried to restore postgresql data from first cluster instead of initizlise it own cluster

**Comment by a-b-v** [comment]
I guess I have to setup several etcd on different ports

**Comment by vitabaks** [comment]
> Several pg clusters with one etcd cluster

Now I understand what you need.

In this case, just specify a different `patroni_cluster_name` for the second cluster.

**Comment by vitabaks** [comment]
https://github.com/vitabaks/postgresql_cluster/commit/87992a6cec4dcf390d469b679eca9711db504510
