### ISSUE TITLE
Migration to Ansible Collection Format

### ISSUE THREAD

**Issue by ThomasSanson** [vitabaks/postgresql_cluster#284]
Currently, PostgreSQL High-Availability Cluster installation via Ansible is done using the "role" mode. However, the "collection" format is now the recommended deployment method for Ansible.

I am requesting a migration of PostgreSQL High-Availability Cluster to the Ansible collection format to improve ease of use and maintainability of the installation.

Thank you very much for your excellent work and your consideration of this request

**Comment by vitabaks** [comment]
Hi @ThomasSanson 

Please show an example of what you want to see? And what advantages will this give us?

**Comment by vitabaks** [comment]
similar discussion https://github.com/vitabaks/postgresql_cluster/discussions/272

**Comment by ThomasSanson** [comment]
I'm one step away from dealing with this issue 😇

**Comment by ThomasSanson** [comment]
Hi @vitabaks,

As I've been thinking about our transition to the Ansible collection format, a question occurred to me: should we wait until the two current pull requests are completed before we embark on this task?

The shift to the collection format will result in changing the location of the playbooks, which could likely lead to a fair amount of git conflicts. While these can be managed, I wanted to discuss the best strategy moving forward.

Here are the two options as I see them:

1. We dive into the transition to the collection format and handle the conflicts as they arise. 
2. We wait until the two pull requests are merged before beginning this transition.

I'm comfortable with either approach and can work on other tasks in the interim if needed, such as improving our linters.

I'd appreciate your thoughts on this. Which approach do you think we should take?

**Comment by vitabaks** [comment]
@ThomasSanson v1.8.0 has been [released](https://github.com/vitabaks/postgresql_cluster/releases/tag/1.8.0), we can move on! 😇

**Comment by jimnydev** [comment]
Is this still actual? I'm also willing to contribute, just wanted to check if there's some ongoing effort regarding this?

Thank you!

**Comment by vitabaks** [comment]
> Is this still actual? I'm also willing to contribute, just wanted to check if there's some ongoing effort regarding this?

I'm not sure if this functionality is necessary. Especially considering the fact that starting from version 2.0, the project has been significantly changed and now the UI is provided.
