### ISSUE TITLE
Task "vip-manager : Wait for the cluster ip address (VIP)" is failed when is used pgbouncer

### ISSUE THREAD

**Issue by FactorT** [vitabaks/postgresql_cluster#286]
This commit [update the vip-manager version (use API v3)](https://github.com/vitabaks/postgresql_cluster/commit/54a17c02b902bd70d8383036ae532e09add29689#diff-803b59701a61cafb1d4b03ab6bc9a7a2f6860f68f29fa222d8b4419ed59af469) changes checking from 22 port to 5432 port.
But if we check [patroni.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/roles/patroni/templates/patroni.yml.j2#L114) we see that 5432 port is accessible only when pgbouncer doesn't used.
If we set pgbouncer_install=true then port 5432 doen't accessible by vip address and task is failed.

Resolve1: return back checking from 5432 to 22 port for task "Wait for the cluster ip address (VIP) "{{ cluster_vip }}" is running"
Resolve2: listen 5432 port on vip address no matter of using pgbouncer - change [patroni.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/roles/patroni/templates/patroni.yml.j2#L114)

If you prefer I can create pull request for one of resolution.

**Comment by vitabaks** [comment]
Exactly you are right. Thanks!

it is necessary to return the "`{{ ansible_ssh_port | default(22) }}`"

**Comment by vitabaks** [comment]
fixed: https://github.com/vitabaks/postgresql_cluster/commit/e4a75244d75346be7c237747e285df5243693cc0
