### ISSUE TITLE
FATAL: role \"postgres\" does not exist"

### ISSUE THREAD

**Issue by gduval** [vitabaks/postgresql_cluster#29]
I am running into an error at the TASK [get postgresql database list]

Eror msg:

fatal: [10.16.13.14 -> 10.16.13.14]: FAILED! => {"changed": false, "cmd": ["/usr/lib/postgresql/11/bin/psql", "-p", "5432", "-c", "SELECT d.datname as Name, pg_catalog.pg_get_userbyid(d.datdba) as Owner, pg_catalog.pg_encoding_to_char(d.encoding) as Encoding, d.datcollate as Collate, d.datctype as Ctype, CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT') THEN pg_catalog.pg_size_pretty(pg_catalog.pg_database_size(d.datname)) ELSE 'No Access' END as Size, t.spcname as Tablespace FROM pg_catalog.pg_database d JOIN pg_catalog.pg_tablespace t on d.dattablespace = t.oid WHERE not datistemplate ORDER BY 1"], "delta": "0:00:00.009237", "end": "2020-02-11 13:20:24.826949", "msg": "non-zero return code", "rc": 2, "start": "2020-02-11 13:20:24.817712", "stderr": "psql: FATAL:  role \"postgres\" does not exist", "stderr_lines": ["psql: FATAL:  role \"postgres\" does not exist"], "stdout": "", "stdout_lines": []}
...ignoring

Any suggestions?

**Comment by vitabaks** [comment]
Hi @gduval 

> TASK [get postgresql database list]

This task is optional, it is only for information. The default setting is `ignore_errors: yes`.

_"psql: FATAL: role" postgres "does not exist"_
But this is already strange...

I fixed this task, now we explicitly specify **-U** postgres.
`{{postgresql_bin_dir}} / psql -p {{postgresql_port}} -U postgres -c \ "SELECT ...`

Clone this playbook again and verify by running with the tag:
`ansible-playbook deploy_pgcluster.yml --tags db_list`

**Comment by gduval** [comment]
Thanks for the reply.  I am not seeing anything different in the deploy_pgcluster.yml playbook.   Were you able to make the changes yet?

**Comment by vitabaks** [comment]
@gduval 
Changes have been made to tasks/[deploy_finish.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/tasks/deploy_finish.yml)

See commit ad5e21daa37b20b2b7dd414d793d40bb628ea176

**Comment by vitabaks** [comment]
I would also like to get a little more information about your postgres instance.

Have you manually make [initdb](https://www.postgresql.org/docs/11/app-initdb.html) for your database?
Is there a postgres user in the role list?
`\du`

This playbook support the deployment of cluster over already existing and running PostgreSQL. You must specify the variable `postgresql_exists='true'` in the inventory file.

**Comment by vitabaks** [comment]
@gduval how are you?
