### ISSUE TITLE
vip-manager: cluster ip confusion (AWS)

### ISSUE THREAD

**Issue by prensgold** [vitabaks/postgresql_cluster#292]
Hi Vitaliy ,

When I ran your scripts on the servers in my local, I could only see the cluster ip on one server.

In the screenshot below, the cluster ip output from the servers I set up in my own locale.

<img width="295" alt="image" src="https://user-images.githubusercontent.com/118886124/228541393-56ed9f43-67be-4ec3-a269-ce21884e2bd6.png">

When I want to install and test your current script on amazon, I can see the cluster ip on all 3 servers.
and when I tried to connect to the database with port 5000 from each server, I was able to connect.

In the screenshot below, the cluster ip output from the servers I set up on amazon.

<img width="296" alt="image" src="https://user-images.githubusercontent.com/118886124/228543019-c8b680d7-1264-4424-ab4c-1dd2c1de4f02.png">

Cluster ip status confused me in two installations.
What is the correct output here? The operating systems are in the same version.
How can we interpret this situation?

**Comment by vitabaks** [comment]
Hi @prensgold 

Thanks!

I'm not sure, but maybe it's a bug in the vip-manager version 2.1.0

Have you deployed a cluster from scratch using etcd version 3.5.7 or do you have a different version?

Can you attach logs from all servers?

`sudo journalctl -u vip-manager`

**Comment by vitabaks** [comment]
an issue was created on the vip-manager project repository

https://github.com/cybertec-postgresql/vip-manager/issues/147

**Comment by vitabaks** [comment]
> AWS doesn't support sending of gratuitous ARP messages (none of the public hosters do, as you could try to impersonate another server easily), so vip-manager would not work with AWS.

https://github.com/cybertec-postgresql/vip-manager/issues/147#issuecomment-1702723720

**Comment by vitabaks** [comment]
Recommendations for cloud environments:
- For the "Type A" scheme: Use DNS records (round-robin) listing all HAProxy load balancing servers instead of relying on cluster_vip.
- For the "Type B" scheme: Use `libpq` [target_session_attrs](https://www.cybertec-postgresql.com/en/new-target_session_attrs-settings-for-high-availability-and-scaling-in-postgresql-v14/), ensuring read/write connections go to the primary database, as an alternative to cluster_vip.
