### ISSUE TITLE
trust в pg_hba

### ISSUE THREAD

**Issue by kkrasnov1** [vitabaks/postgresql_cluster#293]
Подскажите, пожалуйста, зачем в pg_hba используется trust для {{ patroni_superuser_username }}

```
postgresql_pg_hba:
  - { type: "local", database: "all", user: "{{ patroni_superuser_username }}", address: "", method: "trust" }
```

**Comment by kkrasnov1** [comment]
По умолчанию получается что любой локальный пользователь Linux может зайти под учетной записью postgres без аутентификации?

**Comment by vitabaks** [comment]
> По умолчанию получается что любой локальный пользователь Linux может зайти под учетной записью postgres без аутентификации? 
> 

Да. Если пользователь локально подключен к серверу то он получит доступ к базе, даже если там не trust. 
Обычно к серверу кто попало доступ не имеет.

**Comment by kkrasnov1** [comment]
Спасибо!
