### ISSUE TITLE
The task "Wait until the etcd cluster is healthy" is not executed in check mode

### ISSUE THREAD

**Issue by bomuva** [vitabaks/postgresql_cluster#295]
When running deploy_pgcluster.yml in check mode on previously successfully created cluster the task "Wait until the etcd cluster is healthy" not execute (due to limitation of the "command" module in the check_mode (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html#attribute-check_mode)

FAILED - RETRYING: [192.168.1.100]: Wait until the etcd cluster is healthy (10 retries left).
FAILED - RETRYING: [192.168.1.102]: Wait until the etcd cluster is healthy (10 retries left).
FAILED - RETRYING: [192.168.1.104]: Wait until the etcd cluster is healthy (10 retries left).
FAILED - RETRYING: [192.168.1.101]: Wait until the etcd cluster is healthy (10 retries left).
...

It is necessary add "check_mode: false"  attribute to the "command" module to force execution regardless check mode because it is safe

**Comment by vitabaks** [comment]
Hello! 
feel free to create PR.

**Comment by vitabaks** [comment]
https://github.com/vitabaks/postgresql_cluster/blob/master/CONTRIBUTING.md

**Comment by vitabaks** [comment]
PR: https://github.com/vitabaks/postgresql_cluster/pull/459
