### ISSUE TITLE
Issue with ansible-role-firewall on Ubuntu 18.04

### ISSUE THREAD

**Issue by s4vicky** [vitabaks/postgresql_cluster#3]
Thank you so much for the ansible playbooks...gives a good starting point on the steps to get HA setup with postgresql. I am trying to run this playbook on Ubuntu 18.04 (64 bit) and while running the playbook on my virtual box local network... i get the below issue onn the firewall role.. can you please help on this.

TASK [ansible-role-firewall : Load the nf_conntrack_ipv4 module] ***********************************************************************************
fatal: [192.168.1.134]: FAILED! => {"changed": false, "msg": "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'\nmodprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/4.18.0-15-generic\n", "name": "nf_conntrack_ipv4", "params": "", "rc": 1, "state": "present", "stderr": "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'\nmodprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/4.18.0-15-generic\n", "stderr_lines": ["modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'", "modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/4.18.0-15-generic"], "stdout": "", "stdout_lines": []}
...ignoring
fatal: [192.168.1.136]: FAILED! => {"changed": false, "msg": "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'\nmodprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/4.18.0-15-generic\n", "name": "nf_conntrack_ipv4", "params": "", "rc": 1, "state": "present", "stderr": "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'\nmodprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/4.18.0-15-generic\n", "stderr_lines": ["modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'", "modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/4.18.0-15-generic"], "stdout": "", "stdout_lines": []}
...ignoring
changed: [192.168.1.135]

TASK [ansible-role-firewall : Configure the kernel to keep connections alive when enabling the firewall] *******************************************
fatal: [192.168.1.134]: FAILED! => {"changed": false, "msg": "Failed to reload sysctl: sysctl: cannot stat /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal: No such file or directory\n"}
...ignoring
changed: [192.168.1.135]
fatal: [192.168.1.136]: FAILED! => {"changed": false, "msg": "Failed to reload sysctl: sysctl: cannot stat /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal: No such file or directory\n"}
...ignoring

TASK [ansible-role-firewall : Configure the firewall service.] *************************************************************************************
fatal: [192.168.1.134]: FAILED! => {"changed": false, "msg": "Unable to start service firewall: Job for firewall.service failed because the control process exited with error code.\nSee \"systemctl status firewall.service\" and \"journalctl -xe\" for details.\n"}
fatal: [192.168.1.136]: FAILED! => {"changed": false, "msg": "Unable to start service firewall: Job for firewall.service failed because the control process exited with error code.\nSee \"systemctl status firewall.service\" and \"journalctl -xe\" for details.\n"}
changed: [192.168.1.135]

As a result the firewall service fails to start and the ansible exits ... any pointers would be helpful

**Comment by vitabaks** [comment]
Hello! @s4vicky 

I tested on Ubuntu 18.04.2 with the kernel version 4.15. And I had no errors.
It looks like you are using the kernel version 4.18. And I should additionally check the playbook on this version of the kernel.

Please send logs
`sudo journalctl -u firewall.service | tail -n 100`

**Comment by vitabaks** [comment]
I upgraded to Ubuntu 18.04.3 and installed the kernel version 4.18.15 
and there are no errors.

I am waiting for your logs.

**Comment by s4vicky** [comment]
thank you so much for your response... below are the requested details...

$ uname -a
Linux pgnode02 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Below is the output of sudo journalctl -u firewall.service | tail -n 100

Aug 31 08:29:12 pgnode03 firewall.bash[20037]: iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps iptables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps iptables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: iptables: No chain/target/match by that name.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: iptables: No chain/target/match by that name.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps iptables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps iptables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: iptables: No chain/target/match by that name.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-15-generic/modules.dep.bin'
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.18.0-15-generic
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Aug 31 08:29:12 pgnode03 firewall.bash[20037]: Perhaps ip6tables or your kernel needs to be upgraded.
Aug 31 08:29:12 pgnode03 systemd[1]: firewall.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Aug 31 08:29:12 pgnode03 systemd[1]: firewall.service: Failed with result 'exit-code'.
Aug 31 08:29:12 pgnode03 systemd[1]: Failed to start Firewall.

**Comment by s4vicky** [comment]
please ignore this issue... am closing it for now... i killed all my instances and again created the instances in virtualbox with the same OS version and now it worked... 

TASK [ansible-role-firewall : Load the nf_conntrack_ipv4 module] ***********************************************************************************
changed: [192.168.1.138]
changed: [192.168.1.139]
changed: [192.168.1.140]

**Comment by vitabaks** [comment]
Good.

I am glad that you were able to solve the problem.
