### ISSUE TITLE
kerberos аутентификация postgresql 

### ISSUE THREAD

**Issue by erzhick10** [vitabaks/postgresql_cluster#302]
Здравствуйте ! есть ли возможность настройки с протоколом kerberos аутентификацию и  inventory использовать свой  ?

**Comment by vitabaks** [comment]
По kerberos, не включена такая возможность в автоматизации. Но Вы можете сделать это.

Инвентори может быть свой, но должен содержать группы как в текущем inventory файле.

**Comment by erzhick10** [comment]
по kerberos просто так же в роли шаблоны добавит просто его подскажите где могу это сделать чтоб с ansible  раскатать установку ? или после установки можно добавить настройки отдельно?

**Comment by vitabaks** [comment]
Да, Вы можете сделать необходимые для Вас настройки самостоятельно.

**Comment by vitabaks** [comment]
c kerberos аутентификацией для Postgres пока не имел дело.
Мне также как и Вам необходимо выделить время для того чтобы найти решение по Вашему вопросу.

Поэтому, буду благодарен, если Вы опишите инструкцию, если разберетесь в этом вопросе самостоятельно.

**Comment by erzhick10** [comment]
хорошо если получится я вам подскажу как я это реализовал !
