### ISSUE TITLE
Enable GitHub Sponsors for you

### ISSUE THREAD

**Issue by ThomasSanson** [vitabaks/postgresql_cluster#303]
Hello @vitabaks,

First of all, I want to thank you for your excellent work on this project. I've noticed that you have set up a Patreon page for sponsorships. However, I was wondering if you would consider enabling GitHub Sponsors for you as well.

GitHub Sponsors is a convenient way for the community to support your work directly on the GitHub platform. It might help increase the number of sponsors, as some users may prefer to use GitHub over Patreon.

Here is the link to the GitHub Sponsors program for more information: https://github.com/sponsors

Please let me know if you are open to this suggestion, and if you need any help setting it up.

Thank you for your time and consideration.

Best regards,

**Comment by vitabaks** [comment]
Hello @ThomasSanson !

Thank you so much for reminding me about this sponsorship method, I had plans to set it up. I will try to do it soon.

Sponsorship is really very important for the development of this project. If I manage to find enough sponsors, I will be able to devote more time to this project.

**Comment by vitabaks** [comment]
Done.
Now everyone who wants to support my project through Github has such an opportunity.

https://github.com/sponsors/vitabaks

**Comment by ThomasSanson** [comment]
Well done! I made a small personal contribution to the sponsorship, it's not much but it's a good start.

We can close this issue now, as I have added it to the documentation.

**Comment by vitabaks** [comment]
Thanks @ThomasSanson !
