### ISSUE TITLE
Add a CONTRIBUTING.md file to guide new contributors

### ISSUE THREAD

**Issue by ThomasSanson** [vitabaks/postgresql_cluster#304]
Hello @vitabaks,

Firstly, I want to express my appreciation for your amazing work on this project. As the project grows and attracts more contributors, I think it would be helpful to add a CONTRIBUTING.md file to the repository. This file would guide new contributors on how to effectively participate in the project.

Having a CONTRIBUTING.md file can streamline the process for potential contributors and ensure that they have a clear understanding of the steps to follow when submitting issues, making pull requests, and more.

I have already drafted a CONTRIBUTING.md file and will create a pull request for your review. Please let me know if you have any suggestions or changes before I proceed.

Thank you for your time and consideration.

Best regards,

**Comment by vitabaks** [comment]
Thanks @ThomasSanson

**Comment by vitabaks** [comment]
I left a few comments in your PR
