### ISSUE TITLE
Integrate code improvements and add linters

### ISSUE THREAD

**Issue by ThomasSanson** [vitabaks/postgresql_cluster#306]
I have identified several potential improvements in the code and would like to integrate them. These improvements are described below:

1. Add bash-completion package and sort packages
- Add the bash-completion package to the .gitpod.Dockerfile file to enable tab completion in the terminal.
- Sort the packages in the .gitpod.Dockerfile file.

2. Clean up and fix indentation in the molecule.yml file
- Fix indentation issues to improve the readability of the molecule.yml file.

3. Add linters for YAML, Ansible, and Python files
- Update the .yamllint file to ignore the .venv directory and enforce a minimum of one space between comments and content.
- Update the .ansible-lint file to exclude the .venv directory.
- Update the Makefile to include the new linters.mak file, which contains the targets for the linters.
- Run the linters in the `lint` target.

To resolve this issue, I will submit a Pull Request with the above changes.

**Comment by vitabaks** [comment]
Thanks @ThomasSanson

**Comment by vitabaks** [comment]
@ThomasSanson Also note the large list of `skip_list` in the .`ansible-lint` file

I would appreciate it if you could help me refactor the code so that it meets most of the linters' recommendations. 
Of course, not all recommendations should be strictly followed, but some of them still deserve our attention.

**Comment by ThomasSanson** [comment]
@vitabaks You're welcome, happy to help!

Sure, I'd be happy to help you refactor your code to meet the recommendations of the linters.
