### ISSUE TITLE
Error adding Percona repository

### ISSUE THREAD

**Issue by Dasiho2000** [vitabaks/postgresql_cluster#310]
Hi,

   Reading the previous issues, i've tried to add the Percona repository in vars/RedHat.yml like this:
# Repository
yum_repository:
- name: "Percona Original release/x86_64 YUM repository"
description: "repo percona"
baseurl: "http://repo.percona.com/percona/yum/release/latest/RPMS/x86_64"
gpgkey: "https://repo.percona.com/percona/yum/RPM-GPG-KEY-Percona"
gpgcheck: "no"

But after the etcd installation, I receive this error:

TASK [add-repository : Add repository] *********************************************************************************************************************************************
fatal: [192.168.10.138]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'description'\n\nThe error appears to be in '/opt/postgresql_cluster/roles/add-repository/tasks/main.yml': line 23, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:  # RedHat/CentOS\n    - name: Add repository\n      ^ here\n"}
fatal: [192.168.10.140]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'description'\n\nThe error appears to be in '/opt/postgresql_cluster/roles/add-repository/tasks/main.yml': line 23, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:  # RedHat/CentOS\n    - name: Add repository\n      ^ here\n"}
fatal: [192.168.10.141]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'description'\n\nThe error appears to be in '/opt/postgresql_cluster/roles/add-repository/tasks/main.yml': line 23, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:  # RedHat/CentOS\n    - name: Add repository\n      ^ here\n"}

Could you help me?

**Comment by vitabaks** [comment]
@Dasiho2000 I see you have closed the issue. Did you manage to fix the problem?
