### ISSUE TITLE
keepalive issue

### ISSUE THREAD

**Issue by EvgenyLyndin** [vitabaks/postgresql_cluster#317]
Добрый день, Виталий!
Правильно ли я понимаю, что для установки значения cluster_vip: "" можно указать любой несуществующий IP в сети?
Дело в том, что при деплое с haproxy коннекты на каждую ноду проходят, а если указать IP в  cluster_vip, то установка проходит успешно, но коннекта к нему не происходит. Сеть VPC в облаке yandex.cloud.

**Comment by vitabaks** [comment]
Да это должен быть свободный ip адрес в Вашей сети.
Уточните эти детали у Вашего облачного провайдера.
Есть ли возможность использовать плавающий IP адрес который переезжает на другой сервер в кластере с переключениеи роли базы данных leader.
