### ISSUE TITLE
Использование с уже сконфигурированым Consul кластером

### ISSUE THREAD

**Issue by gutleib** [vitabaks/postgresql_cluster#328]
Привет.

Этот случай никак не описан в документации. Поддерживается ли он? Bootstrap servers в vars говорят об этом, но куда вписывать token?

**Comment by vitabaks** [comment]
Укажите адреса сущесвтующего кластера в переменной [consul_join](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/main.yml#L95) 
а для серверов баз данных укажите `consul_node_role=client` в variables 

Больше деталей по consul описано здесь https://github.com/vitabaks/postgresql_cluster/tree/master/roles/consul
