### ISSUE TITLE
Include role in requirements.yml file

### ISSUE THREAD

**Issue by ThomasSanson** [vitabaks/postgresql_cluster#329]
Hi there,

I was reviewing the ansible-role-yedit repository and noticed that the role is not included in the requirements.yml file.
https://github.com/kwoodson/ansible-role-yedit

I suggest that the role be included in the requirements.yml file so that users can easily install it.
This would also make it easier for contributors to submit pull requests to the repository.

Please let me know what you think. Thank you !

**Comment by ThomasSanson** [comment]
see https://github.com/vitabaks/postgresql_cluster/pull/315#issuecomment-1538180078

**Comment by vitabaks** [comment]
in fact, this is not a role, but a library for managing the yaml configuration, which you can observe here https://github.com/vitabaks/postgresql_cluster/tree/master/roles/patroni/library

I don't think it should be defined in requirements.yml

**Comment by vitabaks** [comment]
I'm avoiding the role definition approach in requirements.yml

instead, I copied them in advance to the main project repository to simplify the cluster installation 

here are the external roles that have been copied (and adapted) to this project:

- https://github.com/vitabaks/postgresql_cluster/tree/master/roles/ansible-role-firewall
- https://github.com/vitabaks/postgresql_cluster/tree/master/roles/consul


That is, these are roles that I did not develop from scratch automatically, but simply copied and adapted to my project. So they may differ slightly from the original versions and cannot simply be defined in requirements.yml

**Comment by ThomasSanson** [comment]
Thank you for the detailed explanation.
With this understanding, I am now closing this issue.
