### ISSUE TITLE
How to create correctly new users?

### ISSUE THREAD

**Issue by mobius77** [vitabaks/postgresql_cluster#332]
I use pgAdmin and create users in it but this users can't login.

When I use md5 got error: password authentification dailed
When I use scram-sha-256 got error: sasl authentication failed

What I did wrong?

**Comment by vitabaks** [comment]
### Adding a user to the database or changing the user's password
1. add the user to postgres or change the user's password
2. run the reconfiguration of pgbouncer_generate_userlist

```
ansible-playbook config_pgcluster.yml --tags "pgbouncer_generate_userlist"
```

md5 passwords will be pulled up from Postgres

### Removing the user from the database
1. Delete the user in postgresql
2. run the reconfiguration of pgbouncer_generate_userlist (optional)

```
ansible-playbook config_pgcluster.yml --tags "pgbouncer_generate_userlist"
```
