### ISSUE TITLE
Question about scaling

### ISSUE THREAD

**Issue by sojjan1337** [vitabaks/postgresql_cluster#333]
Hi!
 
Is it possible to run your project from start with only two instances? instead of three. Is there a option for that? 
And also to add one extra node if needed later. Or do you need to add one manually?

Big thanks!

**Comment by vitabaks** [comment]
Hi @sojjan1337 

> Is it possible to run your project from start with only two instances? instead of three. Is there an option for that?

Yes, you can create a database cluster from two nodes.

The only requirement is the presence of at least three servers for the etcd/consul cluster, to ensure consensus, details http://thesecretlivesofdata.com/raft/

I recommend deploying one etc (or consul) cluster to 3 or 5 small servers and using it for multiple Postgresql (Patroni) clusters.

**Comment by vitabaks** [comment]
> And also to add one extra node if needed later. Or do you need to add one manually?

Cluster scaling is also automated, use the add_pgnode.yml playbook for this. Details https://github.com/vitabaks/postgresql_cluster#cluster-scaling
