### ISSUE TITLE
Question Regarding Multi-Master PostgreSQL Support

### ISSUE THREAD

**Issue by ThomasSanson** [vitabaks/postgresql_cluster#337]
Hello,

Does this playbook support a multi-master PostgreSQL configuration ?
https://wiki.postgresql.org/wiki/Main_Page

If yes, can you point me to the appropriate documentation or configuration?

Thanks,

**Comment by vitabaks** [comment]
No.

**Comment by ThomasSanson** [comment]
@vitabaks 

Hmm, alright.

Are you generally opposed to using multi-master PostgreSQL, or is it simply not planned for at the moment?

I'm interested in hearing your perspective 😇

**Comment by vitabaks** [comment]
This project provides Patron + Postgres [+ TimescaleDB] and there is no multi-master support here.

You may be interested in the Citus extension. It is planned to add it to the project - https://github.com/vitabaks/postgresql_cluster/issues/258

**Comment by ThomasSanson** [comment]
Okay, thank you. I close this issue then
