### ISSUE TITLE
Ports, Type A

### ISSUE THREAD

**Issue by zuhataslan** [vitabaks/postgresql_cluster#356]
Hi!

I'll run a application on network A and db cluster (type A) on network B and have a firewall between. Which of the ports listed [here](https://github.com/vitabaks/postgresql_cluster#port-requirements) need to be open on the firewall. I'm guessing that most of the ports are needed only on the internal network for the cluster.

Edit:
Is defaultl port 5432 enough for Type B mode?

**Comment by vitabaks** [comment]
Hello @zuhataslan 

For client access from application network (A) to the database network (B), it is enough to open ports: 

#### Type A

- 5000 (haproxy - (read/write) master)

Optional:
- 5001 (haproxy - (read only) all replicas)
- 5002 (haproxy - (read only) synchronous replica only)
- 5003 (haproxy - (read only) asynchronous replicas only)


#### Type B

- 6432 (pgbouncer)

Or (if pgbouncer_install: false)

- 5432 (postgresql)

**Comment by zuhataslan** [comment]
Hi @vitabaks,
Thanks for your response.
Regarding **Type A**
In your answer, The read only ports are listed as optional, yet in README, it's says: 
> :heavy_exclamation_mark: Your application must have support sending read requests to a custom port (ex 5001), and write requests (ex 5000).

My application takes only one port for the db so I though **Type A** do require using at least one read and one write port, or doesn't it?

**Comment by vitabaks** [comment]
If your application does not support a read-only connection to the database on another port and if you do not have the task of balancing the read load, then you do not need scheme A, scheme B is sufficient, which assumes only a connection to one server - primary.
