### ISSUE TITLE
Вопрос по логике работы роли для Patroni

### ISSUE THREAD

**Issue by kkrasnov1** [vitabaks/postgresql_cluster#360]
Виталий, добрый день!

Если я не ошибся, у Вас в roles/patroni/tasks/main.yml в блоке "when postgresql exists" -> "for master only" выполняется остановка PostgreSQL каждый раз при прокатке плейбука (в строке https://github.com/vitabaks/postgresql_cluster/blob/master/roles/patroni/tasks/main.yml#L593).

Подскажите зачем это происходит.

**Comment by vitabaks** [comment]
Это необходимо для выполнения плейбука [deploy_pgcluster.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/deploy_pgcluster.yml) который должен выполняться только 1 раз, при развертывании кластера.

Остановка postgres необходима для конвертами обычного Postgres в кластер под управлением patroni, если мы говорим о postgresql_exists='true'

Эта логика осталась еще с самой первой реализации, тут нет проверки на предмет является ли этот Postgres уже частью текущего кластера (можно доработать).

В дальнейшем, когда кластер уже развернут, используется плейбук [config_pgcluster.yml](https://github.com/vitabaks/postgresql_cluster/blob/master/config_pgcluster.yml) для изминения конфигураций кластера.

**Comment by kkrasnov1** [comment]
Спасибо!
