### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by emanfeah** [vitabaks/postgresql_cluster#364]

**Comment by vitabaks** [comment]
Hi @emanfeah 

The log you provided shows that the Patroni service has encountered problems connecting to your etcd nodes at addresses 10.0.30.53 , 10.0.30.8, and 10.0.30.223 (port 2379).

To solve this problem, I recommend starting by checking the availability and health of etcd nodes. Then make sure there are no connection problems between the nodes.

from db node:

```
ping 10.0.30.53
ping 10.0.30.8
ping 10.0.30.223
```

```
telnet 10.0.30.53 2379
telnet 10.0.30.8 2379
telnet 10.0.30.223 2379
```

on etcd node
```
etcdctl version
etcdctl member list
etcdctl endpoint health --cluster

sudo journalctl -u etcd -n 1000
```

**Comment by emanfeah** [comment]
Thanks for your reply but the connection between them its good  :

` ping 10.0.30.223
PING 10.0.30.223 (10.0.30.223) 56(84) bytes of data.
64 bytes from 10.0.30.223: icmp_seq=1 ttl=64 time=0.015 ms


ping 10.0.30.8
PING 10.0.30.8 (10.0.30.8) 56(84) bytes of data.
64 bytes from 10.0.30.8: icmp_seq=1 ttl=64 time=0.187 ms

ping 10.0.30.53
PING 10.0.30.53 (10.0.30.53) 56(84) bytes of data.
64 bytes from 10.0.30.53: icmp_seq=1 ttl=64 time=0.230 ms
`
but the error show here 
`telnet 10.0.30.53 2379
Trying 10.0.30.53...
telnet: Unable to connect to remote host: Connection refused`


on etcd node : 

`etcdctl version
etcdctl version: 3.5.7
API version: 3.5  

etcdctl endpoint health --cluster
{"level":"warn","ts":"2023-06-07T06:59:47.293Z","logger":"etcd-client","caller":"v3@v3.5.7/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002de700/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}



`

**Comment by emanfeah** [comment]
hello , thank you for your reply but the connection between them it's good !

here a result : 

```
ping 10.0.30.53
PING 10.0.30.53 (10.0.30.53) 56(84) bytes of data.
64 bytes from 10.0.30.53: icmp_seq=1 ttl=64 time=0.017 ms

ping 10.0.30.223
PING 10.0.30.223 (10.0.30.223) 56(84) bytes of data.
64 bytes from 10.0.30.223: icmp_seq=1 ttl=64 time=0.209 ms

 ping 10.0.30.8
PING 10.0.30.8 (10.0.30.8) 56(84) bytes of data.
64 bytes from 10.0.30.8: icmp_seq=1 ttl=64 time=0.185 ms
```

also a telnet : 
```

 telnet 10.0.30.53 2379
Trying 10.0.30.53...
Connected to 10.0.30.53.
Escape character is '^]'.

Connection closed by foreign host.



telnet 10.0.30.223 2379
Trying 10.0.30.223...
Connected to 10.0.30.223.
Escape character is '^]'.
^C
Connection closed by foreign host.

telnet 10.0.30.8 2379
Trying 10.0.30.8...
Connected to 10.0.30.8.
Escape character is '^]'.

Connection closed by foreign host.
```

on etcd node : 




```
etcdctl version: 3.5.7
API version: 3.5
f08454fc1c45433, started, test02, http://10.0.30.223:2380, http://10.0.30.223:2379, false
3ce5bf2916d518f9, started, test01, http://10.0.30.53:2380, http://10.0.30.53:2379, false
6c120fe219426ddb, started, test03, http://10.0.30.8:2380, http://10.0.30.8:2379, false
http://10.0.30.223:2379 is healthy: successfully committed proposal: took = 2.525429ms
http://10.0.30.53:2379 is healthy: successfully committed proposal: took = 2.19588ms
http://10.0.30.8:2379 is healthy: successfully committed proposal: took = 2.442903ms
Jun 06 08:40:45 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:40:45.132Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:40:46 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:46.112Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:46 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:46.112Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:46 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:46.112Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:46 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:46.112Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:46 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:46.113Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:50 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:40:50.133Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:40:50 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:40:50.133Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:40:50 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:40:50.133Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:40:50 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:40:50.133Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:40:51 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:51.113Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:51 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:51.113Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:51 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:51.113Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:51 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:51.113Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:51 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:51.113Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:55 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:40:55.122Z","caller":"etcdserver/server.go:2083","msg":"faile>Jun 06 08:40:55 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:40:55.134Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:40:55 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:40:55.134Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:40:55 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:40:55.134Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:40:55 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:40:55.134Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:40:56 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:56.113Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:56 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:56.113Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:56 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:56.113Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:56 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:56.113Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:40:56 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:40:56.113Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:41:00 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:41:00.135Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:41:00 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:41:00.136Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:41:00 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:41:00.136Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:41:00 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:41:00.136Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:41:01 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:41:01.112Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:41:01 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:41:01.112Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:41:01 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:41:01.112Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:41:01 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:41:01.112Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:41:01 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:41:01.112Z","logger":"raft","caller":"etcdserver/zap_raft.go:>Jun 06 08:41:05 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:41:05.136Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:41:05 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:41:05.136Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:41:05 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:41:05.136Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:41:05 test01 bash[160083]: {"level":"warn","ts":"2023-06-06T08:41:05.136Z","caller":"rafthttp/probing_status.go:68","msg":"p>Jun 06 08:41:06 test01 bash[160083]: {"level":"info","ts":"2023-06-06T08:41:06.113Z","logger":"raft","caller":"etcdserver/zap_raft.go:
```

**Comment by vitabaks** [comment]
it looks like the etcd cluster is healthy.

Are you using the latest version of the playbook from the master branch? 

> etcdctl version: 3.5.7
API version: 3.5

Since we [switched](https://github.com/vitabaks/postgresql_cluster/pull/274) to using the API v3 and in your logs I see that Patroni is trying to use the etcd API v2

> Failed to get list of machines from http://10.0.30.223:2379/v2

Please show the configuration file `/etc/patroni/patroni.yml`

the `etcd3` section should be declared there, not `etcd`

https://github.com/vitabaks/postgresql_cluster/blob/master/roles/patroni/templates/patroni.yml.j2#L33

**Comment by emanfeah** [comment]
i don't know .. i use the master branch -- etcd3 

but maybe a postgresql .. ?


`ubuntu@test02:~$ psql
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?`


and the here  

```
root@test01:/home/ubuntu/postgresql_cluster# pg_lsclusters
Ver Cluster Port Status Owner    Data directory                       Log file
14  patroni 5432 down   postgres /data1/var/lib/postgresql/14/patroni /var/log/postgresql/postgresql-14-patroni.log
```

**Comment by vitabaks** [comment]
PostgreSQL is not running because Patroni is not running due to etcd connection problems.

>  i use the master branch -- etcd3

An interesting situation, I don't have any ideas yet on how to reproduce it.

Please send the archive of your playbook, I'll take a look at it.

**Comment by vitabaks** [comment]
@emanfeah I have not been able to reproduce the problem using your variable files (from mail).

```

TASK [patroni : Prepare PostgreSQL | make sure the postgresql log directory "/data1/var/log/postgresql" exists] ***
changed: [10.172.0.21]
changed: [10.172.0.20]
changed: [10.172.0.22]

TASK [patroni : Prepare PostgreSQL | make sure PostgreSQL data directory "/data1/var/lib/postgresql/14/patroni" exists] ***
changed: [10.172.0.22]
changed: [10.172.0.21]
changed: [10.172.0.20]

TASK [patroni : Prepare PostgreSQL | check that data directory "/data1/var/lib/postgresql/14/patroni" is not initialized] ***
ok: [10.172.0.21]
ok: [10.172.0.20]
ok: [10.172.0.22]

TASK [patroni : Prepare PostgreSQL | make sure the postgresql config files exists] ***
ok: [10.172.0.20]
ok: [10.172.0.21]
ok: [10.172.0.22]
```

**Comment by emanfeah** [comment]
so the problem in a ports ..?

**Comment by vitabaks** [comment]
I don't think so, since my tests passed successfully.  There is another problem in your case in the interaction of Patroni with the etcd cluster, which I may not be aware of.

Apparently your environment is somewhat different from what I used for testing.  Try to deploy the cluster without changing any variables other than addresses in inventory.

**Comment by emanfeah** [comment]
do you think the problem its in 

```
 pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication replicator 127.0.0.1/32 md5
    - host all all 0.0.0.0/0 md5
```

???? i think it must be a master host ..

**Comment by vitabaks** [comment]
These are the default values for initdb and we redefine them further.

You can check the contents of the pg_hba.conf file after deployment


https://github.com/vitabaks/postgresql_cluster/blob/master/roles/patroni/tasks/main.yml#L530
https://github.com/vitabaks/postgresql_cluster/blob/master/roles/patroni/templates/pg_hba.conf.j2

**Comment by vitabaks** [comment]
> Try to deploy the cluster without changing any variables other than addresses in inventory.

Let me know if you managed to deploy the cluster with the default values.

**Comment by emanfeah** [comment]
Unfortunately, the same problem 
`TASK [patroni : Wait for port 8008 to become open on the host] ************************************************************************ok: [10.0.30.53]
FAILED - RETRYING: Check PostgreSQL is started and accepting connections on Master (1000 retries left).
FAILED - RETRYING: Check PostgreSQL is started and accepting connections on Master (999 retries left).FAILED - RETRYING: Check PostgreSQL is started and accepting connections on Master (998 retries left).`

**Comment by vitabaks** [comment]
well,
now the problem is at an earlier stage - the etcd cluster does not start  

please attach logs from all servers
`sudo journalctl -u etcd`

**Comment by emanfeah** [comment]
its work thank you

**Comment by vitabaks** [comment]
> its work thank you

Ok.

Can you provide more details about your deployment? I would really like to find a way to reproduce your problem.
