### ISSUE TITLE
roles/consul/requirements.yml misses `netaddr` package

### ISSUE THREAD

**Issue by olwe0002** [vitabaks/postgresql_cluster#380]
to install a cluster type C with consul, you advice to install further [requirements](https://github.com/vitabaks/postgresql_cluster/blob/f826ca13a3bf401b828df4099ed52bc9d25b197d/README.md?plain=1#L173) for consul.

this results in the following error:

```
TASK [consul : Create configuration] *******************************************
fatal: [10.0.0.22]: FAILED! => {}
MSG:
An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: The ipwrap filter requires python's netaddr be installed on the ansible controller. The ipwrap filter requires python's netaddr be installed on the ansible controller
```

**Comment by vitabaks** [comment]
@olwe0002 

Please check whether the `netaddr` package is installed on your server (where you run ansible)

```bash
pip list | grep netaddr
```

**Comment by olwe0002** [comment]
its missing of course. shouldn't it be contained in `roles/consul/requirements.yml` if it is needed for this role? that's my point here.

**Comment by vitabaks** [comment]
Fixed here https://github.com/vitabaks/postgresql_cluster/pull/442
