### ISSUE TITLE
Patroni health check endpoint `/master` is undocumented / deprecated

### ISSUE THREAD

**Issue by olwe0002** [vitabaks/postgresql_cluster#381]
haproxy currently [uses](https://github.com/vitabaks/postgresql_cluster/blob/f826ca13a3bf401b828df4099ed52bc9d25b197d/roles/haproxy/templates/haproxy.cfg.j2#L36) patroni endpoint `/master` to determine which node is the read-write endpoint to balance to.

in the current [docs](https://patroni.readthedocs.io/en/latest/rest_api.html#health-check-endpoints) of patroni I can't find this endpoint, I guess it was replaced by `read-write` or `primary` (NOT by `leader`, as this is also responding on `standby_leader` nodes) and should be updated?

**Comment by vitabaks** [comment]
PR https://github.com/vitabaks/postgresql_cluster/pull/400
