### ISSUE TITLE
Syntax error in postgresql_cluster/roles/ansible-role-firewall/tasks/main.ym

### ISSUE THREAD

**Issue by aakashmuthuramalingam** [vitabaks/postgresql_cluster#386]
Hello team,

       Getting syntax error while executing the playbook

ansible-playbook deploy_pgcluster.yml

> ERROR! couldn't resolve module/action 'community.general.modprobe'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/postgresql_cluster/roles/ansible-role-firewall/tasks/main.yml': line 46, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- block:
    - name: Load the nf_conntrack_ipv4 module
      ^ here

Ansible Version

> ansible 2.9.27
  config file = /root/postgresql_cluster/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 28 2022, 15:30:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

It is centos 7

I have not made any changes on this file too. Kindly help here.

**Comment by vitabaks** [comment]
Hello!

Minimum supported Ansible version: 2.11
