### ISSUE TITLE
patroni.yml.j2 auth method hard coded to md5

### ISSUE THREAD

**Issue by chuegel** [vitabaks/postgresql_cluster#389]
First of all thank you for this awesome playbook.

We successfully deployed patroni to a 3 node test cluster and noticed that in the `/etc/patroni/patroni.yml` file the pg_hba section is referencing `md5` as auth type.
The file is created from `roles/patroni/templates/patroni.yml.j2`

```bash
.
.
  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication {{ patroni_replication_username }} 127.0.0.1/32 md5
    - host all all 0.0.0.0/0 md5
.
.
```

shouldn't this use the auth method defined in vars/main.yml `postgresql_password_encryption_algorithm` ?

like 

```bash
.
.
  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication {{ patroni_replication_username }} 127.0.0.1/32 {{ postgresql_password_encryption_algorithm }}
    - host all all 0.0.0.0/0 {{ postgresql_password_encryption_algorithm }}
.
.
```

**Comment by vitabaks** [comment]
In fact, this configuration section is not accessible only during initdb and then we configure the pghba file using ansible.

But I agree with you that it is necessary to define a variable here.  feel free to create a PR or I'll do it myself a little later.

**Comment by vitabaks** [comment]
Done https://github.com/vitabaks/postgresql_cluster/pull/398
