### ISSUE TITLE
Wait for port 8008 to become open on the host

### ISSUE THREAD

**Issue by fatmaAliGamal** [vitabaks/postgresql_cluster#396]
```
TASK [patroni : Start patroni service on the Master server] **********************************************************************
changed: [10.0.4.61]

TASK [patroni : Wait for port 8008 to become open on the host] *******************************************************************
ok: [10.0.4.61]

TASK [patroni : Check PostgreSQL is started and accepting connections on Master] *************************************************
ok: [10.0.4.61]

TASK [patroni : Wait for the cluster to initialize (master is the leader with the lock)] *****************************************
ok: [10.0.4.61]

TASK [patroni : Prepare PostgreSQL | generate pg_hba.conf] ***********************************************************************
changed: [10.0.5.43]
changed: [10.0.4.61]
changed: [10.0.4.201]

TASK [patroni : Prepare PostgreSQL | reload for apply the pg_hba.conf] ***********************************************************
ok: [10.0.4.201]
ok: [10.0.5.43]
changed: [10.0.4.61]

TASK [patroni : Start patroni service on Replica servers] ************************************************************************
changed: [10.0.4.201]
changed: [10.0.5.43]

TASK [patroni : Wait for port 8008 to become open on the host] *******************************************************************
fatal: [10.0.5.43]: FAILED! => {"changed": false, "elapsed": 120, "msg": "Timeout when waiting for 10.0.5.43:8008"}
fatal: [10.0.4.201]: FAILED! => {"changed": false, "elapsed": 120, "msg": "Timeout when waiting for 10.0.4.201:8008"}
```

when I use pgbackrest

**Comment by vitabaks** [comment]
Check Patroni log

`sudo journalctl -u patroni`

**Comment by fatmaAliGamal** [comment]
Starting Runners to orchestrate a high-availability PostgreSQL - Patroni...
Jul 06 05:08:22 ip-10-0-5-31 sudo[14508]: postgres : PWD=/ ; USER=root ; COMMAND=/sbin/modprobe softdog
Jul 06 05:08:22 ip-10-0-5-31 sudo[14508]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=115)
Jul 06 05:08:22 ip-10-0-5-31 sudo[14508]: pam_unix(sudo:session): session closed for user root
Jul 06 05:08:22 ip-10-0-5-31 sudo[14510]: postgres : PWD=/ ; USER=root ; COMMAND=/bin/chown postgres /dev/watchdog
Jul 06 05:08:22 ip-10-0-5-31 sudo[14510]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=115)
Jul 06 05:08:22 ip-10-0-5-31 sudo[14510]: pam_unix(sudo:session): session closed for user root
Jul 06 05:08:22 ip-10-0-5-31 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL - Patroni.
Jul 06 05:08:23 ip-10-0-5-31 patroni[14512]: 2023-07-06 05:08:23,253 INFO: Selected new etcd server http://10.0.4.57:2379
Jul 06 05:08:23 ip-10-0-5-31 patroni[14512]: 2023-07-06 05:08:23,262 INFO: No PostgreSQL configuration items changed, nothing to reload.
Jul 06 05:08:23 ip-10-0-5-31 patroni[14512]: 2023-07-06 05:08:23,313 CRITICAL: system ID mismatch, node ip-10-0-5-31 belongs to a different cluster: 7252567923797276858 != 7252567842164459521
Jul 06 05:08:23 ip-10-0-5-31 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 05:08:23 ip-10-0-5-31 systemd[1]: patroni.service: Failed with result 'exit-code'.
Jul 06 05:08:24 ip-10-0-5-31 systemd[1]: patroni.service: Scheduled restart job, restart counter is at 1.
Jul 06 05:08:24 ip-10-0-5-31 systemd[1]: Stopped Runners to orchestrate a high-availability PostgreSQL - Patroni.
Jul 06 05:08:24 ip-10-0-5-31 systemd[1]: Starting Runners to orchestrate a high-availability PostgreSQL - Patroni...
Jul 06 05:08:24 ip-10-0-5-31 sudo[14537]: postgres : PWD=/ ; USER=root ; COMMAND=/sbin/modprobe softdog
Jul 06 05:08:24 ip-10-0-5-31 sudo[14537]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=115)
Jul 06 05:08:24 ip-10-0-5-31 sudo[14537]: pam_unix(sudo:session): session closed for user root
Jul 06 05:08:24 ip-10-0-5-31 sudo[14539]: postgres : PWD=/ ; USER=root ; COMMAND=/bin/chown postgres /dev/watchdog
Jul 06 05:08:24 ip-10-0-5-31 sudo[14539]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=115)
Jul 06 05:08:24 ip-10-0-5-31 sudo[14539]: pam_unix(sudo:session): session closed for user root
Jul 06 05:08:24 ip-10-0-5-31 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL - Patroni.
Jul 06 05:08:24 ip-10-0-5-31 patroni[14541]: 2023-07-06 05:08:24,799 INFO: Selected new etcd server http://10.0.4.57:2379
Jul 06 05:08:24 ip-10-0-5-31 patroni[14541]: 2023-07-06 05:08:24,809 INFO: No PostgreSQL configuration items changed, nothing to reload.
Jul 06 05:08:24 ip-10-0-5-31 patroni[14541]: 2023-07-06 05:08:24,813 CRITICAL: system ID mismatch, node ip-10-0-5-31 belongs to a different cluster: 7252567923797276858 != 7252567842164459521
Jul 06 05:08:25 ip-10-0-5-31 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 05:08:25 ip-10-0-5-31 systemd[1]: patroni.service: Failed with result 'exit-code'.
Jul 06 05:08:25 ip-10-0-5-31 systemd[1]: patroni.service: Scheduled restart job, restart counter is at 2.
Jul 06 05:08:25 ip-10-0-5-31 systemd[1]: Stopped Runners to orchestrate a high-availability PostgreSQL - Patroni.
Jul 06 05:08:25 ip-10-0-5-31 systemd[1]: Starting Runners to orchestrate a high-availability PostgreSQL - Patroni...
Jul 06 05:08:25 ip-10-0-5-31 sudo[14550]: postgres : PWD=/ ; USER=root ; COMMAND=/sbin/modprobe softdog
Jul 06 05:08:25 ip-10-0-5-31 sudo[14550]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=115)
Jul 06 05:08:25 ip-10-0-5-31 sudo[14550]: pam_unix(sudo:session): session closed for user root
Jul 06 05:08:25 ip-10-0-5-31 sudo[14552]: postgres : PWD=/ ; USER=root ; COMMAND=/bin/chown postgres /dev/watchdog
Jul 06 05:08:25 ip-10-0-5-31 sudo[14552]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=115)
Jul 06 05:08:25 ip-10-0-5-31 sudo[14552]: pam_unix(sudo:session): session closed for user root
Jul 06 05:08:25 ip-10-0-5-31 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL - Patroni.
Jul 06 05:08:26 ip-10-0-5-31 patroni[14554]: 2023-07-06 05:08:26,307 INFO: Selected new etcd server http://10.0.4.57:2379
Jul 06 05:08:26 ip-10-0-5-31 patroni[14554]: 2023-07-06 05:08:26,317 INFO: No PostgreSQL configuration items changed, nothing to reload.
Jul 06 05:08:26 ip-10-0-5-31 patroni[14554]: 2023-07-06 05:08:26,321 CRITICAL: system ID mismatch, node ip-10-0-5-31 belongs to a different cluster: 7252567923797276858 != 7252567842164459521
Jul 06 05:08:26 ip-10-0-5-31 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 05:08:26 ip-10-0-5-31 systemd[1]: patroni.service: Failed with result 'exit-code'.
Jul 06 05:08:27 ip-10-0-5-31 systemd[1]: patroni.service: Scheduled restart job, restart counter is at 3.
Jul 06 05:08:27 ip-10-0-5-31 systemd[1]: Stopped Runners to orchestrate a high-availability PostgreSQL - Patroni.
Jul 06 05:08:27 ip-10-0-5-31 systemd[1]: Starting Runners to orchestrate a high-availability PostgreSQL - Patroni...
Jul 06 05:08:27 ip-10-0-5-31 sudo[14571]: postgres : PWD=/ ; USER=root ; COMMAND=/sbin/modprobe softdog
Jul 06 05:08:27 ip-10-0-5-31 sudo[14571]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=115)
Jul 06 05:08:27 ip-10-0-5-31 sudo[14571]: pam_unix(sudo:session): session closed for user root
Jul 06 05:08:27 ip-10-0-5-31 sudo[14573]: postgres : PWD=/ ; USER=root ; COMMAND=/bin/chown postgres /dev/watchdog
Jul 06 05:08:27 ip-10-0-5-31 sudo[14573]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=115)
Jul 06 05:08:27 ip-10-0-5-31 sudo[14573]: pam_unix(sudo:session): session closed for user root
Jul 06 05:08:27 ip-10-0-5-31 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL - Patroni.
Jul 06 05:08:27 ip-10-0-5-31 patroni[14575]: 2023-07-06 05:08:27,799 INFO: Selected new etcd server http://10.0.5.31:2379
Jul 06 05:08:27 ip-10-0-5-31 patroni[14575]: 2023-07-06 05:08:27,808 INFO: No PostgreSQL configuration items changed, nothing to reload.
Jul 06 05:08:27 ip-10-0-5-31 patroni[14575]: 2023-07-06 05:08:27,813 CRITICAL: system ID mismatch, node ip-10-0-5-31 belongs to a different cluster: 7252567923797276858 != 7252567842164459521
Jul 06 05:08:28 ip-10-0-5-31 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 05:08:28 ip-10-0-5-31 systemd[1]: patroni.service: Failed with result 'exit-code'.
Jul 06 05:08:28 ip-10-0-5-31 systemd[1]: patroni.service: Scheduled restart job, restart counter is at 4.
Jul 06 05:08:28 ip-10-0-5-31 systemd[1]: Stopped Runners to orchestrate a high-availability PostgreSQL - Patroni.
Jul 06 05:08:28 ip-10-0-5-31 systemd[1]: Starting Runners to orchestrate a high-availability PostgreSQL - Patroni...
Jul 06 05:08:28 ip-10-0-5-31 sudo[14583]: postgres : PWD=/ ; USER=root ; COMMAND=/sbin/modprobe softdog
Jul 06 05:08:28 ip-10-0-5-31 sudo[14583]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=115)
Jul 06 05:08:28 ip-10-0-5-31 sudo[14583]: pam_unix(sudo:session): session closed for user root
Jul 06 05:08:28 ip-10-0-5-31 sudo[14585]: postgres : PWD=/ ; USER=root ; COMMAND=/bin/chown postgres /dev/watchdog
Jul 06 05:08:28 ip-10-0-5-31 sudo[14585]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=115)
Jul 06 05:08:28 ip-10-0-5-31 sudo[14585]: pam_unix(sudo:session): session closed for user root
Jul 06 05:08:28 ip-10-0-5-31 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL - Patroni.
Jul 06 05:08:29 ip-10-0-5-31 patroni[14587]: 2023-07-06 05:08:29,299 INFO: Selected new etcd server http://10.0.5.31:2379
Jul 06 05:08:29 ip-10-0-5-31 patroni[14587]: 2023-07-06 05:08:29,308 INFO: No PostgreSQL configuration items changed, nothing to reload.
Jul 06 05:08:29 ip-10-0-5-31 patroni[14587]: 2023-07-06 05:08:29,313 CRITICAL: system ID mismatch, node ip-10-0-5-31 belongs to a different cluster: 7252567923797276858 != 7252567842164459521
Jul 06 05:08:29 ip-10-0-5-31 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 05:08:29 ip-10-0-5-31 systemd[1]: patroni.service: Failed with result 'exit-code'.
Jul 06 05:08:30 ip-10-0-5-31 systemd[1]: patroni.service: Scheduled restart job, restart counter is at 5.
Jul 06 05:08:30 ip-10-0-5-31 systemd[1]: Stopped Runners to orchestrate a high-availability PostgreSQL - Patroni.
Jul 06 05:08:30 ip-10-0-5-31 systemd[1]: patroni.service: Start request repeated too quickly.
Jul 06 05:08:30 ip-10-0-5-31 systemd[1]: patroni.service: Failed with result 'exit-code'.
Jul 06 05:08:30 ip-10-0-5-31 systemd[1]: Failed to start Runners to orchestrate a high-availability PostgreSQL - Patroni.

**Comment by vitabaks** [comment]
> CRITICAL: system ID mismatch, node ip-10-0-5-31 belongs to a different cluster: 7252567923797276858 != 7252567842164459521

it looks like you already have a cluster named "postgres-cluster" and it has a different system ID, which means that the servers you are trying to add contain data from another Postgres instance.

How did this happen? Have you pre-installed postgres on the servers manually? 


To solve this problem, simply delete the data directory on the replicas, ONLY IF YOU ARE SURE THAT THIS DATA IS NOT BEING USED (for example, this is a test server).
Then start the playbook again, but first specify the variable postgresql_exists=true for the master host, since judging by the logs there, the database is already deployed and running.

**Comment by fatmaAliGamal** [comment]
there are new servers. i just  run ansible-playbook deploy_pgcluster.yml  -e "enable_timescale=true"  to deploy code at servers nothing install manual 

 and I make this test at more new server at ec2 but appear this again

**Comment by vitabaks** [comment]
Daily tests are successful and I can't reproduce the problem with different System IDs

Please attach the archive of your playbook I will check

**Comment by fatmaAliGamal** [comment]
postgresql_cluster_2.tar.xz
<https://drive.google.com/file/d/1Ek7klt1ZNsvkYESZOaClRM4TJprl1gdP/view?usp=drive_web>
i  use ubuntu 22.04
i run use
ansible-playbook deploy_pgcluster.yml -e "enable_timescale=true" -e
"AWS_ACCESS_KEY_ID=***" -e "AWS_SECRET_ACCESS_KEY=**" -e
"WALG_S3_PREFIX=s3://soa-backup/soabackup/"
i run code at new servers but  appear same error

**Comment by vitabaks** [comment]
Is this problem still relevant to you?

**Comment by fatmaAliGamal** [comment]
i will check it today and reply

**Comment by vitabaks** [comment]
@fatmaAliGamal update the status of the issue please
