### ISSUE TITLE
Missing ‘|’  in 'tasks/add-repository.yml' at line 30

### ISSUE THREAD

**Issue by marsdonne** [vitabaks/postgresql_cluster#4]
`TASK [Add repository] *************************************************************************************************************************************************************************************************
fatal: [192.168.56.136]: FAILED! => {"msg": "The conditional check 'yum_repository length > 0' failed. The error was: template error while templating string: expected token 'end of statement block', got 'length'. String: {% if yum_repository length > 0 %} True {% else %} False {% endif %}\n\nThe error appears to have been in '/root/postgresql_cluster/tasks/add-repository.yml': line 23, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n    - name: Add repository\n      ^ here\n"}`

the code is

`when: yum_repository length > 0`

should be

`when: yum_repository | length > 0`

**Comment by vitabaks** [comment]
Hi @marsdonne 

Please download the playbook and check again.
Thank you!

**Comment by marsdonne** [comment]
confirmed
