### ISSUE TITLE
How best practice to add postgres user and database to postgresql and pgbouncer?

### ISSUE THREAD

**Issue by patsevanton** [vitabaks/postgresql_cluster#41]
Hello! Thanks for postgresql_cluster
How to add postgres user and database in postgresql_cluster ?

**Comment by patsevanton** [comment]
I added user and database in postgres Leader, but
pgbouncer have error
2020-06-21 06:54:04.270 UTC [24589] WARNING C-0x194fa80: (nodb)/(nouser)@172.26.10.68:23930 pooler error: no such user: test

**Comment by vitabaks** [comment]
### During initial cluster deployment:

> How to add postgres user to postgresql?

Specify the user name and pasword in the `postgresql_users` variable.
example:
```
postgresql_users:
  - {name: "mydb-user", password: "mydb-user-pass"}
```

> How to add postgres database to postgresql?

Specify the database in the `postgresql_databases` variable.
example:
```
postgresql_databases:
  - {db: "mydatabase", encoding: "UTF8", lc_collate: "ru_RU.UTF-8", lc_ctype: "ru_RU.UTF-8", owner: "mydb-user"}
```

> How to add postgres user and database to pgbouncer?

Specify your database name in the `pgbouncer_pools` and user name in the `pgbouncer_users` variables.
example:
```
pgbouncer_pools:
  - {name: "mydatabase", dbname: "mydatabase", pool_parameters: "pool_size=20 pool_mode=transaction"}

pgbouncer_users:
  - {username: "mydb-user", password: "mydb-user-pass"}
```

### For an existing postgres(patroni) cluster:
Adding users and databases is no different from the standard postgresql management methods (see the [postgresql](https://www.postgresql.org/docs/current/index.html) and [pgbouncer](https://www.pgbouncer.org/usage.html) docs).

You can also re-run a specific task, or more.
Example:

```
ansible-playbook deploy_pgcluster.yml --tags postgresql_users,postgresql_databases
```
Configure pgbouncer.ini and userlist.txt
```
ansible-playbook deploy_pgcluster.yml --tags pgbouncer_conf
```
P.S.
See the list of available tags in [tags.md](https://github.com/vitabaks/postgresql_cluster/blob/master/tags.md) file.

**Comment by patsevanton** [comment]
https://github.com/vitabaks/postgresql_cluster/blob/master/vars/main.yml#L73

https://github.com/vitabaks/postgresql_cluster/blob/master/vars/main.yml#L80

https://github.com/vitabaks/postgresql_cluster/blob/master/vars/main.yml#L193

https://github.com/vitabaks/postgresql_cluster/blob/master/vars/main.yml#L199

Thanks!
