### ISSUE TITLE
ansible-playbook add_pgnode.yml

### ISSUE THREAD

**Issue by fatmaAliGamal** [vitabaks/postgresql_cluster#414]
run :: ansible-playbook add_pgnode.yml 
```
hosts.ini
---------
[etcd_cluster]
10.0.4.71 ansible_host=44.204.70.117 
10.0.4.158 ansible_host=18.208.106.130 
10.0.5.87 ansible_host=3.80.94.238 
[balancers]
10.0.4.71 ansible_host=44.204.70.117 
10.0.4.158 ansible_host=18.208.106.130 
10.0.5.87 ansible_host=3.80.94.238 
[pgbackrest]
10.0.4.71 ansible_host=44.204.70.117 
10.0.4.158 ansible_host=18.208.106.130 
10.0.5.87 ansible_host=3.80.94.238 
[master]
10.0.4.71 ansible_host=44.204.70.117 postgresql_exists='true'
[replica]
10.0.4.158 ansible_host=18.208.106.130 postgresql_exists='true'
10.0.5.87 ansible_host=3.80.94.238 postgresql_exists='true'
10.0.4.119 ansible_host=54.90.196.77 postgresql_exists=false new_node=true
[postgres_cluster:children]
master
replica
[all:vars]
ansible_connection='ssh'
ansible_ssh_port='22'
ansible_ssh_user=ubuntu
ansible_ssh_private_key_file=./postgres-db-key-test
[pgbackrest:vars]
ansible_connection='ssh'
ansible_ssh_port='22'
ansible_ssh_user=ubuntu
ansible_ssh_private_key_file=./postgres-db-key-test
```

error: 

```
TASK [pgbouncer : Copy pgbouncer.ini and userlist.txt conf files to replica] ****
changed: [10.0.4.119] => (item=pgbouncer.ini)
changed: [10.0.4.119] => (item=userlist.txt)

TASK [pgbouncer : Remove pgbouncer.ini and userlist.txt conf files from localhost] ***
failed: [10.0.4.119 -> localhost] (item=pgbouncer.ini) => {"ansible_loop_var": "item", "changed": false, "item": "pgbouncer.ini", "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
failed: [10.0.4.119 -> localhost] (item=userlist.txt) => {"ansible_loop_var": "item", "changed": false, "item": "userlist.txt", "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

failed: [10.0.4.119 -> localhost] (item=userlist.txt) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "userlist.txt",
    "module_stderr": "sudo: a password is required\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by fatmaAliGamal** [comment]
i solved it when 
sudo visudo.

postgres ALL=(ALL) NOPASSWD:ALL
but appear again same error with any made chane at cluster 
TASK [patroni : Prepare PostgreSQL | copy pg_hba.conf file to replica] ********************
changed: [10.0.4.119]

TASK [patroni : Start patroni service on Replica servers] *********************************
changed: [10.0.4.119]

TASK [patroni : Wait for port 8008 to become open on the host] ****************************
ok: [10.0.4.119]
FAILED - RETRYING: [10.0.4.119]: Check that the patroni is healthy on the replica server (1200 retries left).
FAILED - RETRYING: [10.0.4.119]: Check that the patroni is healthy on the replica server (1199 retries left).
FAILED - RETRYING: [10.0.4.119]: Check that the patroni is healthy on the replica server (1198 retries left).
FAILED - RETRYING: [10.0.4.119]: Check that the patroni is healthy on the replica server (1197 retries left).

**Comment by vitabaks** [comment]
@fatmaAliGamal Thank you for raising this issue.

Based on the error message you've provided, it seems the task "Remove pgbouncer.ini and userlist.txt conf files from localhost" might be encountering an issue due to the Ansible playbook trying to escalate privileges when it's not necessary.

To resolve this, we suggest setting become: false in this [task](https://github.com/vitabaks/postgresql_cluster/blob/4f46f57b91ec90f557bb4a4b9888989c7052b742/roles/pgbouncer/tasks/main.yml#L132). This change should inform Ansible that privilege escalation is not required to execute this specific task. The code would look as follows:

```yaml
- name: Remove pgbouncer.ini and userlist.txt conf files from localhost
  run_once: true
  become: false
  file:
    path: "files/{{ item }}"
    state: absent
  loop:
    - pgbouncer.ini
    - userlist.txt
  delegate_to: localhost
```

Could you please implement this change in your branch and test if it resolves the problem? We would appreciate your feedback on this proposed solution.

**Comment by fatmaAliGamal** [comment]
this is correct solution
and you need to add become: false 
    - name: Remove patroni.yml conf files from localhost
      run_once: true
      become: false
      file:
        path: files/patroni.yml
        state: absent
      delegate_to: localhost
   thanks for faster response
