### ISSUE TITLE
Patroni fails to start when `patroni_superuser_password` and `patroni_replication_password` are set to digits only phrases

### ISSUE THREAD

**Issue by 2hamed** [vitabaks/postgresql_cluster#42]
Apparently when Patroni wants to start it uses `String.encode()` on password phrases and when we set the password to something like `123456` it is stored as a number thus failing to execute `encode` on it and consequently the patroni service fails to start.

**Comment by vitabaks** [comment]
Hi @2hamed 
A password of only numbers is not a secure,  you should not use such a simple password in production systems.

**Comment by 2hamed** [comment]
Hi @vitabaks ,
You essentially right. I was just testing on a local cluster and noticed this issue and I thought maybe it could be fixed.

**Comment by vitabaks** [comment]
>  it could be fixed.

I think it doesn’t make much sense. 
But you can try to open the PR on the patroni project [repository](https://github.com/zalando/patroni).
