### ISSUE TITLE
exchanging Cluster types

### ISSUE THREAD

**Issue by marwan17705** [vitabaks/postgresql_cluster#428]
Hello,

After deployed successfully with Cluster types "B", how could I change from Cluster types "B" to Cluster types "A" ?

**Comment by vitabaks** [comment]
Hi!

1. Specify the servers in the inventory file in the "balancers" group

2. Deploy load balancers with the option to disable vip-manager

```
ansible-playbook balancers.yml -e "vip_manager_disable=true"
```
