### ISSUE TITLE
etcd error: i/o timeout  

### ISSUE THREAD

**Issue by erzhick10** [vitabaks/postgresql_cluster#430]
в чем может быть проблема?

**Comment by erzhick10** [comment]
failed to read e5fa22gfd664gfgfd0 on stream MsgApp v2 read tcp 172.16.6.6 172.16.6.4 i/o timeout

**Comment by vitabaks** [comment]
Я могу предположить, что Вы установили etcd на тех же серверах что и база данных и скорее всего не придерживались [рекомендации](https://github.com/vitabaks/postgresql_cluster#recommenations) размещать данные etcd на отдельном диске.

Проверьте метрики утилизации ресурсов сервера в вашей системе мониторинга. Скорее всего была повышенная нагрузка, например на диски.

**Comment by vitabaks** [comment]
рекомендую вынести etcd кластер на отдельные сервера
это могут быть 3 небольшие ВМ (на разных гипервизорах), крайне желательно чтобы диски были ssd.

Тогда Вы можете использовать этот один Etcd кластер для множества кластеров Patroni/Postgres.
Но обязательно следите за ресурсами и при необходимости добавьте больше ядер.
