### ISSUE TITLE
intsall type A show status as Active: active (exited)

### ISSUE THREAD

**Issue by miketwais** [vitabaks/postgresql_cluster#434]
i have install postgres_cluster follow as readme introduce, and use 'service postgresql status' see that status was "Active: active (exited)", and i can't connect postgres cluster use : psql -h localhost -p 5000 -U pgbouncer

error show  i can't connect to the master,how can i do?

**Comment by vitabaks** [comment]
Hi

Please give more details, what is the error?

**Comment by vitabaks** [comment]
Please try (not using the pgbouncer user)

```
psql -h <vip_or_balancer_ip> -p 5000 -U postgres
```

**Comment by vitabaks** [comment]
@miketwais please update the status of the issue, is the problem still relevant?

**Comment by vitabaks** [comment]
P.S. haproxy does not listen to localhost, only VIP if it is defined or local IPv4 address
