### ISSUE TITLE
"basebackup" has to exists on patroni_create_replica_methods?

### ISSUE THREAD

**Issue by lkthomas** [vitabaks/postgresql_cluster#457]
https://github.com/vitabaks/postgresql_cluster#restore-and-cloning

The link above shown an example of pgBackRest and WAL-G, but why "basebackup" is on both example? are they essential to be coexists?

**Comment by vitabaks** [comment]
It is used as a fallback method. That is, if it was not possible to create a replica from the backup (for example, there is no backup yet, during the initial deployment), the following method from the list will be used, in this case it is "basebackup".

You can redefine variables and comment out "basebackup" if its use is unacceptable in your environment.
