### ISSUE TITLE
Postgres cant start with changed postgresql_data_dir

### ISSUE THREAD

**Issue by tixass** [vitabaks/postgresql_cluster#46]
Hi!
I want store all postgresql data in other directory
I changed postgresql_data_dir: "/data/pgsql/{{ postgresql_version }}/data"
While systemctl started, it searches bases in /var/lib/pgsql/... directory
Its default environment in  /usr/lib/systemd/system/postgresql-12.service
I solved it manual but it need to be automated, yes?no?

OS: RedHat 7
Cluster: 3 servers

**Comment by vitabaks** [comment]
Hi @tixass 

You can set any path to PGDATA in `postgresql_data_dir` and this will work, the directory will be automatically created if it is missing.

Postgresql-12.service is not used in a clustered configuration.
See /etc/patroni/`patroni.yml` and `patroni` service.

Let me know if I have answered your question.

**Comment by vitabaks** [comment]
You should have seen this task while running the playbook:
```
 TASK [Disable "postgresql-12" service (will be managed by patroni)] ************
```

**Comment by tixass** [comment]
> Hi @tixass
> 
> You can set any path to PGDATA in `postgresql_data_dir` and this will work, the directory will be automatically created if it is missing.
> 
> Postgresql-12.service is not used in a clustered configuration.
> See /etc/patroni/`patroni.yml` and `patroni` service.
> 
> Let me know if I have answered your question.

Oh really, i understood, thanks!
