### ISSUE TITLE
Missing vars_files in update_pgcluster.yml

### ISSUE THREAD

**Issue by roks531** [vitabaks/postgresql_cluster#477]
Description of the problem:

I am just testing the newest additions of the update playbook and I found out that there is a missing vars_files in the update_pgcluster.yml for task name: "(1/4) PRE-UPDATE: Perform Pre-Checks". The update_pgcluster.yml playbook therefore fails.

Result of running ansible-playbook update_pgcluster.yml:
```
PLAY [(1/4) PRE-UPDATE: Perform Pre-Checks] ********************************************************************************************************************************

TASK [Running Pre-Checks] **************************************************************************************************************************************************

TASK [update : [Pre-Check] (ALL) Test PostgreSQL DB Access] ****************************************************************************************************************
fatal: [192.168.1.101]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'postgresql_port' is undefined. 'postgresql_port' is undefined\n\nThe error appears to be in '/home/user/postgresql_cluster/roles/update/tasks/pre_checks.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: '[Pre-Check] (ALL) Test PostgreSQL DB Access'\n  ^ here\n"}
```

Resolution:
Add the missing

```
  vars_files:
    - vars/main.yml
```

to the task name: "(1/4) PRE-UPDATE: Perform Pre-Checks"

**Comment by vitabaks** [comment]
Thank you @roks531 for notifying! I'll fix it.

This [commit](https://github.com/vitabaks/postgresql_cluster/commit/59999ae921f1acbc34781e9d666490218a5ded24) added the variable `postgresql_port`

Definitely I should add a playbook to the tests.

**Comment by vitabaks** [comment]
Fixed here https://github.com/vitabaks/postgresql_cluster/pull/478
