### ISSUE TITLE
Patroni restapi authentication question

### ISSUE THREAD

**Issue by alkorgun** [vitabaks/postgresql_cluster#481]
Hi. Is there any reason why authentication is not enabled at the [patroni restapi configuration](https://github.com/vitabaks/postgresql_cluster/blob/f8b74576c34f17c2fd33d28c8f7bd2b74941628f/roles/patroni/templates/patroni.yml.j2#L28) or this is just an error?

**Comment by vitabaks** [comment]
Hi @alkorgun 

I haven't encountered a need for it yet.

However, I'm open to enhancements. If you can provide a Pull Request for setting up authentication in the Patroni REST API configuration, I will definitely consider it.

**Comment by rcknr** [comment]
@alkorgun This has been added with #647
