### ISSUE TITLE
Рефакторинг - Имена переменных

### ISSUE THREAD

**Issue by sgrinko** [vitabaks/postgresql_cluster#49]
Добрый день!

Спасибо большое за вашу работу!

Предложение: 
есть переменная: `install_pgbouncer` однако если посмотреть на имена других подобных переменных, то мы увидим:
`patroni_install_version`
`wal_g_install`
`pgbackrest_install`
предлагаю изменить имя переменной на: `pgbouncer_install`

Ещё раз большое спасибо за вашу работу!

**Comment by vitabaks** [comment]
Привет @sgrinko 

Вы правы, сделаем. 
Спасибо за обратную связь.
