### ISSUE TITLE
TASK [patroni : Wait for port 8009 to become open on the host]

### ISSUE THREAD

**Issue by kumarashish071092** [vitabaks/postgresql_cluster#494]
Thanks for the superb playbook . I am getting " TASK [patroni : Wait for port 8009 to become open on the host]" error while executing it when it tries to start patroni on the primary server. 

**"fatal: [10.X.X.X]: FAILED! => {"changed": false, "elapsed": 120, "msg": "Timeout when waiting for 10.X.X.X:8009"}"**
When I start it manually on the Postgres server, the status shows active and becomes failed after 5 seconds. 

I am able to ssh the primary server from the Ansible server and the port is also open. Could you please help in getting ahead of this?

**Comment by vitabaks** [comment]
Hi @kumarashish071092 

Check the Patroni log
```
sudo journalctl -u patroni -n 100
```

**Comment by kumarashish071092** [comment]
Thanks for guiding to the right path. The bin directory was pointing to the wrong location. after fixing the issue, everything run smoothly.
