### ISSUE TITLE
http vs https

### ISSUE THREAD

**Issue by sgrinko** [vitabaks/postgresql_cluster#50]
Добрый день!

Спасибо большое за вашу работу!

Сейчас в коде в разных местах используется доступ в Internet и `http` и `https`

Предложение:
Сделать везде `https`, так как во многих компаниях, и у меня в том числе, открывают на серверах только `https` выход в Internet. 
Как вариант ввести параметризацию через переменную.

Ещё раз большое спасибо за вашу работу!

**Comment by vitabaks** [comment]
Опишите детальнее.

Переход на https каких компонентов? Опишите детальнее.

Как правильно, это предполагает генерацию и обмен сертификатами, более сложную настройку, контроль за сертификатами. И дополнительные накладные расходы от шифрования, особенно для таких компонентов как pgbouncer.

В своих инсталляциях я стараюсь избегать подобных конфигураций. Делая систему максимально простой и производительной.
Безопасность же отдана на откуп локальному и межсетевому firewall-у.

**Comment by vitabaks** [comment]
> Сейчас в коде в разных местах используется доступ в Internet и http и https

Если Вы говорите только о URL`s на пакеты:

1) Переменные доступны для редактирования.
2) Вы можете подгрузить необходимые пакеты на свой репозиторий и заменить URL`s.

**Comment by sgrinko** [comment]
у нас отрыт только https доступ в internet.
поэтому всегда когда я обновляюсь на новую версию скриптов, то просто везде тотально меняю адреса загрузки пакетов из Internet с 'http://' 'https://' иначе у меня ничего не работает.
Возможно, что весь сложный процесс :
Как правильно, это предполагает генерацию и обмен сертификатами, более сложную настройку, контроль за сертификатами. И дополнительные накладные расходы от шифрования, особенно для таких компонентов как pgbouncer.

**Comment by vitabaks** [comment]
Готово (a8ca3727707c4e08fad863c50d3748ed0bb98447).
Пожалуйста проверьте.

Все внешние ссылки теперь по https.
За исключением PPA для HAProxy 1.8 (только для Ubuntu 16.04/18.04). Он доступен только через http.

**Comment by sgrinko** [comment]
Спасибо большое!
Всё хорошо.
