### ISSUE TITLE
Question - Scaling/ Adding more nodes

### ISSUE THREAD

**Issue by m3ki** [vitabaks/postgresql_cluster#502]
First thank you for this wonderful code!

While going through my testing here in the lab, I stumbled on a potential issue for me.

I deployed a 3 node TYPE A cluster with HAproxy LB and etcd DCS.

In the scaling section you talk about adding a PG node and a load balancer node and you mention that those roles do not scale ETCD or consul.

How would I go about adding 2 more nodes,  post initial 3 node deployment?

My use case:

1. deploy 3 node cluster
2. later on add 2 more nodes as if I were to initially deploy 5 nodes?

Is this possible?

**Comment by vitabaks** [comment]
Yes, at the moment PostgreSQL node scaling is implemented, but not for DCS. 

I recommend deploying one ETCD cluster of 3 or 5 nodes on separate servers and using it with many Postgresql clusters.

**Comment by m3ki** [comment]
At the moment my application has to be deployed on 3 physical nodes so having postgres and etcd on same nodes is ideal. 

What would be the ideal recovery steps should 1 node physically fail?

Also if I were to add node separately would I create a new empty linux node then add etc then run add_pg_node and add_balancer node?

**Comment by vitabaks** [comment]
That's right, Playbooks `add_pg_node.yml` and `add_balancer.yml` (optional) will do everything for you, but we need to take care of the DCS cluster \
by supporting N/2+1 servers in an etcd or consul cluster (usually 3 or 5 nodes), while the number of Postgres cluster servers can be any (2 or more servers).

https://etcd.io/docs/v3.5/op-guide/runtime-configuration/#replace-a-failed-machine

I understand that managing an etcd cluster manually is not very convenient, so I plan to automate the scaling process for etcd and consul - https://github.com/vitabaks/postgresql_cluster/issues/503

**Comment by m3ki** [comment]
Hey, did you implement scaling?

**Comment by vitabaks** [comment]
Postgres cluster scaling was implemented several releases ago. DCS scaling is planned.

**Comment by m3ki** [comment]
> Postgres cluster scaling was implemented several releases ago. DCS cluster scaling is planned #503

Oh! Got it. For some reason I thought you did the DCS scaling after our last conversation :) I'll keep an eye on #503
