### ISSUE TITLE
Two pgbouncer : One for Master node and one for Secondary node

### ISSUE THREAD

**Issue by kumarashish071092** [vitabaks/postgresql_cluster#504]
Can we modify the existing playbook to have two pgbouncer ports each for the master and secondary node?

**Comment by vitabaks** [comment]
@kumarashish071092 why do you need two different ports? 

It is important to note that in the current database cluster schemes, pgbouncer is not a load balancer, it only acts as a connection puller and is installed directly in front of the database, routing connections over a local Unix socket.  

If you need load balancing (different ports for different database roles), then the "Tour A" scheme using the HAProxy load balancer is suitable for you.

**Comment by vitabaks** [comment]
Yes, "Tour A"  scheme provides the ability to distribute the load on reading.

port 5000 (read / write) master
port 5001 (read only) all replicas

So actually the connections will be routed to different servers (different connection pools).

**Comment by kumarashish071092** [comment]
So 5000 and 5001 will act as different connection pooling or it will only act as load balancer??

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vitabaks** [comment]
Haproxy will direct the load on port 5000 to the pgbouncer on the server with the role of "leader" (Primaty) and connections on port 5001 to the pgbouncer server with the role of "Replica".

![image](https://github.com/vitabaks/postgresql_cluster/assets/37010174/532d3a6a-d245-4cfd-8ac4-4821201e30b6)

**Comment by kumarashish071092** [comment]
Thanks for the detailed explanation. Please close this issue now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
