### ISSUE TITLE
Multi master setup

### ISSUE THREAD

**Issue by kumarashish071092** [vitabaks/postgresql_cluster#505]
Hi Vitaly ,

Can you please help me in setting up multi master Postgres node using patroni , ha and connection pooling?

I am looking to transfer more than 100tbs of data and need to do horizontal scaling and multi master setup.

**Comment by vitabaks** [comment]
Hi @kumarashish071092 

Patroni does not provide the ability to configure clusters in the multimaster scheme. Perhaps you may be interested in schemes using sharding based on the Citus extension, but this scheme is still only in TODO - https://github.com/vitabaks/postgresql_cluster/issues/258

Currently, you can deploy a scheme with read load scaling - the [Type A](https://github.com/vitabaks/postgresql_cluster#type-a-postgresql-high-availability-with-haproxy-load-balancing) scheme. But there is no scheme with scaling of the writing load yet.
