### ISSUE TITLE
Изменить present->latest в roles\packages\tasks\main.yml

### ISSUE THREAD

**Issue by sgrinko** [vitabaks/postgresql_cluster#51]
Добрый день!

Спасибо большое за вашу работу!

При эксплуатации наткнулся на проблему не обновления пакета ввиду уже имеющейся инсталяции предыдущей версии, в частности это был пакет python-psycopg2. Анализ показал, что это из-за того, что для установки используется параметр:
`state: present`
Из-за этого у меня в частности не смог стартовать `patroni` так как версия пакета оказалась старее чем необходимо.

Предложение:
Предлагаю указать принудительную установку последней версии: `state: latest`

Ещё раз большое спасибо за вашу работу!

**Comment by vitabaks** [comment]
Будут устанавливаться последние версии системных пакетов (включая psycopg, setuptools).

Для пакетов PostgreSQL остаётся режим `present`.
Так как плэйбук подерживает режим преобразования уже имеющейся (обычной) инсталляции в кластерную (Переменная postgresql_exists='true') в этом случае мы не должны навязывать самую свежую версии пакетов postgres.

**Comment by sgrinko** [comment]
Всё правильно, спасибо!
Конечно только системные пакеты
