### ISSUE TITLE
Добавление порта zabbix 10050 в firewall_allowed_tcp_ports_for

### ISSUE THREAD

**Issue by sgrinko** [vitabaks/postgresql_cluster#52]
Добрый день!

Спасибо большое за вашу работу!

Думаю, что многие, а не только я, используют zabbix. В default настройке порт zabbix не входит в список разрешённых...

Предложение:
предлагаю добавить в master ветку в список заранее разрешённых портов порт zabbix - 10050
```
файл vars/system.yml
...
firewall_allowed_tcp_ports_for:
...
  balancers:
    ...
    - "10050" # Zabbix agent порт
```

Ещё раз большое спасибо за вашу работу!

**Comment by vitabaks** [comment]
Мы также используем zabbix, netdata и некоторые другие сервисы.

**Но**, предполагается, что Вы самостоятельно определяете - дополняете список необходимых портов.
Я лишь могу добавить как доп поле для примера, но закоментированное:
```
#    - "10050" # Zabbix agent
```

**Comment by sgrinko** [comment]
Конечно, я так и делаю. У меня очень много правок везде не только в vars/main.yml
Просто даже как пример это будет отлично.
Я далеко не сразу понял где надо это добавлять :) 
А так будет хоть подсказка...
