### ISSUE TITLE
Repo list and url

### ISSUE THREAD

**Issue by kumarashish071092** [vitabaks/postgresql_cluster#522]
Hi Vitaly,

I have limited access of the internet from my server .

I need to get my server whitelisted from the internet for required repos only.

could you please help me in determining which url needs to be whitelisted to get this play book working smoothly?

**Comment by vitabaks** [comment]
I recommend using a [proxy](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/main.yml#L4) server in this case.

**Comment by vitabaks** [comment]
> could you please help me in determining which url needs to be whitelisted to get this play book working smoothly?

It very much depends on the chosen scheme and other values of the variables. Since all the code is open, you can get the entire list of URLs with the `grep`

example
```
grep -RE 'http://|https://' postgresql_cluster/* | grep -v '#' | grep -vE 'CONTRIBUTORS.md|CONTRIBUTING.md|README.md|molecule|tests|inventory_hostname' | uniq
```

**Comment by kumarashish071092** [comment]
how can we use proxy server in the following segment :

# Proxy variables (optional) for download packages using a proxy server
proxy_env: {}  # yamllint disable rule:braces
#  http_proxy: http://10.128.64.9:3128
#  https_proxy: http://10.128.64.9:3128<http://10.128.64.9:3128/>


consider I have a running patroni cluster HA having  servers ( 3 for etcd, 2 for postgres , 1 for ansible) and I want to download all the packages that are available in these servers to a new patroni cluster having another set of 5 servers on different domain. ( restricted to internet)..

Please suggest.

regards,
Ashish

________________________________

**Comment by kumarashish071092** [comment]
Please confirm if I understood correctly :


  1.  I have ansible stored on server 10.X.X.1
  2.
10.X.X.1 can access to internet and it was used to implement patroni HA cluster successfully.
  3.
server 10.X.X.2 is not having internet access .
  4.
server 10.X.X.3, 10.X.X.4 , 10.X.X.5 , 10.X.X.6 will be using 10.X.X.2  for patroni setup.
  5.
as per your statement I have to get below entry in 10.X.X.2 ansible playbook :

            proxy_env:
             http_proxy: http://10.X.X.1:22
            

________________________________

**Comment by vitabaks** [comment]
@kumarashish071092 yes
