### ISSUE TITLE
Use Docker to run cross-platform?

### ISSUE THREAD

**Issue by anhnmt** [vitabaks/postgresql_cluster#535]
You can package Docker images for versions so that they can be used in the easiest way. I encountered some problems when using ansible when using windows and was forced to use WSL.

I consulted and used the same method as kubespay and it worked quite well

https://github.com/kubernetes-sigs/kubespray#ansible

**Comment by vitabaks** [comment]
See https://github.com/vitabaks/postgresql_cluster/pull/464

**Comment by hunterelectros** [comment]
It will be very wonderful if you can pack this entire project into Docker. Could you then at least roughly give us an idea of when we can expect a new release (with Docker)?

**Comment by vitabaks** [comment]
The advantage of this project is that it works without using docker. 

We do not plan to use docker in the cluster, we are only adding the docker installer, but the cluster itself will still be without using docker.
