### ISSUE TITLE
Проблема с stats_temp_directory

### ISSUE THREAD

**Issue by sgrinko** [vitabaks/postgresql_cluster#54]
Добрый день!

Спасибо большое за вашу работу!

Параметр [stats_temp_directory](https://postgrespro.ru/docs/postgrespro/12/monitoring-stats) в postgres позволяет указать где хранить данные сборщика статистики и этот каталог можно делать прямо в ОЗУ (`tmpfs`) чтобы улучшить ввод вывод для этих операций. Прекрасно, что в данной реализации скриптов учтен этот важный момент, однако пару моментов не учтены.

1. нет возможности указать размер для такой директории в ОЗУ
2. нет возможности сменить имя для этой директории
3. нет возможности просто отказаться от такой возможности и оставить `default` вариант - каталог на диске как обычно.

в качестве частичного варианта реализации пункта 3 я использовал `--skip-tags "pgsql_stats_tmp"`, но при этом пришлось вручную комментировать соответствующий параметр в `roles/patroni/templates/patroni.yml.j2`: 
`#    stats_temp_directory: /var/lib/pgsql_stats_tmp`

Предлагаю внести соответствующие параметры для этого в vars/main.yml
stats_temp_directory_install
stats_temp_directory_path
stats_temp_directory_size

**Comment by vitabaks** [comment]
1. Выделяется до 1gb, большее значение не понадобится. По факту, используется не весь выделенный объём, а столько сколько требуется на данный момент. Проверьте с помощью df - h

2. С какой целью? (будет добавлена возможность указать другой путь ).

3. С какой целью? Прироста производительности это не даст. Стоит ли экономить пару мегабайт памяти это вопрос. (будет реализована возможность отключить создание в tmpfs).

**Comment by sgrinko** [comment]
Как я могу к вам обращаться ? Ко мне можно просто по имени - Сергей
1) сейчас выделяется 1 ГБ, сколько используется могу посмотреть конечно :) 
дело в том, что не на всех серверах достаточно ОЗУ, чтобы выделить целый Гигабайт для этого. У меня есть сервера у которых всего то 2 ГБ ОЗУ :)
2) другой путь может понадобиться если к примеру устанавливается постгрес на сервер, где уже стоит другой постгрес. В целях тестирования такое может быть легко.
3) как я уже писал выше, в целях выделения ОЗУ для других, более насущных, целей :)

**Comment by vitabaks** [comment]
Вы меня не поняли. По факту, не потребляется гигабайт.

**Comment by sgrinko** [comment]
Я вас понял прекрасно :)
Но я к примеру на очень многих серверах выделять для этого в ОЗУ часть памяти не могу. 
Думаю, что иметь возможность делать эти действия гибче будет хорошо для всех.

**Comment by vitabaks** [comment]
Будет реализовано.

**Comment by vitabaks** [comment]
Готово.

Переменные `postgresql_stats_temp_directory_path` и `postgresql_stats_temp_directory_size`
в vars/Debian.yml либо vars/RedHat.yml

**Comment by sgrinko** [comment]
Спасибо большое!
