### ISSUE TITLE
DNS is unable to connect from postgres port

### ISSUE THREAD

**Issue by kumarashish071092** [vitabaks/postgresql_cluster#540]
The DNS is getting a “connection timeout error” when connecting with Postgres port but it is working fine for pgbouncer port and haproxy port.

![image](https://github.com/vitabaks/postgresql_cluster/assets/91179630/5b336098-b934-4d8a-a0c7-6cb6624586f4)

do we need to make any changes in the configuration file? I have verified that the firewall is not blocking it.

**Comment by vitabaks** [comment]
Hi @kumarashish071092 

> but it is working fine for pgbouncer port and haproxy port.

Why do you want to connect directly via the postgres port? use the haproxy port

> getting a “connection timeout error” when connecting with Postgres port 

1. Check `postgresql.listen` option in `patroni.yml`. Perhaps your DNS refers to another IP address.
2. Check the Postgres logs.

**Comment by kumarashish071092** [comment]
HI Vitaliy,

The Postgres port is used for making LDAP connections .

the DNS is pointing to Virtual IP and the subdomain is allowed for all ports.

if the issue is with DNS , then it should not work for pgbouncer and HAproxy port as well.

Thoughts?

Regards,
Ashish
________________________________

**Comment by kumarashish071092** [comment]
sharing the listen addresses in the patroni.yml file :

[cid:8c3097d7-8df5-408f-bc5f-62b88484e1db]

restapi:
  listen: 10.10.9.119:8009
  connect_address: 10.10.9.119:8009

 listen_addresses: 0.0.0.0

postgresql:
  listen: 10.10.9.119,127.0.0.1:35432
  connect_address: 10.10.9.119:35432

connection details :

primary IP : 10.10.9.119
secondary IP : 10.10.9.120

VIP (DNS) : 10.10.9.118
________________________________

**Comment by vitabaks** [comment]
Use 10.10.9.119 instead of 10.10.9.120 for direct connection to the database. 

But if it needs the application to use a direct connection then just add 10.10.9.120 to patroni.yml file. \
But then the question arises why did you install pgbouncer if you don't use it?

**Comment by kumarashish071092** [comment]
Hi Vitaliy,

The application is using pgbouncer but for direct ldap connection from pgadmin/dbeaver , we use Postgres port only.

My primary ip is 10.10.9.119 and vip is 10.10.9.118

Can you suggest what to change in the patroni.yml file?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vitabaks** [comment]
`listen` option. Must contain a VIP address.

See the example above.

**Comment by kumarashish071092** [comment]
thanks for the detailed explanation. Working fine now. we can close this issue

**Comment by kumarashish071092** [comment]
making changes in patroni.yml file for parameter :
 postgresql:
  listen: 10.10.X.X,10.10.X.X,127.0.0.1:35432
  connect_address: 10.10.X.X:35432
