### ISSUE TITLE
Failover Multi region

### ISSUE THREAD

**Issue by farisam** [vitabaks/postgresql_cluster#542]
Hi @vitabaks ,

I have a question about failover with a secondary/replica multi regions. Using EC2, I plan to deploy four instances across two regions, with us-west-2 as the master and ap-east-1 as the  replica.

Regarding failover speed, how quickly can we switch to the secondary? If we doing a manual failover, can we simply update the IP address in the inventory file (switch master to ap-east-1 and us-west-2 set to replica) and rerun `ansible-playbook deploy_pgcluster.yml` ?

Thank you

**Comment by vitabaks** [comment]
For `switchover`, you can use the patronictl command.

```
patronictl switchover <cluster_name>
```

**Comment by vitabaks** [comment]
Placement of cluster members in different data centers:
If you’d prefer a cross-data center setup, where the replicating databases are located in different data centers, etcd member placement becomes critical.

There are quite a lot of things to consider if you want to create a really robust etcd cluster, but there is one rule: do not placing all etcd members in your primary data center. See some examples.

**Comment by farisam** [comment]
> Hi @farisam
> 
> For switchover, you can use the `patronictl` command.
> 
> ```
> patronictl switchover <cluster_name>
> ```

Thanks for the answer @vitabaks .

1 more question, 

If I have more than 1 replica, and I want to switchover/ failover to specific - cross region replica, can I use same command but targeted ip address?

**Comment by vitabaks** [comment]
Yes, you can use this command to switch regardless of the region. 

I recommend reading the Patroni documentation

**Comment by farisam** [comment]
Thank you @vitabaks 

I also curious about this one :

You said if we are using cloud
- For the "Type A" scheme: Use DNS records listing all HAProxy load balancing servers instead of relying on cluster_vip.

Do you mean we need to put all haproxy ip address by using route53?

**Comment by vitabaks** [comment]
It seems to me that this is not a very good recommendation (I will update the comments later) because if one of the HAProxy servers fails, DNS will continue to direct traffic there.

**Comment by farisam** [comment]
Thank you @vitabaks . So for cloud we can't have dynamic endpoint when the failover happens ya?

**Comment by vitabaks** [comment]
@farisam I wanted to share an idea regarding the challenge of implementing virtual IPs for HAProxy in AWS. While I haven't personally set up this exact configuration, according to AWS documentation, it's possible to use Amazon Route 53 health checks and DNS failover as an alternative. 
Route 53 can monitor the health of web servers and HAProxy instances, automatically rerouting traffic from unhealthy instances to healthy ones. This approach could effectively replace the need for a VIP, ensuring high availability across regions or instances. 

For detailed setup instructions, the AWS Route 53 Documentation is a great resource: [AWS Route 53 Health Checks and DNS Failover](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover.html).

**Comment by vitabaks** [comment]
@farisam I am currently working on integration with cloud providers - PR

And I added automatic Amazon Elastic Load Balancer (ELB) creation, here is an example: https://github.com/vitabaks/postgresql_cluster/pull/464#issuecomment-1912252310

I suggest we test it.

**Comment by farisam** [comment]
wow cool, let me test it @vitabaks . Thanks

**Comment by vitabaks** [comment]
@farisam How are you? Have you tested it?
