### ISSUE TITLE
getting "pooler error : "query_timeout_error" in pgbouncer logs

### ISSUE THREAD

**Issue by kumarashish071092** [vitabaks/postgresql_cluster#547]
if we want to check the connections getting established from connection pooling. how can we execute the "SHOW POOLS" command?

Do we have to create pgbouncer user and pgbouncer database and how it will store the active connections to debug "query_timeout_issue"?

**Comment by vitabaks** [comment]
> if we want to check the connections getting established from connection pooling. how can we execute the "SHOW POOLS" command?

```
psql -h <server_ip> -p 6432 -U postgres -d pgbouncer
```

> Do we have to create pgbouncer user and pgbouncer database and how it will store the active connections 

No. You do not need to explicitly create a pgbouncer database.

**Comment by kumarashish071092** [comment]
Thanks . We can close this issue now.
________________________________
