### ISSUE TITLE
Feature: HA Proxy: Direct connection to Primary and/or Replica (apart from pgbouncer)

### ISSUE THREAD

**Issue by jimnydev** [vitabaks/postgresql_cluster#548]
Prior to submitting a PR and considering a deployment with pgbouncer: I was wondering if you would find it useful to expose Primary and Replica nodes directly (skipping pgbouncer) in HA Proxy config (using two new ports)?

Use case would be for applications that need to connect using `replication` protocol (which currently isn't supported by pgbouncer, and is unlikely to be supported for a while).

Thanks!

**Comment by vitabaks** [comment]
Just specify the variables:

`with_haproxy_load_balancing: true`

`pgbouncer_install: false`

**Comment by jimnydev** [comment]
I would still like to have pgbouncer for connection pooling for other applications that are doing regular PostgreSQL protocol.

**Comment by vitabaks** [comment]
Now I understand that you are interested in the possibility of launching "selected" connections without the participation of a puller in a scenario using pgbouncer. 

This feature will require further development. Feel free to suggest a PR.

**Comment by jimnydev** [comment]
Resolved via #549. Thank you!
