### ISSUE TITLE
Unable to reflect postgresql parameter changes after executing playbook

### ISSUE THREAD

**Issue by kumarashish071092** [vitabaks/postgresql_cluster#550]
I have added below entries in vars/main.yml file : 

```
log_checkpoints = on
log_connections = on
log_disconnections =on
log_lock_waits=0
log_temp_files=0
log_autovacuum_min_duration=0
log_error_verbosity=default
log_statement=off
log_min_duration_statement=10
log_line_prefix = '%t [%p]: db=%d,user=%u,app=%a,client=%h '
```
After executing the playing the changes were not reflected in the database.

I have also added "pending_restart: false" and "pending_restart: true" and made modifications in the config_pgcluster.yml as well .

the query "select * from pg_settings where pending_restart is true;" is also giving null data.

what am I missing here?

**Comment by vitabaks** [comment]
@kumarashish071092 please attach the variables file `main.yml`, the ansible playbook execution `log`, and the result of the `command`

```
patronictl show-config
```

**Comment by kumarashish071092** [comment]
________________________________

**Comment by kumarashish071092** [comment]
@vitabaks any update here? I am trying few options but still it is not reflecting.

**Comment by vitabaks** [comment]
please attach

1. the variables file main.yml
1. the ansible playbook execution log
3. the result of the patronictl show-config command

**Comment by kumarashish071092** [comment]
[Re_ [vitabaks_postgresql_cluster] Unable to reflect postgresql parameter changes after executing playbook (Issue #550).zip](https://github.com/vitabaks/postgresql_cluster/files/13957712/Re_.vitabaks_postgresql_cluster.Unable.to.reflect.postgresql.parameter.changes.after.executing.playbook.Issue.550.zip)

**Comment by vitabaks** [comment]
### To change the Postgres configuration in a cluster using automation:

1) change the parameters in the `postgresql_parameters` variable. You can also specify the `pending_restart: true` variable so that Postgres is automatically restarted if a parameter change requires a restart.
2) run `config_pgcluster.yml` playbook to apply changes.

**Comment by vitabaks** [comment]
@kumarashish071092 Judging by ansible.log, you ran deploy_pgcluster.yml, but you need config_pgcluster.yml to manage the cluster parameters after deployment.

**Comment by vitabaks** [comment]
@kumarashish071092 Is the problem still relevant?

**Comment by sapisuper** [comment]
@vitabaks the problem still relevant, I also facing this problem.

**Comment by sapisuper** [comment]
please see the attachment, I will provided main.yml, ansible execution log and result from patronictl show-config

[issue-postgresql_cluster.zip](https://github.com/vitabaks/postgresql_cluster/files/14495709/issue-postgresql_cluster.zip)

**Comment by vitabaks** [comment]
according to the ansible log, I see that the task "Update conf file" has been completed

```
TASK [../../roles/patroni/config : Update conf file "/etc/patroni/patroni.yml"] ***********************************************************************************************************************************************************
changed: [172.16.11.99]
changed: [172.16.11.25]
changed: [172.16.12.156]
```

 but I do not see the task "Update postgresql parameters in DCS". Since no changes have been made to the DCS so you don't see the changes.

Please attach an archive of the entire postgresql_cluster directory so that I can analyze all the changes you have made.

**Comment by sapisuper** [comment]
@vitabaks hi Vita, thanks for you feedback I will check later.
