### ISSUE TITLE
PMM integration

### ISSUE THREAD

**Issue by ugenk** [vitabaks/postgresql_cluster#559]
Thank you so much for your awesome project!

Would be nice, if you will add support for the Percona Monitoring & Management client installation to the cluster, as described here:
https://docs.percona.com/percona-monitoring-and-management/setting-up/client/postgresql.html#pg_stat_monitor

**Comment by vitabaks** [comment]
Hi. Integration with PMM is not planned. You can install it yourself if you need it. 

Here is related issue https://github.com/vitabaks/postgresql_cluster/issues/249

There is something better (in my opinion) dashboards that I have developed personally.

**Comment by ugenk** [comment]
>There is something better (in my opinion) dashboards that I have developed personally.

would be nice to see them :)

**Comment by vitabaks** [comment]
https://gitlab.com/postgres-ai/pgwatch2
