### ISSUE TITLE
ERROR! 'cluster_vip' is undefined

### ISSUE THREAD

**Issue by jidckii** [vitabaks/postgresql_cluster#56]
Очень странное поведение, по пути выполнение ансибл как будто теряет переменную, при чём каждый раз в разных местах. При том в той таске в которой идёт выполнение, она вообще может не использоваться.

но тут все переменные в файле, перенеёс в inventory/dev/all.yaml 

всё из vars/main.yml и vars/system.yml  
по сути больше почти ничего не правил...

запускаю :
```
$ ansible-playbook -i inventory/dev/ balancers.yml 
```
падает вот так:
```
TASK [Generate conf file "/etc/confd/conf.d/haproxy.toml"] ********************************************************************************************************************************************************
Wednesday 26 August 2020  13:15:54 +0500 (0:00:01.561)       0:00:47.078 ****** 
ERROR! 'cluster_vip' is undefined
```

запускаю снова, падает уже на другой таске
```
TASK [Generate conf file "/etc/confd/conf.d/haproxy.toml"] ********************************************************************************************************************************************************
Wednesday 26 August 2020  13:20:42 +0500 (0:00:01.862)       0:00:42.198 ****** 
ok: [172.30.101.212]
ok: [172.30.101.210]
ok: [172.30.101.211]

TASK [Generate template "/etc/confd/templates/haproxy.tmpl"] ******************************************************************************************************************************************************
Wednesday 26 August 2020  13:20:44 +0500 (0:00:01.549)       0:00:43.747 ****** 
ERROR! 'cluster_vip' is undefined
```

в дебаге инфы не больше
```
$ ansible-playbook -i inventory/dev/ balancers.yml  -vvv
```
https://paste2.org/gED0YdAg

В чём может быть проблема ?
Впервые с таким встречаюсь и только в этом плейбуке...

**Comment by vitabaks** [comment]
Нужно разбираться, в таком виде не запускал.
Какая-то тонкость самого ansible...

**Comment by vitabaks** [comment]
@jidckii 
Проблему смог воспроизвести.
Очень похоже на какой-то баг (или ограничение) ansible.

Попробуйте открыть issue на репозитории ansible по этой проблеме. 
Я (пока) Вам не подскажу, могу лишь порекомендовать использовать плейбук в том виде, в котором он был предоставлен и протестирован.
