### ISSUE TITLE
switchover is happening to cluster but not the Virtual IP

### ISSUE THREAD

**Issue by kumarashish071092** [vitabaks/postgresql_cluster#564]
Hi Vitaliy,

I can see that using patronictl that in case of switchover the VIP is not getting assigned to the primary server automatically.

![image](https://github.com/vitabaks/postgresql_cluster/assets/91179630/91d7089d-ee7b-4159-9649-b5fe590a1e78)

but virtual IP is pointing to the wrong IP: 

![image](https://github.com/vitabaks/postgresql_cluster/assets/91179630/aff40e9d-653f-4cc2-ae55-0b60c44ee32b)

what Parameters I need to change to handle this properly ?

**Comment by vitabaks** [comment]
Are you using a Type A or Type B scheme?

**Comment by kumarashish071092** [comment]
Type A : PostgreSQL High-Availability with HAProxy Load Balancing
________________________________

**Comment by vitabaks** [comment]
@kumarashish071092 test it :)

HAProxy is [configured](https://github.com/vitabaks/postgresql_cluster/blob/master/roles/haproxy/templates/haproxy.cfg.j2#L36) in such a way as to direct traffic only to the server on which the patroni Rest API confirms that it is primary.
