### ISSUE TITLE
О настройке patroni 'pgpass:'

### ISSUE THREAD

**Issue by sgrinko** [vitabaks/postgresql_cluster#57]
Обратил внимание на перезапись файла с паролями `.pgpass` и начал разбираться...

Cвязался с разработчиками `patroni` и выяснил интересные факты о настройке `patroni 'pgpass:'` (сейчас default в Debian.yml и Redhat.yml - `'.pgpass'` )
разработчики ответили, что этот файл может быть с любым именем и используется для потоковой репликации. Нет никакой нужды давать ему имя `.pgpass`
указанный файл перезаписывается в следующих случаях:
- вход и выход из режима обслуживания на всех серверах кластера
- при рестарте ноды с ролью реплика на этой реплике
- при switchover или failover на всех серверах

В связи с этим предлагаю изменить в `yaml` скриптах начальное имя этого файла к примеру на `'.pgpass_patroni'`
Думаю, что многие как и я используют файл `'.pgpass'` со нужными мне доступами, то для меня это изменение очень важно.

Далее просто для новичков в patroni :)

Я уточнил у разработчиков как правильно менять настройки patroni, к примеру имя этого файла.
Если нужно изменить настройки patroni, кроме тех, которые хранятся в DCS (правятся командой edit-config), нужно сделать следующее:

- изменить данные файла конфигурации (/etc/patroni/patroni.yml)
- перевести кластер в режим обслуживания: patronictl -c /etc/patroni/patroni.yml pause --wait <кластер>
- перезапустить patroni на всех хостах: systemctl restart patroni
- снять режим обслуживания: patronictl -c /etc/patroni/patroni.yml resume <кластер>

 
Спасибо за вашу работу!

**Comment by vitabaks** [comment]
Это переменная `postgresql_pgpass` (vars/Debian.yml либо RedHat.yml) 

, она доступна для редактирования, как и другие переменные.

> предлагаю изменить в yaml скриптах начальное имя этого файла к примеру на '.pgpass_patroni'

Принято. Сделаем по умолчанию с именем pgpass_patroni

**Comment by vitabaks** [comment]
Готово (353877b9254494e8bb0ab248f63f99f95f2a5d7c).

Переменная postgresql_pgpass более не используется.

**Comment by sgrinko** [comment]
Спасибо!
