### ISSUE TITLE
Роли для maintenace режима patroni

### ISSUE THREAD

**Issue by sgrinko** [vitabaks/postgresql_cluster#58]
Предлагаю добавить 2 простые роли

- patroni_pause
- patroni_resume

их очень удобно использовать во время написания своих доп.ролей по обслуживанию кластера
```
- name: Prepare patroni | pause patroni ...
  run_once: true
  become: true
  become_user: root
  command: "/usr/local/bin/patronictl -c /etc/patroni/patroni.yml pause --wait {{ patroni_cluster_name }}"
  ignore_errors: yes
```
и
```
- name: Prepare patroni | resume patroni ...
  run_once: true
  become: true
  become_user: root
  command: "/usr/local/bin/patronictl -c /etc/patroni/patroni.yml resume --wait {{ patroni_cluster_name }}"
  ignore_errors: yes
```

**Comment by vitabaks** [comment]
Обратите внимание, что первоначальная цель разработки этой автоматизации была больше связана с первоначальным развертыванием кластера высокой доступности PostgreSQL, и поэтому в настоящее время он не занимается текущим обслуживанием кластера.

> их очень удобно использовать во время написания своих доп.ролей по обслуживанию кластера

Мне не совсем понятен смысл этих задач по части развертывпния кластеров.
Вы должны понимать, что данная автоматизация представляет из себя инсталлятор готовых к работе кластеров. 

Дополнительная логика лишь усложняет дальнейшее обслуживание этой автоматизации. 

Роли автоматизации задач управления я предлагаю Вам писать отдельными ролями.

**Comment by sgrinko** [comment]
Именно так я и делаю. 
Я пишу доп.роли рядом, опираясь на уже имеющиеся роли из комплекса по развертыванию кластера.
Указанные роли у меня и есть как отдельные.
Просто подумал, что если такие роли будут уже изначально, то это облегчит использование набора готовых ролей при написании своих плэйбуков по обслуживанию.
У меня эти роли используются при работе по обновлению pgbouncer во всем кластере на новую версию к примеру.
Думал, что если это полезно мне, то возможно и другим будет полезно.

**Comment by vitabaks** [comment]
А зачем Вы автоматизируете посредством ansible конкретно эту комманду?

Т.е. почему бы не просто перевести кластер в режим обслуживания путём запуска patronictl вручную?
Я в паузу перевожу именно так.

**Comment by sgrinko** [comment]
в ansible у меня изменение pgbouncer (обновление пакетов и реконфигурация его) перед запуском всего этого перевожу patroni в режим обслуживания и то же делаю это через ansible в одном playbook

**Comment by vitabaks** [comment]
Ну для обслуживания pgbouncer переводить patroni в maintenance mode не нужно, так как пуллер это отдельный компонент напрямую не связанный с patroni.
Но ладно, спасибо за обратную связь.
