### ISSUE TITLE
(UI) User Interface for installing and managing Postgres clusters

### ISSUE THREAD

**Issue by vitabaks** [vitabaks/postgresql_cluster#589]
Currently, the process of installing and managing PostgreSQL clusters is conducted through the command line, which can be inconvenient for users who are less familiar with terminal operations. We propose to create a graphical user interface (GUI) that would make the installation and management processes of PostgreSQL clusters more intuitive and accessible.

**Objectives**:
1. Simplify the PostgreSQL installation process by providing a graphical installer.
2. Develop a comprehensive GUI for managing PostgreSQL clusters, including the creation, configuration, and maintenance of clusters.
3. Integrate the ability to launch Ansible playbooks directly from the GUI to automate routine cluster management operations.
4. Ensure support for various operating systems, including Windows, Linux, and macOS (_perhaps it should be a web interface_).

**Anticipated Benefits**:
- Improved accessibility and usability for users without deep technical knowledge.
- Increased efficiency in managing clusters by simplifying routine tasks.
- Expansion of the project's user base by attracting new users who prefer graphical interfaces.
- Providing a self-managed alternative to cloud managed databases, which may be particularly relevant for organizations seeking to increase control over their data.

**Resource Request**:
The implementation of this feature will require resources in the form of fronted and backend developers, testers, as well as PostgreSQL and Ansible specialists to ensure integration and compatibility.

**Conclusion**:
Introducing a graphical interface for the installation and management of PostgreSQL clusters will significantly improve user experience and make the product accessible to a wider audience. This step could represent a significant enhancement to our project and contribute to its dissemination and popularity.

---

_Consider sponsoring the project via [GitHub](https://github.com/sponsors/vitabaks) or [Patreon](https://patreon.com/vitabaks)_

**Comment by vitabaks** [comment]
Draft:

**Postgres cluster console** - is a web interface designed for deployment (the first stage of development) and cluster management (subsequent versions). Packaged in docker (preferably one container) for the ability to run on different operating systems, on a corporate server, or just on a laptop.

It also includes a service designed to run a docker image in which the postgresql_cluster project code is packaged. The deployment and management of clusters are carried out using Ansible, which means that the service simply needs to launch the desired playbook (the `ansible-playbook` command is part of the postgresql_cluster container), if necessary with the necessary tags (`--tags`) depending on the task (for example, only create a database and user ID), and variables (`--extra-vars`) which are determined based on the selected options in the web interface.

As a basis for the design (discussed, designer's ideas are welcome), we can take an example of the implementation of Google Cloud SQL for PostgreSQL

![image](https://github.com/vitabaks/postgresql_cluster/assets/37010174/ee7a301b-c8ac-4e40-bac5-731dc4d989d5)
![image](https://github.com/vitabaks/postgresql_cluster/assets/37010174/1c0a51e4-95c9-4425-bdb3-4b57c62e95bf)

As an installer interface, we can take the example of [Aiven for PostgreSQ](https://aiven.io/postgresql)L in which we can choose where the cluster will deployed in five cloud providers: "Google Cloud", "AWS", "Azure", "DigitalOceon", "Hetzner Cloud" (related PR: https://github.com/vitabaks/postgresql_cluster/pull/464)

Here the user defines the region to deploy, the type of server, the disk size for the database, and other parameters. To get a list of regions, server types, and (possibly) to provide an approximate cost, it is necessary to provide integration with the API of cloud providers to obtain this data. \
This data will eventually be filled into the appropriate variables (will be described during implementation) and passed to the ansible-playbook command via the extra-vars option.

![image](https://github.com/vitabaks/postgresql_cluster/assets/37010174/d1ea1a34-8861-40e8-a25b-3c62b48d603f)

Example: https://www.youtube.com/watch?v=tJfQMubaspg


The sixth method is named "Your Own Machines" which is designed to deploy the cluster to ready-made servers (in another cloud provider or your own data center). \
Here the user fills in the data of their servers for connection, IP addresses, login password, or private SSH key for authorization.  Based on this data, an inventory file will be prepared which will be passed to the ansible-playbook command to execute playbooks on the target servers.

**Comment by vitabaks** [comment]
сс @ThomasSanson

**Comment by riker1** [comment]
Would it be possible to integrate pgAdmin? I'm not crazy about docker instances but could be persuaded otherwise if the Google version is better.

**Comment by vitabaks** [comment]
> Would it be possible to integrate pgAdmin?

I'm not a fan of pgAdmin, but I think it will be possible to think about adding a simple SQL editor to the UI interface (in one of the future versions) when elements for managing database clusters are added.

In the first implementation, this will primarily be an interface for installing clusters.

**Comment by rcknr** [comment]
I recently found [Ivory](https://github.com/veegres/ivory) which seems to match with many of the listed requirements. Given the maturity of the project it makes sense to consider it an option for including in the project.

**Comment by vitabaks** [comment]
@rcknr Thanks. I'll take a look at this.
We will most likely write our solution from scratch. I have already started drafting the user interface.

**Comment by rcknr** [comment]
So I just had a look and I have to say that Ivory seems to be exactly what was missing for me to have an overview of the cluster's operations. You have `patronictl` functionality and a summary of what's going on on the server right now.

**Comment by vitabaks** [comment]
We will have something more, we plan to make a free analog to cloud databases, which includes deployment, management, monitoring, etc.

**Comment by vitabaks** [comment]
Done.

**Looking ahead**, we are planning to enhance the PostgreSQL Cluster Console with features that will enable you to manage your PostgreSQL clusters directly through the UI. If you’re interested in supporting the continued development of this project, please consider becoming a [sponsor](https://github.com/vitabaks/postgresql_cluster?tab=readme-ov-file#sponsor-this-project).

**Comment by rcknr** [comment]
@vitabaks Could you add a screenshot please?

**Comment by vitabaks** [comment]
![image](https://github.com/user-attachments/assets/7d6970bb-a8a3-451f-88eb-56b580632fd6)

Example: https://postgresql-cluster.org/deployment/gcp

**Comment by rcknr** [comment]
Thanks! Is it possible to add this console to a deployed cluster?

**Comment by vitabaks** [comment]
There is no such button in the UI yet, but I think you can add information about your cluster directly to the Consumer database (table: clusters, servers).

**Comment by rcknr** [comment]
Okay, I was able to do that. However, I don't think everything is fully operational because I could not fill out many fields.
It'd be great to have an ability to import existing cluster.

**Comment by vitabaks** [comment]
> It'd be great to have an ability to import existing cluster.

This is planned for one of the future releases.

**Comment by vitabaks** [comment]
Next, add cluster management functionality https://github.com/vitabaks/postgresql_cluster/issues/754
