### ISSUE TITLE
проблема в patroni.service.j2

### ISSUE THREAD

**Issue by sgrinko** [vitabaks/postgresql_cluster#59]
Добрый день,

в файле сервиса для патрони есть вот такая строка
`WorkingDirectory=~`
при запуске видим вот такое сообщение:
```
Sep 10 15:15:55 sfactspostgres1 systemd[1]: [/etc/systemd/system/patroni.service:14] Not an absolute path, ignoring: ~
Sep 10 15:15:55 sfactspostgres1 systemd[1]: [/etc/systemd/system/patroni.service:14] Not an absolute path, ignoring: ~
```
в systemd сервисных файлах нужно указывать абсолютные пути.

**Comment by vitabaks** [comment]
> в файле сервиса для патрони есть вот такая строка
> WorkingDirectory=~

За основу взят этот пример: https://github.com/zalando/patroni/blob/master/extras/startup-scripts/patroni.service

**Comment by sgrinko** [comment]
понятно, но изменить надо )
всё равно systemd игнорирует эту строку заданную в таком виде.
лишние ошибочные сообщения зачем нам?

**Comment by sgrinko** [comment]
завёл им также issue насчет проблемки
https://github.com/zalando/patroni/issues/1688

**Comment by sgrinko** [comment]
По документации к systemd указание `~` должно работать, но у меня выдаёт ошибку на команде
`systemctl daemon-reload`
В наших скриптах развёртывания мы вполне можем указать там полный путь к домашней папке пользователя postgres
Как такое решение?

**Comment by vitabaks** [comment]
Проработаю этот момент.

**Comment by vitabaks** [comment]
Готово (280ecf0d2d8a31fd83c7d7a8032187f1d427debf)
