### ISSUE TITLE
Oracle Foreign Data Wrapper plugin

### ISSUE THREAD

**Issue by emccormickva** [vitabaks/postgresql_cluster#592]
Hi all,

I recently had a client request to install the Oracle FDW plugin on their Postgresql cluster which is deployed and maintained with this wonderful set of playbooks. I wrote a playbook to handle this for them and merged it into their local fork of this repo. 

Currently, it only supports EL9 and Oracle Instantclient 19.19 as that is what the customer is running, but is otherwise using and extending variables and structure already in tree here. If I were to extend it to support all of the other distros / versions supported here and add some variables for users to configure oracle client versions, would this be of interest to anyone? I'm not sure how much of an edge case this is, so I wanted to ask before putting the work in.

Cheers,
Erik

**Comment by vitabaks** [comment]
Hi @emccormickva 

I think it makes sense, but it should be an option and not a default setting. See an example of how I implement this for a future version ("Extension Auto-Setup") - https://github.com/vitabaks/postgresql_cluster/pull/464

example of a variable name: `enable_oracle_fdw`

**Comment by emccormickva** [comment]
Great. I'll work on cleaning it up and extending it to other distros. I did set it up as optional from the start

  roles:
    - role: oracle-fdw
      when: install_oracle_fdw|bool


I'll switch it to "enable_oracle_fdw" for consistency.

**Comment by vitabaks** [comment]
I chose `enable` instead of `install` because we not only install packages, but also automatically prepare the configuration if necessary.

**Comment by vitabaks** [comment]
See the [list of 300+ extensions](https://postgresql-cluster.org/docs/extensions/list) available for installation, including oracle_fdw

Doc: https://postgresql-cluster.org/docs/extensions/install
