### ISSUE TITLE
Default Python3 change breaks patroni during config_pgcluster run on RH variants

### ISSUE THREAD

**Issue by emccormickva** [vitabaks/postgresql_cluster#599]
Hello all,

I recently made a change to my cluster config (setting the timezone var explicitly) and ran config_pgcluster playbook to deploy it. Upstream changes to this project had been merged in since we did our last deploy or config update and it included PR #573 which changed the default system Python to 3.11 from 3.9. Patroni was entirely deployed with 3.9, and the change here doesn't address already-running python. 

I'm trying to untangle this now, but perhaps a change like this should be done by those who need it explicitly setting the python version to a non-system default rather than updating the default for everyone. At a minimum it needs to pull patroni into the new python modules if not present.

**Comment by vitabaks** [comment]
Hello!

Just specify the required version in `python_version` variable.
