### ISSUE TITLE
etcd from apt repo in ubuntu

### ISSUE THREAD

**Issue by ayadahm** [vitabaks/postgresql_cluster#603]
Hi 
I can see that the part of etcd installation and configuration part  is been implemented via  etcd github repo or a file . Is it possible doing that via the debian/ubuntu repo way ? I mean through the apt install command . 
for example for patroni part one can use "deb" method so it been installed through the apt.
Can it be implemented the same for etcd ?

Regards
Ayad Mohamed

**Comment by vitabaks** [comment]
@ayadahm Hi

What for? After all, this complicates the maintenance of the code.

**Comment by ayadahm** [comment]
Hi 

I was thinking just as for the patroni , all the packages can come from the ubuntu official repository . 
Apt update will not updates all the packages in this case. 

Regards
Ayad

**Comment by vitabaks** [comment]
there are many packages that are not installed from the apt repository (by default), for example patroni, confd, vip-manager.

To update the cluster, use playbook [update_pgcluster.yml](https://github.com/vitabaks/postgresql_cluster#update-the-postgresql-ha-cluster), it will take care of updating the necessary packages.

**Comment by vitabaks** [comment]
Feel free to prepare a PR if it's really important to you.
