### ISSUE TITLE
LXC containers: ignore errors in handlers io-scheduler and transparent_huge_pages

### ISSUE THREAD

**Issue by gmaruzz** [vitabaks/postgresql_cluster#61]
LXC containers will not allow to modify those values

see attached diff
[handlers_diff.txt](https://github.com/vitabaks/postgresql_cluster/files/5237408/handlers_diff.txt)

**Comment by vitabaks** [comment]
Hi @gmaruzz 

> LXC containers will not allow to modify those values

I do not support installing a database cluster in containers...

You can disable these tasks in your variable file (vars/system.yml):
`disable_thp: false`
`set_scheduler: false`

**Comment by gmaruzz** [comment]
Thanks!
