### ISSUE TITLE
haproxy.cfg creation issue

### ISSUE THREAD

**Issue by mathgonzlez** [vitabaks/postgresql_cluster#616]
Hi.

Im trying to deployin in rhel9.3 but when the procedure need to create the haproxy.cfg is created with an error

`listen replicas`
`    bind 192.168.60.118:5001`
`    maxconn 10000`
`    option tcplog`
`    option httpchk OPTIONS /replica?lag=100MB    balance roundrobin`
`    http-check expect status 200`
`    default-server inter 3s fastinter 1s fall 3 rise 2 on-marked-down shutdown-sessions`
`  server postgres-1 192.168.60.18:6432 check port 8008`
`  server postgres-2 192.168.60.45:6432 check port 8008`
`  server postgres-3 192.168.60.83:6432 check port 8008`
``
``
`listen replicas_sync`
`    bind 192.168.60.118:5002`
`    maxconn 10000`
`    option tcplog`
`    option httpchk OPTIONS /sync    balance roundrobin`
`    http-check expect status 200`
`    default-server inter 3s fastinter 1s fall 3 rise 2 on-marked-down shutdown-sessions`
`  server postgres-1 192.168.60.18:6432 check port 8008`
`  server postgres-2 192.168.60.45:6432 check port 8008`
  `server postgres-3 192.168.60.83:6432 check port 8008`
``
``
`listen replicas_async`
`    bind 192.168.60.118:5003`
`    maxconn 10000`
`    option tcplog`
`    option httpchk OPTIONS /async?lag=100MB    balance roundrobin`
`    http-check expect status 200`
`    default-server inter 3s fastinter 1s fall 3 rise 2 on-marked-down shutdown-sessions`
`  server postgres-1 192.168.60.18:6432 check port 8008`
`  server postgres-2 192.168.60.45:6432 check port 8008`
`  server postgres-3 192.168.60.83:6432 check port 8008`
  
  
  The right format is:
`option httpchk OPTIONS /async?lag=100MB    balance roundrobin`\

I see the j2 but seems to be ok.

Thanks!

**Comment by mathgonzlez** [comment]
i have the fix:

in roles/haproxy/templates/haproxy.cfg.j2

we need to change in all lines where:
    option httpchk OPTIONS /replica?lag={{ patroni_maximum_lag_on_replica }}{% if balancer_tags | default('') | length > 0 %}{{ '&' + balancer_tags.split(',') | map('trim') | map('regex_replace', '([^=]+)=(.*)', 'tag_\\1=\\2') | join('&') + '\n' }}{% endif %}
    balance roundrobin

To:
    option httpchk OPTIONS /replica?lag={{ patroni_maximum_lag_on_replica }}{% if balancer_tags | default('') | length > 0 %}{{ '&' + balancer_tags.split(',') | map('trim') | map('regex_replace', '([^=]+)=(.*)', 'tag_\\1=\\2') | join('&') + '\n' }}
{% endif %}
    balance roundrobin

As you can see the endif is after the 'option' line and not in the same line. With this im able to deploy without any issue

**Comment by vitabaks** [comment]
Thanks, I'll fix it. It looks like this MR broke the formatting if no tags are specified https://github.com/vitabaks/postgresql_cluster/pull/613

**Comment by mathgonzlez** [comment]
> Thanks, I'll fix it.
> 
> It looks like this MR broke the formatting if no tags are specified #613

ok, you re right, ill add the tag for haproxy and now works great. 

Thanks!

**Comment by vitabaks** [comment]
@mathgonzlez Fixed https://github.com/vitabaks/postgresql_cluster/pull/618
