### ISSUE TITLE
Patroni dependency missing

### ISSUE THREAD

**Issue by rcknr** [vitabaks/postgresql_cluster#626]
I've used the playbook to deploy a cluster on Ubuntu 22.04 several times now and every time `patronictl` was missing a dependency - `cdiff`. Upon installing it manually it worked fine. I'm wondering why is not installed by the playbook?

**Comment by vitabaks** [comment]
Hello @rcknr 

`cdiff` is optional and `ydiff` is used by default.

See requirements.txt  - https://github.com/vitabaks/postgresql_cluster/blob/master/files/requirements.txt

**Comment by vitabaks** [comment]
If you are experiencing problems with `patronictl`, then simply update Patroni to version [3.3.0](https://github.com/zalando/patroni/blob/master/docs/releases.rst#version-330)

**Comment by rcknr** [comment]
Sure, but without cdiff `patronictl` wasn't executing complaining about missing dependency.

**Comment by vitabaks** [comment]
> All older Partoni versions are not compatible with ydiff>=1.3.

 I don't see cdiff in the [required](https://github.com/zalando/patroni/blob/master/requirements.txt) dependencies. I think the update will solve the problem, please try.

**Comment by rcknr** [comment]
Okay, I see that you have updated Patroni version to 3.3.0 recently. I also see that this issue is addressed in [Patroni's release notes](https://github.com/zalando/patroni/blob/634b44ee0586f063033074806a42b534a354cbff/docs/releases.rst#L16).
