### ISSUE TITLE
Issue importing GPG from Postgres Repository and epel-release

### ISSUE THREAD

**Issue by aliencrash** [vitabaks/postgresql_cluster#63]
while running the playbook there is an error now regarding GPG importation
        "msg": "Failed to validate GPG signature for pgdg-redhat-repo-42.0-13.noarch",
This is maybe due to changes on posgres repository.
The same happen with epel-release. It was needed to add it manually

OS: Centos 8.
About a week ago was working without any issue from my tests.

**Comment by aliencrash** [comment]
I think your latest version solves the issue.

**Comment by aliencrash** [comment]
Nop, didn't solve the problem.

**Comment by vitabaks** [comment]
Hi @aliencrash 

I already fixed in this commit:

https://github.com/vitabaks/postgresql_cluster/commit/d684b22fbc08c7d1db4d75de7fc168bcb5c5de86

**Comment by aliencrash** [comment]
True, it was strange but it looks likes something was being reused after updating the code.
