### ISSUE TITLE
Have Different default_pool_size for two seperate database

### ISSUE THREAD

**Issue by kumarashish071092** [vitabaks/postgresql_cluster#631]
can we add settings in pgbouncer separately for a database which would be different from other databases:

I have two databases :

test
test1

Can I set something with **test database is having default_pool_size =20 for all user/database set and test1 database having default_pool_size =40 >**

I know it was implemented in few enterprise databases ( EDB,Crunchy etc) . Can we implement this in our playbooks ?

Thanks ,
Ashish

**Comment by vitabaks** [comment]
Yes, just describe the configuration of your pools in `pgbouncer_pools` variable, an example:

```yaml
pgbouncer_pools:
  - { name: "postgres", dbname: "postgres", pool_parameters: "" }
  - { name: "test", dbname: "test", pool_parameters: "pool_size=20 pool_mode=transaction" }
  - { name: "test", dbname: "test1", pool_parameters: "pool_size=40 pool_mode=transaction" }
```

And run playbook `config_pgcluster.yml` to apply the changes

```
ansible-playbook config_pgcluster.yml --tags "pgbouncer_conf"
```

**Comment by kumarashish071092** [comment]
after making the changes in pgbouncer_pools value in main.yml file and reexecuting the playbooks , pgbouncer is not starting . below is the pgbouncer.ini

[databases]
postgres = host=127.0.0.1 port=35432 dbname=postgres
prgx_scs_shared = host=127.0.0.1 port=35432 dbname=prgx_scs_shared default_pool_size=40

* = host=127.0.0.1 port=35432

[pgbouncer]
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /run/pgbouncer/pgbouncer.pid
listen_addr = 0.0.0.0
listen_port = 15432
unix_socket_dir = /var/run/postgresql
auth_type = scram-sha-256
auth_user = pgbouncer
auth_dbname = postgres
auth_query = SELECT usename, passwd FROM user_search($1)
admin_users = postgres
stats_users = postgres
ignore_startup_parameters = extra_float_digits,geqo,search_path

pool_mode = transaction
server_reset_query = DISCARD ALL
max_client_conn = 5000
default_pool_size = 20
query_wait_timeout = 0
reserve_pool_size = 1
reserve_pool_timeout = 1
max_db_connections = 400
pkt_buf = 8192
listen_backlog = 4096

log_connections = 0
log_disconnections = 0

what I am missing here?

________________________________

**Comment by vitabaks** [comment]
Please attach pgbouncer.log

**Comment by kumarashish071092** [comment]
the logs are not having any data when pgbouncer is having below value :

test= host=127.0.0.1 port=35432 dbname=test default_pool_size=40

this is happening because pgbouncer is not getting started.

Apr 19 07:36:08 atl20lv8215pg01.amer.prgx.com pgbouncer[756361]: unrecognized connection parameter: default_pool_size
Apr 19 07:36:08 atl20lv8215pg01.amer.prgx.com pgbouncer[756361]:  invalid value "host=127.0.0.1 port=35432 dbname=test default_pool_size=40" for parameter test in configuration (/etc/pgbouncer/pgbouncer.ini:5)

Apr 19 07:36:08 atl20lv8215pg01.amer.prgx.com pgbouncer[756361]: cannot load config file
Apr 19 07:36:08 atl20lv8215pg01.amer.prgx.com systemd[1]: pgbouncer.service: Control process exited, code=exited, status=1/FAIL>

Can we some other way to log the error?
________________________________

**Comment by vitabaks** [comment]
Replace default_pool_size to **pool_size**

**Comment by kumarashish071092** [comment]
worked now. thanks

we can close it now
________________________________
