### ISSUE TITLE
haproxy 5000 port write/read not working

### ISSUE THREAD

**Issue by oguzhansrky** [vitabaks/postgresql_cluster#64]
Hi,

Thank you very much for the game book.

When I type in the VIP ip address and port 5000 with Zabbix, I want it to load balance but it doesn't work.

Does the VIP ip address not provide both reading and writing to the system over port 5000? I installed the system on Type = A.

Thanks for your help in advance

**Comment by tyldum** [comment]
Works fine for me. How have you set it up?
Detailed network information on the haproxy node is essential. Also any
errors you might observe.

ons. 30. sep. 2020, 19:39 skrev oguzhansrky <notifications@github.com>:

**Comment by oguzhansrky** [comment]
there are no errors. After adding the zabbix server configuration file and starting the service, there is no error in the log file. however, while installing the interface, it freezes and the database fails.


3 machines. haproxy bouncer postgresql on the same machine

**Comment by oguzhansrky** [comment]
iptables all settings remove and clear. still didn't

**Comment by tyldum** [comment]
And connecting with psql says what?

**Comment by vitabaks** [comment]
Is the problem still relevant?

@tyldum thanks
