### ISSUE TITLE
Debian 12 - Ansible Issue - etcd Download Package

### ISSUE THREAD

**Issue by TheOriginalGraLargeShrimpakaReaper** [vitabaks/postgresql_cluster#643]
Hi Vitabaks

I have an Ansible Problem with Debian 12.
etcd hosts are reachable from Ansible Control Host.
But if i run the Playbook, the following Error appears:
```
TASK [etcd : Download "etcd" package] *****************************************************************************************************************************************************************************
failed: [xx.xx.xx.xx] (item=https://github.com/etcd-io/etcd/releases/download/v3.5.11/etcd-v3.5.11-linux-amd64.tar.gz) => {"ansible_loop_var": "item", "changed": false, "dest": "/tmp/", "elapsed": 0, "gid": 0, "group": "root", "item": "https://github.com/etcd-io/etcd/releases/download/v3.5.11/etcd-v3.5.11-linux-amd64.tar.gz", "mode": "0777", "msg": "Request failed: <urlopen error [Errno 111] Connection refused>", "owner": "root", "size": 4096, "state": "directory", "uid": 0, "url": "https://github.com/etcd-io/etcd/releases/download/v3.5.11/etcd-v3.5.11-linux-amd64.tar.gz"}
```
Prechecks succeded successfully.

The User have root Acces and i can Download the Package manual.
I've disabled iptables and use an other Proxy Host, but still the same Issue.
Logs tell not more than this.

**Comment by vitabaks** [comment]
> "Request failed: <urlopen error [Errno 111] Connection refused>"

it looks like a problem accessing to github.com from the servers where the etcd cluster is deployed.

**Comment by TheOriginalGraLargeShrimpakaReaper** [comment]
Hi vatabak

I made an mistake.
I didn't set the proxy in the vars/main.yml

So, there are two Solutions they worked:

1. Set the Proxy in vars/main.yml
2. Set Firewall Rules

I close this Issue

**Comment by TheOriginalGraLargeShrimpakaReaper** [comment]
Hi vatabak

I made an mistake.
I didn't set the proxy in the vars/main.yml

So, there are two Solutions they worked:

1. Set the Proxy in vars/main.yml
2. Set Firewall Rules

I close this Issue
