### ISSUE TITLE
How to add new users for postgres cluster without stopping the services?

### ISSUE THREAD

**Issue by tixass** [vitabaks/postgresql_cluster#66]
I just added through cmd, but my pga clients ( VSC, pgadmin) says `"no such user"`. 
Trying to add through main.yml and starting playbook make me failed on task `"patroni : Prepare PostgreSQL | data directory check result"` with `"Whoops! data directory /data/pgsql/12/data is already initialized" `message. 
My inventory file contains  `postgresql_exists='true'` I just thinking that pgbouncer rules the postgres users visibility? ^)
Sorry for my english ^))

**Comment by tyldum** [comment]
Try running the playbook with `--tags postgresql_users`.
See `tags.md` for list of all available tags that can be used for specific operations.

**Comment by vitabaks** [comment]
If you are using pgbouncer:

After creating a user in PostgreSQL, you need to update the /etc/pgbouncer/userlist.txt file

You can do it manually, or start the playbook with the tag:
```
ansible-playbook deploy_pgcluster.yml --tags pgbouncer_generate_userlist
```
or
Create postgres users and update pgbouncer userlist.txt file:
```
ansible-playbook deploy_pgcluster.yml --tags postgresql_users,pgbouncer_generate_userlist
```

**Comment by tixass** [comment]
Yes, all your advices worked for me. Thx very much!

> 
> 
> Try running the playbook with `--tags postgresql_users`.
> See `tags.md` for list of all available tags that can be used for specific operations.

**Comment by tyldum** [comment]
@vitabaks an idea to open up the wiki for detailing some of these things? Would be happy to help.

**Comment by vitabaks** [comment]
@tyldum 
I have invested a lot of time in this project, and if you are ready to help, I will be grateful to you.

I quote:
> Please note that the original design goal of this playbook was more concerned with the initial deploiment of a PostgreSQL HA Cluster and so it does not currently concern itself with performing ongoing maintenance of a cluster.
> 
> You should learn each component of the cluster for its further maintenance.

I'm not sure if need to fully describe the already existing documentation on the cluster components. 
Everyone should read the official documentation.

But, we can put answers to frequently asked questions in the wiki, and describe some of the advanced features of this automation.

**Comment by tyldum** [comment]
Yes, and I fully understand and agree.
However, I have discovered that there are quite a few maintenance tasks that can be performed using the tags, and you are under selling your work. 

I'm more and more impressed with the quality of the playbook the more I use it, it's a fantastic effort from you.

Up to you how you want to handle things. I plan on keeping an eye on the issues here and help out as much as possible. I rely on this in production, so it's win-win for me.
