### ISSUE TITLE
remove_cluster.yml - Documentation

### ISSUE THREAD

**Issue by TheOriginalGraLargeShrimpakaReaper** [vitabaks/postgresql_cluster#668]
Hello

I need to use `remove_cluster.yml`.
You wrote in the Documentation follow Information:
![Screenshot from 2024-05-29 17-06-52](https://github.com/vitabaks/postgresql_cluster/assets/118848945/0a8123ca-e84d-4df2-bf82-d55d5d7147f2)

But where or what is the safety Pin?
Where to write `remove_postgres: true` and `remove_etcd: true` in `remove_cluster.yml`?
I tried a couple of variations but it throws an error or the installation was not removed.

**Comment by vitabaks** [comment]
Hello @TheOriginalGraLargeShrimpakaReaper 

try `--extra-vars`

Example:
```
ansible-playbook remove_cluster.yml -e "remove_postgres=true"
```
