### ISSUE TITLE
How to use the tool to setup PG HA without internet?

### ISSUE THREAD

**Issue by dashng** [vitabaks/postgresql_cluster#669]
Hi,
Is it possible to setup HA without internet?
May I downloaded all dependencies and install manually then call the script to install HA cluster?

**Comment by vitabaks** [comment]
Hi @dashng 

For environments where there is no direct Internet access from servers, they can use a [proxy](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/main.yml#L4) server.

Or use the (more complex) offline installation method - `installation_method: file` https://github.com/vitabaks/postgresql_cluster/blob/master/vars/Debian.yml#L145

**Comment by vitabaks** [comment]
Related issue https://github.com/vitabaks/postgresql_cluster/issues/10#issuecomment-1917394005

**Comment by dashng** [comment]
Hi @vitabaks， thanks for your comments. I will try the offline mode on RHEL9.
By the way, does it possible to have only 2 nodes, master and slavor as the minimal size of the cluster?

**Comment by vitabaks** [comment]
Yes, provided that you use a dedicated DCS cluster (etcd or consul) consisting of 3 or more servers.

**Comment by vitabaks** [comment]
>  I will try the offline mode on RHEL9.

Feel free to suggest a PR with improvement, as offline installation is the most rarely used mode.

**Comment by dashng** [comment]
Sure, we will try and update here.
