### ISSUE TITLE
typo in roles/ssh-keys/tasks/main.yml

### ISSUE THREAD

**Issue by msavdert** [vitabaks/postgresql_cluster#672]
Line 50 in roles/ssh-keys/tasks/main.yml

Change this from

    - anable_ssh_key_based_authentication is defined

to

    - enable_ssh_key_based_authentication is defined

**Comment by vitabaks** [comment]
Hi @msavdert 

feel free to suggest a PR

**Comment by vitabaks** [comment]
Fixed https://github.com/vitabaks/postgresql_cluster/pull/706
