### ISSUE TITLE
wal-g build not possible due issue with libsodium script

### ISSUE THREAD

**Issue by ihor-tereshchuk** [vitabaks/postgresql_cluster#678]
I have encountered issue today. Playbook fails. See https://github.com/golang/go/issues/68107

**Comment by vitabaks** [comment]
@ihor-tereshchuk Thank you for informing me. It looks like a fix is on the way https://github.com/wal-g/wal-g/pull/1739

**Comment by vitabaks** [comment]
PR: https://github.com/vitabaks/postgresql_cluster/pull/693
