### ISSUE TITLE
Deploy after master init problem.

### ISSUE THREAD

**Issue by byazrail** [vitabaks/postgresql_cluster#68]
Hi guys,

`ansible-playbook deploy_pgcluster.yml`
after result;

`FAILED - RETRYING: Check PostgreSQL is started and accepting connections on Master (1000 retries left).`

<img width="936" alt="Screen Shot 2020-10-14 at 04 14 11" src="https://user-images.githubusercontent.com/5870455/95932179-cd62d900-0dd3-11eb-8111-905b5c1bbaa6.png">

**Comment by byazrail** [comment]
Cluster name change after problem resolved.

**Comment by vitabaks** [comment]
> Cluster name change after problem resolved.

Ok.
Are you using a dedicated etcd cluster?

I would also like to see the patroni log.
