### ISSUE TITLE
Make keepalived more configurable

### ISSUE THREAD

**Issue by abyss-ms** [vitabaks/postgresql_cluster#683]
It’d be nice to extend the keepalived role and make it possible to configure some options, for example, by adding the possibility of configuring more VIPs, virtual router IDs, and changing authentication. I'll prepare a PR for that and please let me know what you think about it. Thanks.

**Comment by vitabaks** [comment]
> by adding the possibility of configuring more VIPs

@abyss-ms Could you please explain why it might be necessary to have more than one VIP address for a database cluster?

**Comment by abyss-ms** [comment]
Sure, in my case, there is a separate network for VPN traffic, allowing other sides to connect to the database. Therefore, the VPN connection still has failover functionality.
