### ISSUE TITLE
Server with multiple network cards

### ISSUE THREAD

**Issue by SterhLight** [vitabaks/postgresql_cluster#686]
Привет.
Не могу найти в твоем проекте возможность выбора ip-адресов, на которых будет кластер, при наличии в сервере несколько сетевых карт. Я админю сервера по удаленке подключаясь к ним с интернета, а они объединены между собой локальной сетью. Реализована ли такая возможность или нет?
Спасибо.

**Comment by vitabaks** [comment]
Привет @SterhLight 

Испоьзуйте [переменные](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/main.yml#L10) `cluster_vip` чтобы назначить VIP адрес и `vip_interface` чтобы определить на каком именно интерфейсе его запускать.

**Comment by SterhLight** [comment]
> Привет @SterhLight
> 
> Испоьзуйте [переменные](https://github.com/vitabaks/postgresql_cluster/blob/master/vars/main.yml#L10) `cluster_vip` чтобы назначить VIP адрес и `vip_interface` чтобы определить на каком именно интерфейсе его запускать.

Возможно я не корректно выразился. Я имею ввиду не ip-адрес по которому следует отправлять запросы, а адреса, по которым ноды общаются между собой, на которых etcd будет, по которым идет служебный трафик.

**Comment by vitabaks** [comment]
Это будут те адреса которые указаны в inventory
