### ISSUE TITLE
How to create users to management for full access and read only users for netdata log monitoring?

### ISSUE THREAD

**Issue by algoritmsystems** [vitabaks/postgresql_cluster#691]
How to create users to management for full access and read only users for netdata log monitoring system?
Is it doing on leader node?
Thanks in advance!

**Comment by vitabaks** [comment]
You can do this simply by using SQL or by defining them in the `postgresql_users` variable in order for automation to create these users.

**Comment by algoritmsystems** [comment]
Thanks you very much for your work!

**Comment by vitabaks** [comment]
How is Netdata related to this? This is a user of the Postgres database.

**Comment by Jamic28** [comment]
> You can do this simply by using SQL or by defining them in the `postgresql_users` variable in order for automation to create these users.

I tried follow this instructions.
In my main.yml file I configured "netdata = true", so it is installing and working from the address ip:19999. But everyone has access to this web.
Can I restrict access to the netdata by creating users for monitoring and for administring separately? 
Thank you in advance!

**Comment by vitabaks** [comment]
As far as I know, there is no authorization in the local Netdata, only in the cloud. Please see the documentation of the Netdata project.

**Comment by Jamic28** [comment]
> As far as I know, there is no authorization in the local Netdata, only in the cloud. Please see the documentation of the Netdata project.

yes, but  some functions as logs you can's see without sign in

**Comment by vitabaks** [comment]
> Did you try to integrate pmm instead of netdata?

No. See related issue https://github.com/vitabaks/postgresql_cluster/issues/249
