### ISSUE TITLE
Automatic configuration of HugePages

### ISSUE THREAD

**Issue by vitabaks** [vitabaks/postgresql_cluster#697]
Feature: Automatic Configuration of HugePages

**Tasks:**

1. **Automatic Configuration of HugePages:**
   - Implement automatic detection and configuration of the `vm.nr_hugepages` parameter.
   - Link to the current setting: [system.yml#L56](https://github.com/vitabaks/postgresql_cluster/blob/1.10.0/vars/system.yml#L56).

2. **Pre-check:**
   - Add a pre-check for the `huge_pages` parameter in PostgreSQL.
   - If the `huge_pages` parameter is set to `on`, verify that the `vm.nr_hugepages` kernel parameter is configured with a sufficient value.

---

_Consider sponsoring the project via [GitHub](https://github.com/sponsors/vitabaks) or [Patreon](https://patreon.com/vitabaks)_

**Comment by rcknr** [comment]
I have just enabled this in my cluster with 1GB pages, so I could contribute to this feature.

**Comment by vitabaks** [comment]
@rcknr Thank you, I'm already working on it, I'll publish a PR soon and I'll be glad if you take part in the testing.

**Comment by vitabaks** [comment]
PR: https://github.com/vitabaks/postgresql_cluster/pull/713
