### ISSUE TITLE
Hello, I seem to have a problem. I always fail in this place 

### ISSUE THREAD

**Issue by cdy668** [vitabaks/postgresql_cluster#7]
failed: [xxx.xxx.xx.xx] (item=python36-devel) => {"ansible_loop_var": "item", "changed": false, "changes": {"installed": ["python36-devel"]}, "item": "python36-devel", "msg": "\n\nTransaction check error:\n  file /etc/rpm/macros.python from install of python-rpm-macros-3-32.el7.noarch conflicts with file from package python-devel-2.7.5-80.el7_6.x86_64\n\nError Summary\n-------------\n\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\nPackage python36-devel is obsoleted by python3-devel, trying to install python3-devel-3.6.8-10.el7.x86_64 instead\nResolving Dependencies\n--> Running transaction check\n---> Package python3-devel.x86_64 0:3.6.8-10.el7 will be installed\n--> Processing Dependency: redhat-rpm-config for package: python3-devel-3.6.8-10.el7.x86_64\n--> Processing Dependency: python3-rpm-macros for package: python3-devel-3.6.8-10.el7.x86_64\n--> Processing Dependency: python3-rpm-generators for package: python3-devel-3.6.8-10.el7.x86_64\n--> Processing Dependency: python-rpm-macros for package: python3-devel-3.6.8-10.el7.x86_64\n--> Running transaction check\n---> Package python-rpm-macros.noarch 0:3-32.el7 will be installed\n--> Processing Dependency: python-srpm-macros for package: python-rpm-macros-3-32.el7.noarch\n---> Package python3-rpm-generators.noarch 0:6-2.el7 will be installed\n---> Package python3-rpm-macros.noarch 0:3-32.el7 will be installed\n---> Package redhat-rpm-config.noarch 0:9.1.0-88.el7.centos will be installed\n--> Processing Dependency: dwz >= 0.4 for package: redhat-rpm-config-9.1.0-88.el7.centos.noarch\n--> Processing Dependency: zip for package: redhat-rpm-config-9.1.0-88.el7.centos.noarch\n--> Processing Dependency: perl-srpm-macros for package: redhat-rpm-config-9.1.0-88.el7.centos.noarch\n--> Running transaction check\n---> Package dwz.x86_64 0:0.11-3.el7 will be installed\n---> Package perl-srpm-macros.noarch 0:1-8.el7 will be installed\n---> Package python-srpm-macros.noarch 0:3-32.el7 will be installed\n---> Package zip.x86_64 0:3.0-11.el7 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package                    Arch       Version                   Repository\n                                                                           Size\n================================================================================\nInstalling:\n python3-devel              x86_64     3.6.8-10.el7              base     215 k\nInstalling for dependencies:\n dwz                        x86_64     0.11-3.el7                base      99 k\n perl-srpm-macros           noarch     1-8.el7                   base     4.6 k\n python-rpm-macros          noarch     3-32.el7                  base     8.8 k\n python-srpm-macros         noarch     3-32.el7                  base     8.4 k\n python3-rpm-generators     noarch     6-2.el7                   base      20 k\n python3-rpm-macros         noarch     3-32.el7                  base     7.7 k\n redhat-rpm-config          noarch     9.1.0-88.el7.centos       base      81 k\n zip                        x86_64     3.0-11.el7                base     260 k\n\nTransaction Summary\n================================================================================\nInstall  1 Package (+8 Dependent packages)\n\nTotal download size: 704 k\nInstalled size: 1.8 M\nDownloading packages:\n--------------------------------------------------------------------------------\nTotal                                              411 kB/s | 704 kB  00:01     \nRunning transaction check\nRunning transaction test\n"]}

**Comment by cdy668** [comment]
CentOS Linux release 7.6.1810 (Core)

**Comment by cdy668** [comment]
It seems to be in conflict with Python 2.7 that comes with the syste。Of course, my system confirms that it is a pure version

**Comment by vitabaks** [comment]
Hello, @cdy668 
Presumably python-rpm-macros is being pulled in as a dependency of python-devel.

In the bug, https://bugs.centos.org/view.php?id=16379 

TrevorH says: "The point is that python-rpm-macros.noarch has moved from EPEL to the distro itself. All would be fine with a compete `yum --enablerepo=cr update` first."


I will try to reproduce this problem and fix it in this playbook.

**Comment by vitabaks** [comment]
I could not reproduce your problem.
CentOS Linux release 7.6.1810 (Core) 3.10.0-957.12.2.el7.x86_64

Try updating your target systems first.
`yum update`

**Comment by cdy668** [comment]
> I could not reproduce your problem.
> CentOS Linux release 7.6.1810 (Core) 3.10.0-957.12.2.el7.x86_64
> 
> Try updating your target systems first.
> `yum update`

Thank you,After I tried Yum update, I did pass it.It does seem like a bug.

**Comment by vitabaks** [comment]
>It does seem like a bug.

But this is not a mistake of this playbook.

Preliminary updating of the operating system was not part of the tasks of this automation.

**Comment by cdy668** [comment]
> > It does seem like a bug.
> 
> But this is not a mistake of this playbook.
> 
> Preliminary updating of the operating system was not part of the tasks of this automation.


I think you are right.I have one more suggestion:
Installing PIP-related packages is the most time-consumin。I recommend this step to determine whether the local installation is already in place。If I install all the PIP packages in advance, playbook doesn't make a judgment that they already exist.

**Comment by vitabaks** [comment]
>determine whether the local installation is already in place

Could you formalize your wish as a separate issue? Since it is not entirely related to the problem described in this issue.

Thank!

**Comment by cdy668** [comment]
> > 确定本地安装是否已经到位
> 
> 你能否将自己的愿望正式化为一个单独的问题？由于它与本期中描述的问题并不完全相关。
> 
> 谢谢！

All right. Thank you for your reply

**Comment by cdy668** [comment]
> > 确定本地安装是否已经到位
> 
> 你能否将自己的愿望正式化为一个单独的问题？由于它与本期中描述的问题并不完全相关。
> 
> 谢谢！

**Comment by cdy668** [comment]
> > determine whether the local installation is already in place
> 
> Could you formalize your wish as a separate issue? Since it is not entirely related to the problem described in this issue.
> 
> Thank!

Thank you for your reply!
