### ISSUE TITLE
Pgbackrest install problem

### ISSUE THREAD

**Issue by byazrail** [vitabaks/postgresql_cluster#70]
Hi guys,

Deploy Result
<img width="1176" alt="Screen Shot 2020-10-16 at 04 52 54" src="https://user-images.githubusercontent.com/5870455/96203875-9b847a80-0f6b-11eb-82ef-6327c4431e9a.png">

Configs
<img width="1099" alt="Screen Shot 2020-10-16 at 04 53 46" src="https://user-images.githubusercontent.com/5870455/96203887-a0e1c500-0f6b-11eb-85a5-a02fd991f487.png">

Exists all node postgres user on .ssh/id_rsa, id_rsa.pub, authorized_keys
Logs
<img width="1521" alt="Screen Shot 2020-10-16 at 04 56 24" src="https://user-images.githubusercontent.com/5870455/96204078-1057b480-0f6c-11eb-897c-78294aeeb2e2.png">

**Comment by vitabaks** [comment]
Did you specify the IP address of the pgbackrest server in the [inventory](https://github.com/vitabaks/postgresql_cluster/blob/master/inventory) file?

**Comment by byazrail** [comment]
Added after error;

PLAY [pgbackrest:postgres_cluster] *************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************************
ok: [10.135.213.60]
ok: [10.135.213.62]
ok: [10.135.213.63]
fatal: [10.135.47.252]: FAILED! => {"msg": "Missing sudo password"}

inventory;
[pgbackrest:vars]
ansible_user='postgres'
ansible_ssh_port='1071'
ansible_ssh_pass='Secret'

**Comment by vitabaks** [comment]
This playbook requires root privileges or sudo.

Add postgres user to sudo on pgbackrest server.

**Comment by byazrail** [comment]
Problem resolved.

SSH port issues default port changed after ssh_keys known_hosts and pgbackrest have a problem.
Changed default port 22 for ssh.
