### ISSUE TITLE
How to make permanent changes on the postgresql cluster

### ISSUE THREAD

**Issue by JY-210** [vitabaks/postgresql_cluster#702]
I want to point the control node to below 2 ports:
- Port 7000 for haproxy stats
- Port 6432 for pgbouncer

I modified the configuration files and it works fine. But after i reboot the VM, the changes to listen to port 7000 and 6432 will disappear. Tested to modify the files after deploy the cluster and before deploy the cluster, but both having same issue. Would like to ask if there is a way to make the changes permanent even after reboot?

Thanks.

**Comment by vitabaks** [comment]
Hello. Please attach your vars/main.yml

**Comment by JY-210** [comment]
Hi, i pasted the parts that i did changes.

1. Control node - vars/main.yml (part Load Balancing)

# Load Balancing
with_haproxy_load_balancing: true  # or 'true' if you want to install and configure the load-balancing
haproxy_listen_port:
  master: 5000
  replicas: 5001
  replicas_sync: 5002
  replicas_async: 5003
  pgbouncer: 6432           **<------------------ added line**
# The following ('_direct') ports are used for direct connections to the PostgreSQL database,
# bypassing the PgBouncer connection pool (if 'pgbouncer_install' is 'true').
# Uncomment the relevant lines if you need to set up direct connections.
#  master_direct: 6000
#  replicas_direct: 6001
#  replicas_sync_direct: 6002
#  replicas_async_direct: 6003
  stats: 7000
haproxy_maxconn:
  global: 100000
  master: 10000
  replica: 10000
haproxy_timeout:
  client: "60m"
  server: "60m"


2. HAProxy node /etc/haproxy/haproxy.cfg

- Part listen stats

listen stats
    mode http
    bind [HAProxy node 1 IP]:7000
    bind [Control node IP]:7000   **<------------------ added line**
    stats enable
    stats uri /


- Part pgbouncer      **<------------------ newly added**

frontend pgbouncer_frontend
    bind *:6432
    default_backend pgbouncer_backend
    option tcplog

backend pgbouncer_backend
    balance roundrobin
    option httpchk OPTIONS /primary
    http-check expect status 200
    default-server inter 3s fastinter 1s fall 3 rise 4 on-marked-down shutdown-sessions
server pgnode01 [PGNODE01 IP]:6432 check port 8008
server pgnode02 [PGNODE02 IP]:6432 check port 8008
server pgnode03 [PGNODE03 IP]:6432 check port 8008


After the changes, I am able to view haproxy stats using [Control node IP]:7000 and connect [Control node IP]:6432 at pgadmin. Just that the changes won't be permanent.

**Comment by vitabaks** [comment]
> pgbouncer: 6432 <------------------ added line

See [pgbouncer_listen_port](https://github.com/vitabaks/postgresql_cluster/blob/1.10.0/vars/main.yml#L310) variable

If you want to make manual changes (not recommended) to the HAProxy configuration after deploying the cluster, then you need to do this in the `confd` service template because it manages the haproxy configuration.

`/etc/confd/templates/haproxy.tmpl`

**Comment by JY-210** [comment]
May I know any concerns if edited /etc/confd/templates/haproxy.tmpl?

**Comment by vitabaks** [comment]
Well, I would say that manual modification is highly undesirable, only if you know what you are doing, with mandatory testing before starting production.
