### ISSUE TITLE
Leader переходит в режим read only при отказе сети между 2 датацентрами.

### ISSUE THREAD

**Issue by stomperkgz** [vitabaks/postgresql_cluster#71]
Развернул кластер, имеется 4 ноды. 2 в одном датацентре, 2 в другом. Между ними ipsec туннель. При обрыве туннеля leader уходит в Read Only. Хотя статус этого не показывает. Все возвращается в исходное состояние только после восстановления связи между всеми 4 нодами.

| Member | Host           | Role    | State   | TL | Lag in MB |
+--------+----------------+---------+---------+----+-----------+
| db01   | 192.168.14.161 | Leader  | running | 22 |           |
| db02   | 192.168.14.162 | Replica | running | 22 |         0 |
| db03   | 192.168.15.163 | Replica | running | 22 |         0 |
| db04   | 192.168.15.164 | Replica | running | 22 |         0 |
+--------+----------------+---------+---------+----+-----------+

При нормальном выключении 1 ноды, проблем не замечается.

**Comment by vitabaks** [comment]
Мастер переходит в режим чтения если он не может обновить ключ лидера в DCS. Это ожидаемое повидение.

Хотя Вы и не предоставили лог Patroni, могу предположить, что Вы развернули кластер etcd из 4-х нод, по два в каждом Датацентре, что вкорне неверно.

1. Ознакомьтесь с тем как работает алгоритм RAFT
http://thesecretlivesofdata.com/raft/

2. Ознакомьтесь с рекомендациями
"Placement of cluster members in different data centers"
https://github.com/vitabaks/postgresql_cluster#recommendations

**Comment by stomperkgz** [comment]
Спасибо за информацию. Если я вынесу еще 1 etcd ноду без самого Postgres вне этих 2 ДЦ. Например vds или облако в качестве так сказать арбитора, это будет надежное решение? И решит проблему?

**Comment by vitabaks** [comment]
Да. Достаточно по одной etcd ноды в трёх ДЦ.
