### ISSUE TITLE
timescaledb version Definition

### ISSUE THREAD

**Issue by warlockedward** [vitabaks/postgresql_cluster#718]
Since Zabbix 7.0 has a requirement for timescaledb to be no higher than 2.15.0, but I found after running Ansible that using either pg15 or pg16, the version of timescaledb is 2.16.0, is it possible to specifically define the version number of timescaleDB

**Comment by vitabaks** [comment]
Hi @warlockedward 

Yes, here is an example:
```yaml
postgresql_packages:
  - timescaledb-2-postgresql-{{ postgresql_version }}=2.15.0

```

**Comment by vitabaks** [comment]
but there is no package of this version in the official repository anymore.
```
root@pgnode01:/# apt search timescaledb-2-postgresql-16
Sorting... Done
Full Text Search... Done
timescaledb-2-postgresql-16/jammy,now 2.16.0~ubuntu22.04 amd64 [installed]
  An open-source time-series database based on PostgreSQL, as an extension.
```

**Comment by warlockedward** [comment]
well,I found a new problem is that after using remove_cluster.yml I found that all the servers still have postgresql,patroni,etcd etc. Do I need to use any extra parameters?

**Comment by vitabaks** [comment]
```
ansible-playbook remove_cluster.yml -e "remove_postgres=true" -e "remove_etcd=true"
```

**Comment by warlockedward** [comment]
> but there is no package of this version in the official repository anymore.
> 
> ```
> root@pgnode01:/# apt search timescaledb-2-postgresql-16
> Sorting... Done
> Full Text Search... Done
> timescaledb-2-postgresql-16/jammy,now 2.16.0~ubuntu22.04 amd64 [installed]
>   An open-source time-series database based on PostgreSQL, as an extension.
> ```

well，i try it .
postgresql_packages:
  - timescaledb-2-2.14.2-postgresql-16=2.14.2~ubuntu22.04
  - timescaledb-2-loader-postgresql-16=2.14.2~ubuntu22.04
