### ISSUE TITLE
'cluster_vip' is undefined

### ISSUE THREAD

**Issue by aikrash** [vitabaks/postgresql_cluster#726]
Good day. No matter how I tried to use balancing, I always get the error 'cluster_vip' ​​is undefined. Whether you specify vip_cluster or not, it's still the same error.

**Comment by vitabaks** [comment]
This should not be the case since the cluster_vip variable is declared in vars/[main.yml ](https://github.com/vitabaks/postgresql_cluster/blob/1.11.0/vars/main.yml#L10)

Please attach the log with error.
