### ISSUE TITLE
Migration from On-Premises to AWS RDS

### ISSUE THREAD

**Issue by shailabsinghha** [vitabaks/postgresql_cluster#731]
We have running cluster on premises using this playbook but now we would like to move to AWS RDS. We would like to do this using replication to ensure zero downtime of the application. Could you please help me with the replication if feasible?  

There is a add_node feature in this playbook but i am not sure how it can be used to do this in a already managed instance.

cc: @vitabaks

**Comment by vitabaks** [comment]
Your request goes beyond the scope of postgresql_cluster automation. add_node is intended for scaling the Patroni cluster, but not for migration to RDS.

Look towards using logical replication for this task.
