### ISSUE TITLE
How to configure one aplications to read only from replica and other ones just to write to master node?

### ISSUE THREAD

**Issue by Jamic28** [vitabaks/postgresql_cluster#736]
As far as I know, now an application connected to a VIP address:5000 can only read/write from/to  master node. How to configure one aplication to read only from replica and other one just to write to master node of the postgres cluster? Or it is recommended to raise a separate read-only replica server outside the cluster?
Can I configure HA Proxy load balancer for this purpose?
Thanks!

**Comment by vitabaks** [comment]
You don’t need to configure HAProxy, as the automation will handle everything for you. However, to separate read and write traffic, your application must support sending read requests to a custom port (5001).

**Comment by Jamic28** [comment]
Thanks!
