### ISSUE TITLE
Possibility of adding privileges to objects

### ISSUE THREAD

**Issue by abyss-ms** [vitabaks/postgresql_cluster#737]
Hi @vitabaks 
I have a question regarding the possibility of adding privileges for users. In the postgresql_cluster project, we can find roles for adding users, databases, and schemas, but there doesn't seem to be an option to add privileges or create a role with specific privileges. Sometimes, it is necessary to create a role (or add a specific privilege to user) like pg_ls_waldir() for example for monitoring purposes. Additionally, some users or service accounts should not have full read/write access to the database.

Is it not possible to add privileges, or is there a solution that I might have missed?

Thank you in advance for your response.

**Comment by vitabaks** [comment]
Hi @abyss-ms 

For this task, we can create roles to perform modules such as [postgresql_owner](https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_owner_module.html#ansible-collections-community-postgresql-postgresql-owner-module), [postgresql_membership](https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_membership_module.html#ansible-collections-community-postgresql-postgresql-membership-module) and [postgresql_privs](https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_privs_module.html#ansible-collections-community-postgresql-postgresql-privs-module) modules. Or [postgresql_query](https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_query_module.html#ansible-collections-community-postgresql-postgresql-query-module) as a more versatile option.

in the meantime, you have the opportunity to use `post_deploy_command` [variable](https://github.com/vitabaks/postgresql_cluster/blob/master/automation/vars/system.yml#L240), in which you can specify any script / command that will be executed after the cluster deployment.

**Comment by abyss-ms** [comment]
Cool. Thank you for your reply. Nice to know about post_deploy_command variable - I haden't noticed it :)
I will try to prepare something regarding postgresql_privs soon then.
