### ISSUE TITLE
Issue at postgresql_cluster/automation/roles/ when running playbook

### ISSUE THREAD

**Issue by JY-210** [vitabaks/postgresql_cluster#741]
Hi,

Previously I am able to run the playbook using the old repo with everything inside postgresql_cluster/. 
Now I am trying to rebuild all the thing. I deleted the old repo, clone the new repo and found that there are errors likely due to the required Ansible collection not being installed or an issue with how the module is referenced.
Error:
ERROR! couldn't resolve module/action 'ansible.builtin.deb822_repository'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/infraoperator/postgresql_cluster/automation/roles/add-repository/tasks/main.yml': line 14, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: Add repository
      ^ here

May I know what version of ansible should i use? Or any ways to use back the previous repo? 
Thank you.

**Comment by vitabaks** [comment]
Hi @JY-210 

> May I know what version of ansible should i use?

Minimum supported Ansible version: 8.0.0 (ansible-core 2.15.0)

> Or any ways to use back the previous repo?

https://github.com/vitabaks/postgresql_cluster/tree/1.11.0

**Comment by JY-210** [comment]
Thank you!

May I have a brief summary on the latest repo? Is it integrated with cloud?

**Comment by vitabaks** [comment]
https://github.com/vitabaks/postgresql_cluster/releases/tag/2.0.0
