### ISSUE TITLE
PostgreSQL High-Availability with Load Balancing

### ISSUE THREAD

**Issue by Jamic28** [vitabaks/postgresql_cluster#743]
I don't understand how haproxy works in 2 scheme: PostgreSQL High-Availability with Load Balancing.
How it doing load balancing? First haproxy loads balancing and then hands over to pgbouncer? When if master falls and after switching master how it works then? As I know ansible playbook installs haproxy on each node, Is it controlled by vip address?
Thanks!

**Comment by vitabaks** [comment]
Hello.

HAProxy interacts with Patroni via REST API, periodically polling it to determine the current primary and replicas, and based on this information, it directs traffic to the appropriate database server. If the current primary fails and Patroni promotes a new primary server, HAProxy automatically redirects traffic to the new primary based on the data retrieved from Patroni through the REST API.

The VIP address is maintained by the keepalived service, which ensures high availability of HAProxy itself. 

PgBouncer does not participate in load balancing in this scenario; it acts as a connection pooler directly in front of the database. Its use is recommended for optimizing connection management, but it is an optional component.

**Comment by Jamic28** [comment]
Thanks @vitabaks for your answer!
Did I understand correctly: HAProxy doing health check patroni on the same node and if primary server falls then replica switches to master in case of failure, and then the VIP address also somehow health checks the patroni and then redirects the traffic to the new HAProxy to the appropriate node?

**Comment by Jamic28** [comment]
Thanks!
