### ISSUE TITLE
How to remove a node from existing cluster?

### ISSUE THREAD

**Issue by longddox** [vitabaks/postgresql_cluster#748]
As the title, i want to remove a node from my cluster, it uses pgbackrest, load balancing option, but not use pgBouncer. I have read the README.md, searching for the folders but i cannot find information about remove a node from a cluster. I appreciate for your help!

edit: My cluster have 3 nodes (1 master, 2 workers). Each of the node has it own etcd server installed.

**Comment by vitabaks** [comment]
Hello.

To remove the node from the database cluster, simply stop and disable the Patroni service on that node. 

To remove the node from the etcd cluster, you need to use the command `etcdctl member remove`, but first, make sure to add another etcd node using `etcdctl member add`. See details in documentation.
