### ISSUE TITLE
Any way to specify custom WAL location?

### ISSUE THREAD

**Issue by mol-lux** [vitabaks/postgresql_cluster#75]
Hello!

First, thank you for this playbook! It is really nice!

While deploying this, we ran into the issue that we would like to put the Write-Ahead-Log onto a separate drive for permormance reasons. This is also recommended in the [PostgreSQL Wiki](http://wiki.postgresql.org/wiki/Installation_and_Administration_Best_practices#WAL_Directory).

As far as I can tell, there isn't really a configuration option for this.

Thanks!

**Comment by vitabaks** [comment]
Hi @mol-lux 

I have not yet automated the placement of the WAL directory in another path/disk.

We need to work on this.

**Comment by mol-lux** [comment]
OK, thanks!

As a workaround, I currently mount the WAL drive on `{{ postgres_data_dir}}/pg_wal` - I haven't had any issues with this yet. Will report if thes arise.

**Comment by servergeeks** [comment]
Hi @mol-lux 

Can you please share how you did this ?
I would like to store all postgres related data to a dedicated fs called /appl/postgres

Thanks!

**Comment by vitabaks** [comment]
@servergeeks 
> I would like to store all postgres related data to a dedicated fs called /appl/postgres

You can specify any other path for PGDATA in the postgresql_data_dir variable (in vars/Debian.yml or vars/RedHat.yml)
example:
```
postgresql_data_dir: "/appl/postgres" 
```
The specified directory will be automatically created if it does not already exist.

**Comment by servergeeks** [comment]
@vitabaks 

Thank you!

**Comment by vitabaks** [comment]
Hi @mol-lux 
> Any way to specify custom WAL location?

I am currently working on it. See my PR https://github.com/vitabaks/postgresql_cluster/pull/80

`postgresql_wal_dir` variable (in vars/Debian.yml or RedHat.yml)

To test for these changes, please clone the 'dev' branch:
```
git clone https://github.com/vitabaks/postgresql_cluster.git --branch dev
```

**Comment by vitabaks** [comment]
merged

**Comment by mol-lux** [comment]
Awesome, thank you!
