### ISSUE TITLE
ENV Vars like PG_CONSOLE_API_URL and PG_CONSOLE_AUTHORIZATION_TOKEN used in docker run dont work

### ISSUE THREAD

**Issue by HiggsTeilchen** [vitabaks/postgresql_cluster#764]
Hi,

i started my postgres_console with customized values:

```
docker run -d --name pg-console \
  --publish 80:80 \
  --publish 8080:8080 \
  --env PG_CONSOLE_API_URL=http://own-server.corporate.com:8080/api/v1 \
  --env PG_CONSOLE_AUTHORIZATION_TOKEN=very_secret_token \
  --volume console_postgres:/var/lib/postgresql \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/ansible:/tmp/ansible \
  --restart=unless-stopped \
  vitabaks/postgresql_cluster_console:2.0.0
```

If i want to login in my browser on http://own-server.corporate.com i cant login with my customized Token. i can just login with the default "secret_token".
After login and "Create Cluster", i can see, that my webbrowser still tries do resolve http://localhost:8080

Somehow my customized variables arent working for the image?

**Comment by vitabaks** [comment]
Hi @HiggsTeilchen,

I couldn't reproduce your issue, as both variables are overridden in my case.
![image](https://github.com/user-attachments/assets/df3decce-729b-4279-9d30-0976b16b5379)

Could it be that you first tested the console locally and only later installed it on the corporate server? If so, it might simply be a browser cache issue. Have you tried clearing the browser cache or logging in using private/incognito mode?

**Comment by HiggsTeilchen** [comment]
Oh damn, your right.
It was the browser cache. My Bad.

Never thought that the needed password would be cached too.
