### ISSUE TITLE
Unable to build WAL-G if it was built once

### ISSUE THREAD

**Issue by realkarmakun** [vitabaks/postgresql_cluster#767]
When attempting to run config_pgcluster.yml after initial installation I get the following:

```
TASK [wal-g : Download WAL-G v3.0.2 source code] **************************************************************************************************************************************************************************************************************************
fatal: [10.0.1.53]: FAILED! => {"before": "124e8e714b2fe573bd35be870b7e21d8f1976bd6", "changed": false, "msg": "Local modifications exist in the destination: /tmp/wal-g (force=no)."}
fatal: [10.0.1.52]: FAILED! => {"before": "124e8e714b2fe573bd35be870b7e21d8f1976bd6", "changed": false, "msg": "Local modifications exist in the destination: /tmp/wal-g (force=no)."}
fatal: [10.0.1.51]: FAILED! => {"before": "124e8e714b2fe573bd35be870b7e21d8f1976bd6", "changed": false, "msg": "Local modifications exist in the destination: /tmp/wal-g (force=no)."}
```

It seems WAL-G is being downloaded to the same directory it's built in (which is fine) but It does not work for some reason.

Running AlmaLinux 9 without any security profiles, under root user.

**Comment by vitabaks** [comment]
@realkarmakun Thanks, I'll take a look at it.

When running `config_cluster.yml`, there should not be a second attempt to build WAL-G. \
Or did you change the version in the `wal_g_version` variable to update?

**Comment by realkarmakun** [comment]
> Or did you change the version in the wal_g_version variable to update?

I didn't commit changes so I can't tell for sure. I think I only changed postgresql_listen_addr and pgbouncer_listen_addr. 

I also ran into the same problem when tried to run deploy_pgcluster.yml twice (without delete). It resulted in the same issue, but I brushed it off as it's expected to delete cluster before deploying again.

I also run 3.0.2 but changed the version before deployment. 

Pretty sure if I attempt to run config_pgcluster.yml I'll get the same error message. I can try it.

**Comment by vitabaks** [comment]
@realkarmakun Add the `force` option for the `git` module

```
    - name: "Download WAL-G v{{ wal_g_version }} source code"
      ansible.builtin.git:
        repo: https://github.com/wal-g/wal-g.git
        version: v{{ wal_g_version }}
        dest: /tmp/wal-g
        force: true
```

And also see this PR https://github.com/vitabaks/postgresql_cluster/pull/768
