### ISSUE TITLE
pgBackRest не стартует.

### ISSUE THREAD

**Issue by Dzirt2** [vitabaks/postgresql_cluster#778]
С парольной аутентификацией сервис pgbackrest не стартует. Опции в yml такой tls-server-auth нету.

```
$ systemctl status pgbackrest
● pgbackrest.service - pgBackRest Server
     Loaded: loaded (/usr/lib/systemd/system/pgbackrest.service; disabled; preset: enabled)
     Active: activating (start-post) (Result: exit-code) since Thu 2024-10-03 15:53:26 MSK; 2s ago
    Process: 14999 ExecStart=/usr/bin/pgbackrest server (code=exited, status=37)
   Main PID: 14999 (code=exited, status=37); Control PID: 15000 (sleep)
      Tasks: 1 (limit: 4575)
     Memory: 196.0K (peak: 3.1M)
        CPU: 28ms
     CGroup: /system.slice/pgbackrest.service
             └─15000 /bin/sleep 3

Oct 03 15:53:27 clonme24 systemd[1]: pgbackrest.service: Scheduled restart job, restart counter is at 217.
Oct 03 15:53:27 clonme24 systemd[1]: Starting pgbackrest.service - pgBackRest Server...
Oct 03 15:53:27 clonme24 pgbackrest[14999]: P00   WARN: configuration file contains invalid option 'include-path'
Oct 03 15:53:27 clonme24 pgbackrest[14999]: P00  ERROR: [037]: server command requires option: tls-server-auth
```

**Comment by vitabaks** [comment]
Смотрите примеры конфигураций в [документации](https://postgresql-cluster.org/docs/management/backup#command-line)

**Comment by Dzirt2** [comment]
# pgBackRest
pgbackrest_install: true  # or 'true' to install and configure backups using pgBackRest
pgbackrest_install_from_pgdg_repo: true  # or 'false'
pgbackrest_stanza: "{{ patroni_cluster_name }}"  # specify your --stanza
pgbackrest_repo_type: "posix"  # or "s3", "gcs", "azure"
pgbackrest_repo_host: "172.29.1.27"  # dedicated repository host (optional)
pgbackrest_repo_user: "postgres"  # if "repo_host" is set (optional)
pgbackrest_conf_file: "/etc/pgbackrest/pgbackrest.conf"
# config https://pgbackrest.org/configuration.html
pgbackrest_conf:
  global:  # [global] section
    - { option: "log-level-file", value: "detail" }
    - { option: "log-path", value: "/var/log/pgbackrest" }
    - { option: "repo1-type", value: "{{ pgbackrest_repo_type | lower }}" }
    - { option: "repo1-host", value: "{{ pgbackrest_repo_host }}" }
    - { option: "repo1-host-user", value: "{{ pgbackrest_repo_user }}" }
    - { option: "repo1-path", value: "/var/lib/pgbackrest" }
    - { option: "repo1-retention-full", value: "4" }
    - { option: "repo1-retention-archive", value: "4" }
    - { option: "repo1-bundle", value: "y" }
    - { option: "repo1-block", value: "y" }
    - { option: "start-fast", value: "y" }
    - { option: "stop-auto", value: "y" }
    - { option: "link-all", value: "y" }
    - { option: "resume", value: "n" }
    - { option: "spool-path", value: "/var/spool/pgbackrest" }
    - { option: "archive-async", value: "y" } # Enables asynchronous WAL archiving (details: https://pgbackrest.org/user-guide.html#async-archiving)
    - { option: "archive-get-queue-max", value: "1GiB" }
#    - { option: "archive-push-queue-max", value: "100GiB" }
#    - { option: "backup-standby", value: "y" } # When set to 'y', standby servers will be automatically added to the stanza section.
#    - { option: "", value: "" }
  stanza:  # [stanza_name] section
    - { option: "process-max", value: "4" }
    - { option: "log-level-console", value: "info" }
    - { option: "recovery-option", value: "recovery_target_action=promote" }
    - { option: "pg1-socket-path", value: "{{ postgresql_unix_socket_dir }}" }
    - { option: "pg1-path", value: "{{ postgresql_data_dir }}" }
#    - { option: "", value: "" }
# (optional) dedicated backup server config (if "repo_host" is set)
# (optional) dedicated backup server config (if "repo_host" is set)
pgbackrest_server_conf:
  global:
    - { option: "log-level-file", value: "detail" }
    - { option: "log-level-console", value: "info" }
    - { option: "log-path", value: "/var/log/pgbackrest" }
    - { option: "repo1-type", value: "{{ pgbackrest_repo_type | lower }}" }
    - { option: "repo1-path", value: "/var/lib/pgbackrest" }
    - { option: "repo1-retention-full", value: "4" }
    - { option: "repo1-retention-archive", value: "4" }
    - { option: "repo1-bundle", value: "y" }
    - { option: "repo1-block", value: "y" }
    - { option: "archive-check", value: "y" }
    - { option: "archive-copy", value: "n" }
    - { option: "backup-standby", value: "y" }
    - { option: "start-fast", value: "y" }
    - { option: "stop-auto", value: "y" }
    - { option: "link-all", value: "y" }
    - { option: "resume", value: "n" }
#    - { option: "", value: "" }
# the stanza section will be generated automatically

pgbackrest_archive_command: "pgbackrest --stanza={{ pgbackrest_stanza }} archive-push %p"
pgbackrest_patroni_cluster_restore_command:
  '/usr/bin/pgbackrest --stanza={{ pgbackrest_stanza }} --delta restore'  # restore from latest backup
#  '/usr/bin/pgbackrest --stanza={{ pgbackrest_stanza }} --type=time "--target=2020-06-01 11:00:00+03" --delta restore'  # Point-in-Time Recovery (example)

# By default, the cron jobs is created on the database server.
# If 'repo_host' is defined, the cron jobs will be created on the pgbackrest server.
pgbackrest_cron_jobs:
  - name: "pgBackRest: Full Backup"
    file: "/etc/cron.d/pgbackrest-{{ patroni_cluster_name }}"
    user: "postgres"
    minute: "00"
    hour: "{{ PGBACKREST_BACKUP_HOUR | default('3') }}"
    day: "*"
    month: "*"
    weekday: "0"
    job: "pgbackrest --stanza={{ pgbackrest_stanza }} --type=full backup"
    # job: "if [ $(psql -tAXc 'select pg_is_in_recovery()') = 'f' ]; then pgbackrest --stanza={{ pgbackrest_stanza }} --type=full backup; fi"
  - name: "pgBackRest: Diff Backup"
    file: "/etc/cron.d/pgbackrest-{{ patroni_cluster_name }}"
    user: "postgres"
    minute: "00"
    hour: "3"
    day: "*"
    month: "*"
    weekday: "1-6"
    job: "pgbackrest --stanza={{ pgbackrest_stanza }} --type=diff backup"
    # job: "if [ $(psql -tAXc 'select pg_is_in_recovery()') = 'f' ]; then pgbackrest --stanza={{ pgbackrest_stanza }} --type=diff backup; fi"


Вот с таким конфигом не стартует.

**Comment by vitabaks** [comment]
> systemctl status pgbackrest

обратите внимание что мы не используем `pgbackrest.service`, достаточно бинарного файла и задания cron расположенного по пути `/etc/cron.d/pgbackrest-{{ patroni_cluster_name }}`

**Comment by Dzirt2** [comment]
тогда крон создался, но не выполнился потому что:
1) pgbackrest info
P00   WARN: configuration file contains invalid option 'include-path'
No stanzas exist in the repository.

2)pgbackrest --stanza=pgbackrest-postgres16-cluster-rims stanza-create
P00   WARN: configuration file contains invalid option 'include-path'
P00  ERROR: [037]: stanza-create command requires option: pg1-path
            HINT: does this stanza exist?

**Comment by vitabaks** [comment]
Приложите файл конфигурации pgbackrest

**Comment by vitabaks** [comment]
>  Permission denied (publickey,password)

между серверами должен быть выполнен обмен SSH ключами. Это должно было выполниться автоматически, приложите лог Ansible для анализа пожалуйста.
Вы можете выполнить плейбук повторно на уже развернутом кластере с добавлением переменной `postgresql_exists`

```
ansible-playbook deploy_pgcluster.yml -t pgbackrest -e "postgresql_exists=true"
```

**Comment by Pavel-postgresql-cluster** [comment]
Hello!

Thank you for choosing postgresql_cluster for your database management. We hope our solution is helping you manage PostgreSQL more efficiently and cost-effectively.

We’d like to ensure that postgresql_cluster fully meets your needs. Could you let us know:

• Are you using postgresql_cluster in your daily operations?
• Have you encountered any challenges or questions regarding setup and usage?
• Would you be interested in additional assistance from our team? We offer customized support packages tailored to your specific needs.

We’re always here to help and provide any recommendations to optimize your experience. Just reply to this email, and we’d be happy to discuss how we can be of assistance.

Best regards,
The postgresql-cluster.org Team
