### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by SrinivasMajeti** [vitabaks/postgresql_cluster#79]
Hello

We are testing this in Ubuntu 16.04 and and Python 3.5 and running into issues where in the patroni is starting. Are there any minimum requirements for this to work. From what my team mentioned this is working fine in Ubuntu 18.04 in which we get python 3.6. Any help is appreciated (other than upgrading the Ubuntu :) )

tail -30 /var/log/syslog
Dec 23 14:19:49 pgnode01 ansible-command: Invoked with creates=None executable=None _uses_shell=False strip_empty_ends=True _raw_params=/usr/lib/postgresql/11/bin/pg_ctl status -D /var/lib/postgresql/11/main removes=None argv=None warn=True chdir=None stdin_add_newline=True stdin=None
Dec 23 14:19:55 pgnode01 ansible-systemd: Invoked with no_block=False force=None name=patroni daemon_reexec=False enabled=True daemon_reload=True state=restarted user=None scope=None masked=None
Dec 23 14:19:55 pgnode01 systemd[1]: Reloading.
Dec 23 14:19:55 pgnode01 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL - patroni.
Dec 23 14:19:55 pgnode01 ansible-wait_for: Invoked with active_connection_states=['ESTABLISHED', 'FIN_WAIT1', 'FIN_WAIT2', 'SYN_RECV', 'SYN_SENT', 'TIME_WAIT'] state=started connect_timeout=5 delay=10 search_regex=None host=172.29.149.223 sleep=1 timeout=120 exclude_hosts=None msg=None path=None port=8008
Dec 23 14:19:55 pgnode01 patroni[1725]: 2020-12-23 14:19:55,835 INFO: Failed to import patroni.dcs.consul
Dec 23 14:19:55 pgnode01 patroni[1725]: 2020-12-23 14:19:55,837 INFO: Failed to import patroni.dcs.etcd
Dec 23 14:19:55 pgnode01 patroni[1725]: 2020-12-23 14:19:55,838 INFO: Failed to import patroni.dcs.etcd3
Dec 23 14:19:55 pgnode01 patroni[1725]: 2020-12-23 14:19:55,889 INFO: Failed to import patroni.dcs.raft
Dec 23 14:19:55 pgnode01 patroni[1725]: Traceback (most recent call last):
Dec 23 14:19:55 pgnode01 patroni[1725]:   File "/usr/bin/patroni", line 11, in <module>
Dec 23 14:19:55 pgnode01 patroni[1725]:     load_entry_point('patroni==2.0.1', 'console_scripts', 'patroni')()
Dec 23 14:19:55 pgnode01 patroni[1725]:   File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 170, in main
Dec 23 14:19:55 pgnode01 patroni[1725]:     return patroni_main()
Dec 23 14:19:55 pgnode01 patroni[1725]:   File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 138, in patroni_main
Dec 23 14:19:55 pgnode01 patroni[1725]:     abstract_main(Patroni, schema)
Dec 23 14:19:55 pgnode01 patroni[1725]:   File "/usr/lib/python3/dist-packages/patroni/daemon.py", line 98, in abstract_main
Dec 23 14:19:55 pgnode01 patroni[1725]:     controller = cls(config)
Dec 23 14:19:55 pgnode01 patroni[1725]:   File "/usr/lib/python3/dist-packages/patroni/__init__.py", line 29, in __init__
Dec 23 14:19:55 pgnode01 patroni[1725]:     self.dcs = get_dcs(self.config)
Dec 23 14:19:55 pgnode01 patroni[1725]:   File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 106, in get_dcs
Dec 23 14:19:55 pgnode01 patroni[1725]:     Available implementations: """ + ', '.join(sorted(set(available_implementations))))
Dec 23 14:19:55 pgnode01 patroni[1725]: patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: exhibitor, kubernetes, zookeeper'
Dec 23 14:19:55 pgnode01 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Dec 23 14:19:55 pgnode01 systemd[1]: patroni.service: Unit entered failed state.
Dec 23 14:19:55 pgnode01 systemd[1]: patroni.service: Failed with result 'exit-code'.
Dec 23 14:22:22 pgnode01 cf-agent[1797]: CFEngine(agent)  No suitable server found
Dec 23 14:22:22 pgnode01 cf-agent[1797]: message repeated 2 times: [ CFEngine(agent)  No suitable server found]
Dec 23 14:22:22 pgnode01 cf-agent[1797]: CFEngine(agent)  Method 'cfe_internal_update_policy_cpv' failed in some repairs
Dec 23 14:22:23 pgnode01 cf-agent[1807]: CFEngine(agent)  R: ERROR: No Policy Hub defined for this server.  Environment: UNKNOWN.  Stage: 0.  Role: INFRASTRUCTURE.

**Comment by vitabaks** [comment]
Hi @SrinivasMajeti 

> ... other than upgrading the Ubuntu :)

I was just planning to remove 16.04 from the list of supported :)
I've even stopped testing the code on this version of the distribution.

Ubuntu 16.04 - End of Life in April 2021
Python 3.5 - End of Life in September 2020

> INFO: Failed to import patroni.dcs.etcd
> patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distributed configuration store

I'll check it out and try to help you.

**Comment by SrinivasMajeti** [comment]
Thank you. I also have another issue. My setup has 3 servers - a master, a replica and a dedicated pgbackrest (this does have not have postgres in it).

The inventory file has

[etcd_cluster]  # recommendation: 3 or 5-7 nodes
172.17.0.2
172.17.0.3
172.17.0.4


#if with_haproxy_load_balancing: true (in vars/main.yml)
[balancers]
172.17.0.2
172.17.0.3
172.17.0.4

#PostgreSQL nodes
[master]
172.17.0.4 hostname=u3 postgresql_exists='false'

[replica]
172.17.0.3 hostname=u2

[postgres_cluster:children]
master
replica

#In this example, all components will be installed on PostgreSQL nodes
#You can deploy the etcd cluster and the haproxy balancers on other dedicated servers.

 #if pgbackrest_install: true and "repo_host" is set (in vars/main.yml)
[pgbackrest]  # optional (Dedicated Repository Host)
172.17.0.2 hostname=u4


#Connection settings
[all:vars]
ansible_connection='ssh'
ansible_ssh_port='22'
ansible_user='root'
ansible_ssh_pass='z1X@c3v4'  # "sshpass" package is required for use "ansible_ssh_pass"
#ansible_ssh_private_key_file=
ansible_python_interpreter='/usr/bin/python3.5'  # is required for use python3

[pgbackrest:vars]
ansible_user='postgres'
ansible_ssh_pass='postgres'

*************

When I deploy getting the error

TASK [Build a firewall_ports_dynamic_var] ****************************************************************************************************************************************************************************************************
ok: [172.17.0.2] => (item=balancers) => {"ansible_facts": {"firewall_ports_dynamic_var": ["22", "5000", "5001", "5002", "5003", "7000"]}, "ansible_loop_var": "item", "changed": false, "item": "balancers"}
ok: [172.17.0.2] => (item=etcd_cluster) => {"ansible_facts": {"firewall_ports_dynamic_var": ["22", "5000", "5001", "5002", "5003", "7000", "22", "2379", "2380"]}, "ansible_loop_var": "item", "changed": false, "item": "etcd_cluster"}
ok: [172.17.0.3] => (item=balancers) => {"ansible_facts": {"firewall_ports_dynamic_var": ["22", "5000", "5001", "5002", "5003", "7000"]}, "ansible_loop_var": "item", "changed": false, "item": "balancers"}
# _fatal: [172.17.0.2]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'pgbackrest'\n\nThe error appears to be in '/postgres/postgres_cluster/etcd_cluster.yml': line 31, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Build a firewall_ports_dynamic_var\n      ^ here\n"}_**
ok: [172.17.0.3] => (item=etcd_cluster) => {"ansible_facts": {"firewall_ports_dynamic_var": ["22", "5000", "5001", "5002", "5003", "7000", "22", "2379", "2380"]}, "ansible_loop_var": "item", "changed": false, "item": "etcd_cluster"}
ok: [172.17.0.4] => (item=balancers) => {"ansible_facts": {"firewall_ports_dynamic_var": ["22", "5000", "5001", "5002", "5003", "7000"]}, "ansible_loop_var": "item", "changed": false, "item": "balancers"}
ok: [172.17.0.3] => (item=postgres_cluster) => {"ansible_facts": {"firewall_ports_dynamic_var": ["22", "5000", "5001", "5002", "5003", "7000", "22", "2379", "2380", "22", "5432", 6432, "8008"]}, "ansible_loop_var": "item", "changed": false, "item": "postgres_cluster"}
ok: [172.17.0.4] => (item=etcd_cluster) => {"ansible_facts": {"firewall_ports_dynamic_var": ["22", "5000", "5001", "5002", "5003", "7000", "22", "2379", "2380"]}, "ansible_loop_var": "item", "changed": false, "item": "etcd_cluster"}
ok: [172.17.0.3] => (item=replica) => {"ansible_facts": {"firewall_ports_dynamic_var": ["22", "5000", "5001", "5002", "5003", "7000", "22", "2379", "2380", "22", "5432", 6432, "8008"]}, "ansible_loop_var": "item", "changed": false, "item": "replica"}
ok: [172.17.0.4] => (item=master) => {"ansible_facts": {"firewall_ports_dynamic_var": ["22", "5000", "5001", "5002", "5003", "7000", "22", "2379", "2380"]}, "ansible_loop_var": "item", "changed": false, "item": "master"}
ok: [172.17.0.4] => (item=postgres_cluster) => {"ansible_facts": {"firewall_ports_dynamic_var": ["22", "5000", "5001", "5002", "5003", "7000", "22", "2379", "2380", "22", "5432", 6432, "8008"]}, "ansible_loop_var": "item", "changed": false, "item": "postgres_cluster"}

**Comment by SrinivasMajeti** [comment]
This cluster is a 3 node cluster with 1 master 1 replica and 1 dedicated pgbackrest. The patroni yaml file is failing at restore from backup. If this is a new cluster which backup is it trying to restore from?

TASK [patroni : Run "/usr/bin/pgbackrest --stanza=test --delta restore" on Master] ***********************************************************************************************************************************************************
changed: [172.17.0.4] => {"ansible_job_id": "985085638936.21192", "changed": true, "finished": 0, "results_file": "/var/lib/postgresql/.ansible_async/985085638936.21192", "started": 1}

TASK [patroni : Run "/usr/bin/pgbackrest --stanza=test --delta restore" on Replica] **********************************************************************************************************************************************************
changed: [172.17.0.3] => {"ansible_job_id": "960424571700.7083", "changed": true, "finished": 0, "results_file": "/var/lib/postgresql/.ansible_async/960424571700.7083", "started": 1}

TASK [patroni : Waiting for restore from backup] *********************************************************************************************************************************************************************************************
failed: [172.17.0.3] (item=True) => {"ansible_job_id": "960424571700.7083", "ansible_loop_var": "item", "attempts": 1, "changed": true, "cmd": ["/usr/bin/pgbackrest", "--stanza=test", "--delta", "restore"], "delta": "0:00:00.253018", "end": "2020-12-25 05:28:57.292155", "finished": 1, "item": {"ansible_job_id": "960424571700.7083", "changed": true, "failed": false, "finished": 0, "results_file": "/var/lib/postgresql/.ansible_async/960424571700.7083", "started": 1}, "msg": "non-zero return code", "rc": 55, "start": "2020-12-25 05:28:57.039137", "stderr": "ERROR: [055]: unable to load info file '/var/lib/pgbackrest/backup/test/backup.info' or '/var/lib/pgbackrest/backup/test/backup.info.copy':\n       FileMissingError: raised from remote-0 protocol on '172.17.0.2': unable to open missing file '/var/lib/pgbackrest/backup/test/backup.info' for read\n       FileMissingError: raised from remote-0 protocol on '172.17.0.2': unable to open missing file '/var/lib/pgbackrest/backup/test/backup.info.copy' for read\n       HINT: backup.info cannot be opened and is required to perform a backup.\n       HINT: has a stanza-create been performed?", "stderr_lines": ["ERROR: [055]: unable to load info file '/var/lib/pgbackrest/backup/test/backup.info' or '/var/lib/pgbackrest/backup/test/backup.info.copy':", "       FileMissingError: raised from remote-0 protocol on '172.17.0.2': unable to open missing file '/var/lib/pgbackrest/backup/test/backup.info' for read", "       FileMissingError: raised from remote-0 protocol on '172.17.0.2': unable to open missing file '/var/lib/pgbackrest/backup/test/backup.info.copy' for read", "       HINT: backup.info cannot be opened and is required to perform a backup.", "       HINT: has a stanza-create been performed?"], "stdout": "", "stdout_lines": []}
failed: [172.17.0.4] (item=True) => {"ansible_job_id": "985085638936.21192", "ansible_loop_var": "item", "attempts": 1, "changed": true, "cmd": ["/usr/bin/pgbackrest", "--stanza=test", "--delta", "restore"], "delta": "0:00:00.295693", "end": "2020-12-25 05:28:56.930831", "finished": 1, "item": {"ansible_job_id": "985085638936.21192", "changed": true, "failed": false, "finished": 0, "results_file": "/var/lib/postgresql/.ansible_async/985085638936.21192", "started": 1}, "msg": "non-zero return code", "rc": 55, "start": "2020-12-25 05:28:56.635138", "stderr": "ERROR: [055]: unable to load info file '/var/lib/pgbackrest/backup/test/backup.info' or '/var/lib/pgbackrest/backup/test/backup.info.copy':\n       FileMissingError: raised from remote-0 protocol on '172.17.0.2': unable to open missing file '/var/lib/pgbackrest/backup/test/backup.info' for read\n       FileMissingError: raised from remote-0 protocol on '172.17.0.2': unable to open missing file '/var/lib/pgbackrest/backup/test/backup.info.copy' for read\n       HINT: backup.info cannot be opened and is required to perform a backup.\n       HINT: has a stanza-create been performed?", "stderr_lines": ["ERROR: [055]: unable to load info file '/var/lib/pgbackrest/backup/test/backup.info' or '/var/lib/pgbackrest/backup/test/backup.info.copy':", "       FileMissingError: raised from remote-0 protocol on '172.17.0.2': unable to open missing file '/var/lib/pgbackrest/backup/test/backup.info' for read", "       FileMissingError: raised from remote-0 protocol on '172.17.0.2': unable to open missing file '/var/lib/pgbackrest/backup/test/backup.info.copy' for read", "       HINT: backup.info cannot be opened and is required to perform a backup.", "       HINT: has a stanza-create been performed?"], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT ***************************************************************************************************************************************************************************************************************************

**Comment by vitabaks** [comment]
@SrinivasMajeti 
Why are you trying to restore from a backup if you don't have a backup?

The playbook does not currently configure a backup (although it can prepare the configuration), the task of this playbook is to deploy a сluster, including deploying from a **(pre-existing)** backup.

See https://github.com/vitabaks/postgresql_cluster/issues/67

P.S.
This task is not related to compatibility with Ubuntu 16.04, please feel free to create new issues.

**Comment by vitabaks** [comment]
> We are testing this in Ubuntu 16.04 and and Python 3.5 and running into issues where in the patroni is starting

Until I could reproduce the problem, the patroni service is running.

pip3 list
```
