### ISSUE TITLE
Question - Consul multi datacenter deployment

### ISSUE THREAD

**Issue by guillaumeldc** [vitabaks/postgresql_cluster#798]
Thanks for the library, this has been very helpful so far. 
I'm trying different failure scenarios and there are a few things I have trouble understanding.

I'm using Consul with nodes deployed in 2 datacenter.
DC1: 3 servers, 1 client
DC2: 3 servers, 1 client

My understanding is that the raft protocol and  Consul should work with 2 wan federated cluster in these two datacenter. 

The setup with patroni however seems to require the use of only one cluster across 2 different datacenter.
My questions are as follows:
- I would need to remove or add one node to bring the total of nodes to either 5 or 7 (DC1: 2 or 3, DC2: 3 or 4) and adjust to quorum to either 3 or 4. Correct?
- I understand, the fault tolerance would either be 3 or 2 nodes but what if I lose DC2 (the one with most nodes) completely?

thank you in advance for your help.

**Comment by vitabaks** [comment]
Hi @guillaumeldc,

To ensure quorum, (N/2) + 1 nodes are required. You can find more details about how Raft works [here](http://thesecretlivesofdata.com/raft/). When distributing the DCS across multiple data centers, a third data center is necessary. More information on this can be found [here](https://www.cybertec-postgresql.com/en/introduction-and-how-to-etcd-clusters-for-patroni/).

If the second data center is only intended for Disaster Recovery (DR), you can set up two independent DCS clusters: one for the main Patroni cluster and another for the [Standby Cluster](https://patroni.readthedocs.io/en/latest/standby_cluster.html) (variable [patroni_standby_cluster](https://github.com/vitabaks/postgresql_cluster/blob/2.0.0/automation/vars/main.yml#L393C1-L393C24)).

**Comment by guillaumeldc** [comment]
Thanks a lot for pointing me to some good documentation. I was looking for something like that. 
I understand better the setup now.

**Comment by Pavel-postgresql-cluster** [comment]
Hello!

Thank you for choosing postgresql_cluster for your database management. We hope our solution is helping you manage PostgreSQL more efficiently and cost-effectively.

We’d like to ensure that postgresql_cluster fully meets your needs. Could you let us know:

• Are you using postgresql_cluster in your daily operations?
• Have you encountered any challenges or questions regarding setup and usage?
• Would you be interested in additional assistance from our team? We offer customized support packages tailored to your specific needs.

We’re always here to help and provide any recommendations to optimize your experience. Just reply to this email, and we’d be happy to discuss how we can be of assistance.

Best regards,
The postgresql-cluster.org Team
