### ISSUE TITLE
Error when not running HAProxy and Keepalived on the same VM

### ISSUE THREAD

**Issue by NormanTrinh** [vitabaks/postgresql_cluster#799]
Here is my setup for HAProxy and Keepalived.
```
VM 1: HAProxy, Keepalived
VM 2: HAProxy, Keepalived
VM 3: HAProxy, Keepalived
```

When only VM 1 (or only 2 or only 3) enables HAProxy and Keepalived (the other VM is disabled), my client call to services works ok. When only VM 1 enabled HAProxy and only VM 2 enabled Keepalived (not run HAProxy and Keepalived as a pair on the same VM), I couldn't call my services. What happened? Is there any way to fix this?

**Comment by vitabaks** [comment]
@NormanTrinh It is not entirely clear from the description what is happening with you, could you attach configurations and logs for analysis?

**Comment by NormanTrinh** [comment]
@vitabaks I just ask because I just tested the Keepalived and HAProxy features, and the Patroni cluster still works fine. Actually, we will need to enable Keepalive in all 3 VMs for it to work properly, and HAProxy will need at least 1 alive to run.

Anyway, thank you for your great project.
