### ISSUE TITLE
your own machine hetzner

### ISSUE THREAD

**Issue by TrinityGale** [vitabaks/postgresql_cluster#801]
Hi
I give 10.0.0.0.3 10.0.0.0.4 10.0.0.0.5 to the private ip addresses in your own server section to the server I opened before with vds in hetzner and 10.0.0.3 in Cluster VIP address section but it gives failed

**Comment by vitabaks** [comment]
Hi @TrinityGale  try without a VIP address

<img width="1001" alt="Screenshot 2024-11-08 at 11 22 57 PM" src="https://github.com/user-attachments/assets/0abe0bba-d6d2-45c1-9bba-7689b8b73610">


Doc: https://postgresql-cluster.org/docs/deployment/your-own-machines

**Comment by TrinityGale** [comment]
thank you but now I get this error
fatal: [10.0.0.5]: FAILED! => {"changed": false, "msg": "Unable to start service etcd: Job for etcd.service failed because the control process exited with error code.\nSee \"systemctl status etcd.service\" and \"journalctl -xeu etcd.service\" for details.\n"}

**Comment by TrinityGale** [comment]
I solved it, the hostnames must be different, how do I clean the operations logs?

**Comment by vitabaks** [comment]
You can delete entries in the operations table in the console database, but why would you want to? The operations table is intended to serve as an audit log, recording all actions performed on the cluster.

**Comment by vitabaks** [comment]
> are the read and write ports different or does the haproxy redirect itself?

Yes, different.

Your application must have support sending read requests to a custom address/port.

Doc: https://postgresql-cluster.org/docs/overview/architecture

**Comment by TrinityGale** [comment]
Do I have the chance to write read from a single port, can haproxy redirect according to the query, and can I rent 4-5 clusters on the same server separately? Sorry havre bad english and thank you

**Comment by vitabaks** [comment]
> Do I have the chance to write read from a single port, can haproxy redirect according to the query

To read and write from a single port when using HAProxy, use port 5000, in which case all traffic will be directed to the Primary server.

> and can I rent 4-5 clusters on the same server separately?
Only one cluster within a single server is supported. You can simply create more VMs to create multiple database clusters.

**Comment by TrinityGale** [comment]
Thank you
