### ISSUE TITLE
The page for creating a cluster spins endlessly

### ISSUE THREAD

**Issue by DevOps-Youtube-Channel** [vitabaks/postgresql_cluster#805]
Good afternoon. 
Deployed a virtual machine under ubuntu 22.04 server. Installed Docker. I picked up the container to install the cluster. Came in. But it freezes, that is, the page simply spins endlessly to create a cluster. What could be the problem?
<img width="853" alt="docker container" src="https://github.com/user-attachments/assets/6da77dad-ac6b-4602-b8b8-4aab5cb081f4">
<img width="1240" alt="page" src="https://github.com/user-attachments/assets/c949d3df-55c3-48ab-8745-21d10628b912">

**Comment by vitabaks** [comment]
Hi @DevOps-Youtube-Channel 

If you have set up the console on a different server, replace `localhost` with your server's IP address in the `PG_CONSOLE_API_URL` variable.

**Comment by DevOps-Youtube-Channel** [comment]
do you mean like that?

![image](https://github.com/user-attachments/assets/3cd165d8-e9b4-4f1f-bcd6-b62f38c7c522)

![image](https://github.com/user-attachments/assets/1a5a6994-5284-41aa-b2cb-0b2de7e31331)

**Comment by DevOps-Youtube-Channel** [comment]
![image](https://github.com/user-attachments/assets/ed9d0929-b655-48fb-8fe2-36b3e2653198)


it worked thank you
