### ISSUE TITLE
patroni jinja tepmlate issue for maximum_lag_on_failover parameter

### ISSUE THREAD

**Issue by garry-t** [vitabaks/postgresql_cluster#807]
In case you maximum_lag_on_failover: 0, will be applied default value, since 0 treats as False

**Comment by garry-t** [comment]
Fix https://github.com/vitabaks/postgresql_cluster/pull/808

**Comment by vitabaks** [comment]
Ok, thanks.

But I don't think anyone will set 0 as this will turn off autofailover at the slightest replication lag.
