### ISSUE TITLE
Failed to start Etcd Server

### ISSUE THREAD

**Issue by DevOps-Youtube-Channel** [vitabaks/postgresql_cluster#809]
Hello
During the installation of the etcd server I receive an error, I am attaching screenshots. Why does this happen?

VM-1-2-3 character:  16 GB RAM, 4 CPU, 20 GB SSD

![image](https://github.com/user-attachments/assets/013ae764-0c54-4650-ac09-f6f0daf0e835)

![image](https://github.com/user-attachments/assets/08582c15-01b6-43b1-8b32-b1c6fa05c5ce)

![image](https://github.com/user-attachments/assets/ad3b8caa-d496-417e-a8b4-6e092fdfbc80)

**Comment by vitabaks** [comment]
Hi @DevOps-Youtube-Channel 

Please attach etcd conf and log file

```
cat /etc/etcd/etcd.conf
```

```
sudo journalctl -u etcd | head -n 50
```


P.S. Do all VMs have unique names?

**Comment by DevOps-Youtube-Channel** [comment]
![image](https://github.com/user-attachments/assets/75725ca2-eb18-47e3-993b-2eea4f8951d5)


![image](https://github.com/user-attachments/assets/d445d8e6-792c-4185-a841-a0dc9cfd2351)


![image](https://github.com/user-attachments/assets/7ebde4a9-07d7-4f34-ae11-d79c0ac672d6)


yes you are right, all virtual machines have the same hostname: farrukh

**Comment by DevOps-Youtube-Channel** [comment]
![image](https://github.com/user-attachments/assets/fc7c5a53-19d0-4fed-bdbe-0e78c1d887dc)


One more question here: should I change the IP addresses and so on?  In general, in which files should I change the values ​​or something?

**Comment by vitabaks** [comment]
> yes you are right, all virtual machines have the same hostname: farrukh

This is not the first time. I will add a check so that the deployment does not start if the hostnames are the same.

**Comment by vitabaks** [comment]
> One more question here: should I change the IP addresses and so on? In general, in which files should I change the values ​​or something?

**Comment by vitabaks** [comment]
> One more question here: should I change the IP addresses and so on? In general, in which files should I change the values ​​or something?

Try use the UI console if command-line control seems difficult for you.

Doc: https://postgresql-cluster.org/docs/deployment/your-own-machines

**Comment by DevOps-Youtube-Channel** [comment]
![image](https://github.com/user-attachments/assets/64f2833c-91ca-4d38-9029-d46121175f61)


![image](https://github.com/user-attachments/assets/33df1577-9ab7-4c12-83b5-faa240c8aeb7)


for some reason the cluster is being created but there is nothing in operations, what is this connected with?

**Comment by DevOps-Youtube-Channel** [comment]
![image](https://github.com/user-attachments/assets/ea54b514-73e6-438f-9cd6-43f05994cb3a)


![image](https://github.com/user-attachments/assets/7b0e9838-7725-4fee-a79b-af0f87b86c95)

**Comment by vitabaks** [comment]
> for some reason the cluster is being created but there is nothing in operations, what is this connected with?

Could you check for an entry in the operations table?

```
docker exec pg-console psql -U postgres -c "select count (*) from operations"
```

**Comment by DevOps-Youtube-Channel** [comment]
![image](https://github.com/user-attachments/assets/214e21e1-aec3-472a-bedf-9dbe1fe779f9)

**Comment by vitabaks** [comment]
Please attach Console API log

```
docker exec pg-console cat /var/log/supervisor/pg-console-api-stdout.log | gzip > pg-console-api-stdout.log.gz
```

**Comment by DevOps-Youtube-Channel** [comment]
[pg-console-api-stdout.log.gz](https://github.com/user-attachments/files/17797145/pg-console-api-stdout.log.gz)

**Comment by vitabaks** [comment]
> {"level":"error","app":"pg_console","version":"2.0.0","module":"docker_manager","cid":"c67b129f-a894-4fd2-b114-3031782192d3","error":"Post \"http://%2Fvar%2Frun%2Fdocker.sock/v1.45/images/create?fromImage=vitabaks%2Fpostgresql_cluster&tag=latest\": context canceled","docker_image":"vitabaks/postgresql_cluster:latest","time":"2024-11-18T07:56:45Z","message":"failed to pull docker image"}
{"level":"error","app":"pg_console","version":"2.0.0","cid":"c67b129f-a894-4fd2-b114-3031782192d3","error":"context canceled","time":"2024-11-18T07:56:45Z","message":"failed to update cluster"}

`failed to pull docker image`

@DevOps-Youtube-Channel Perhaps there are problems with the Internet? The automation image did not load. Try to pull it manually:

```
docker pull vitabaks/postgresql_cluster:latest
```

**Comment by DevOps-Youtube-Channel** [comment]
![image](https://github.com/user-attachments/assets/5352a04e-5834-47fa-bd44-8838f52ddd37)

![image](https://github.com/user-attachments/assets/4aa1d05d-b443-4b8d-8228-54a193aafbb6)


yes it was a problem with the image since I deleted it then downloaded it back and everything worked

**Comment by DevOps-Youtube-Channel** [comment]
![image](https://github.com/user-attachments/assets/5407ff66-aff3-473f-9bf8-8e310155786a)


![image](https://github.com/user-attachments/assets/e084274c-44c9-4c75-bf9a-b1e1adf1a0bf)


I just got one failed from 3 hosts

**Comment by DevOps-Youtube-Channel** [comment]
I also can’t find the haproxy and patroni services installed on the hosts

![image](https://github.com/user-attachments/assets/1465945d-d6ae-44fb-a857-175648454660)

**Comment by vitabaks** [comment]
Judging by the log, the cluster deployment failed because the installation of packages was interrupted. Unfortunately, I don’t have the full log for a detailed error analysis, but I suspect there may be issues with repository access for downloading packages. Try to create the cluster again.

P.S. Please attach logs in text format in the future for easier analysis.

**Comment by DevOps-Youtube-Channel** [comment]
![image](https://github.com/user-attachments/assets/44170828-fc28-4b81-acfc-9fa504e31b52)


I did everything again from scratch, after line 444 I got this error: 192.168.217.135 this is my virtual machine that is running a docker container, most likely my computer simply does not have enough resources (I think RAM) they want for each VM I allocated 16 GB RAM, 4 CPU

**Comment by vitabaks** [comment]
There is an error at the time of creating a 4GB swap file. Do you have enough disk size on your VMs?

the log that you send as a screenshot does not allow us to see the entire text of the error. Just copy the text content of the log.

**Comment by DevOps-Youtube-Channel** [comment]
![image](https://github.com/user-attachments/assets/81ded5d8-21f2-4dcb-8965-d18f313dbb5d)


![image](https://github.com/user-attachments/assets/278ba0a5-1d2c-4fc0-be56-1f90c61f1975)


Everything was installed without failed, only one thing confuses me that I got it in one place, ignore is it critical?
I'm attaching the error:

fatal: [192.168.217.134]: FAILED! => {"msg": "Timeout (62s) waiting for privilege escalation prompt: "}
...ignoring

![image](https://github.com/user-attachments/assets/a7ff7c7a-9ef1-4ec8-be97-9ae581736ad0)

**Comment by vitabaks** [comment]
> Everything was installed without failed, only one thing confuses me that I got it in one place, ignore is it critical?

The error occurred because Ansible timed out while waiting for a privilege escalation prompt on the host 192.168.217.134. However, the playbook is configured to ignore non-critical errors like this one (...ignoring) and continued the deployment. 

The automation code is designed in such a way that any error critical to the functioning of the cluster will not be ignored. If the deployment completed successfully, then everything is fine.
