### ISSUE TITLE
QUESTION: How to recover from a pgbackrest server fail ?

### ISSUE THREAD

**Issue by BabaTataKaka** [vitabaks/postgresql_cluster#816]
Hi There,

How to recover from a pgbackrest server fail?  Should only have to redeploy the pgbackrest server and re create the stanza? Looks like the playbook does not support such scenario without redeploying the whole postgres cluster from scratch.

Thanks

**Comment by vitabaks** [comment]
Hello, have you tried to run the playbook with the pgbackrest tag?

**Comment by BabaTataKaka** [comment]
Yes , but my mistake was not to set postgres_exist to true.
