### ISSUE TITLE
Should huge pages be tuned explicitly?

### ISSUE THREAD

**Issue by algoritmsystems** [vitabaks/postgresql_cluster#817]
Hi @vitabaks !
What is the best way to specify huge pages explicitly or will it be set automatically?

> sysctl_set: true
>...
>#- { name: "vm.nr_hugepages", value: "9510" }  
>...
> ## Huge Pages
> ## this setting will automatically configure "vm.nr_hugepages" for shared_buffers of 8GB or more
> ##if 'sysctl_set' is 'true', "vm.nr_hugepages" is undefined or insufficient in sysctl_conf,
> ##and "huge_pages" is not 'off' in postgresql_parameters.
> huge_pages_auto_conf: true

If shared_buffers=12GB
And in postgrsql conf huge_pages mast be "on" or may be "try" to automatically configure hugepages?
Thanks!

**Comment by vitabaks** [comment]
Hello! Use "on" and "`huge_pages_auto_conf`", in order not to think about it on your own, it makes sense, for example, when increasing shared_buffers, in this case automation will set up huge pages.
