### ISSUE TITLE
 label:question adding some parametres to vars/system.yml file sysctl_conf:postgres_cluster:

### ISSUE THREAD

**Issue by algoritmsystems** [vitabaks/postgresql_cluster#818]
Hello! I added some parametres to sysctl_conf:postgres_cluster:
>  - { name: "vm.overcommit_memory", value: "2" }
>  - { name: "vm.overcommit_ratio", value: "90" }
>  - { name: "vm.dirty_background_ratio", value: "0" }          
>  - { name: "vm.dirty_ratio", value: "0" }
>  - { name: "vm.dirty_writeback_centisecs", value: "500" }
>  - { name: "net.ipv4.tcp_timestamps", value: "0" }
>  - { name: "kernel.sched_migration_cost_ns", value: "5000000" }   #uncommented

Is it reasonable to add these parameters?
Thanks!

**Comment by vitabaks** [comment]
Hello @algoritmsystems 

Assessing the suitability of these parameters requires a deeper understanding of your specific environment and workload.

We recommend exploring our [individual support packages](https://postgresql-cluster.org/docs/support#commercial-support) for tailored guidance and expertise to address such questions.
