### ISSUE TITLE
archive-push command end: aborted with exception [032]

### ISSUE THREAD

**Issue by servergeeks** [vitabaks/postgresql_cluster#83]
Hello guys,

Any idea why the archive push command fails ?

The directory seems to be configured correctly and should be the same in both locations.

```
vars/Debian.yml:postgresql_data_dir: "/appl/postgresql/{{ postgresql_version }}/{{ postgresql_cluster_name }}"
vars/main.yml:    - {option: "pg1-path", value: "{{ postgresql_data_dir }}"}
postgresql.base.conf:#data_directory = 'ConfigDir'              # use data in another directory
```
This is complete error message.
```
postgres@db2:~$ pgbackrest --stanza=s3_stanza archive-push pg_wal/000000060000000000000012.partial
2020-12-30 15:39:50.639 P00   INFO: archive-push command begin 2.31: [pg_wal/000000060000000000000012.partial] --exec-id=54416-06131fd5 --log-level-console=info --log-level-file=detail --log-path=/var/log/pgbackrest --pg1-path=/appl/postgresql/13/main --process-max=2 --repo1-path=/ --repo1-s3-bucket=postgres-backup --repo1-s3-endpoint=s3.nl-ams.scw.cloud --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=nl-ams --no-repo1-s3-verify-tls --repo1-type=s3 --stanza=s3_stanza
ERROR: [032]: PostgreSQL working directory '/var/lib/postgresql' is not the same as option pg1-path '/appl/postgresql/13/main'
       HINT: is the PostgreSQL data_directory configured the same as the pg1-path option?
2020-12-30 15:39:50.639 P00   INFO: archive-push command end: aborted with exception [032]
```

Thanks!

**Comment by vitabaks** [comment]
> ERROR: [032]: PostgreSQL working directory '/var/lib/postgresql' is not the same as option pg1-path '/appl/postgresql/13/main'

Check your pgbackrest.conf config file

pg1-path=?

**Comment by servergeeks** [comment]
```
postgres@db2:~$ psql
psql (13.1 (Ubuntu 13.1-1.pgdg20.04+1))
Type "help" for help.

postgres=# show data_directory;
      data_directory
--------------------------
 /appl/postgresql/13/main
(1 row)

postgres=#
```

And in /etc/pgbackrest/pgbackrest.conf...

```
[s3_stanza]
pg1-path=/appl/postgresql/13/main
process-max=2
recovery-option=recovery_target_action=promote
log-level-console=info
```

**Comment by servergeeks** [comment]
Hmmm... if I specify the whole path it works...

postgres@db2:~$ pgbackrest --stanza=s3_stanza archive-push /appl/postgresql/13/main/pg_wal/000000060000000000000012.partial

**Comment by vitabaks** [comment]
WAL file '000000060000000000000012.partial' already exists in the pgbackrest repo.

Decision:
Replace the archive_command parameter in the postgresql.conf configuration file with:
```
archive_command = 'cd .' 
```
Apply parameter changes
example: 
`select pg_reload_conf ();`

Next, switch (repeatedly) to the new WAL:
 `select pg_switch_wal();`

Optional. Reset counters in pg_stat_archiver view
`select pg_stat_reset_shared('archiver');`

Revert the old value of archive_command.

Check and run a full backup immediately:
```
pgbackrest --stanza=<my_stanza_name> check
pgbackrest --stanza=<my_stanza_name> --type=full backup
```

**Comment by vitabaks** [comment]
This error is not related to this playbook :)
please see the [pgbackrest](https://pgbackrest.org/) documentation.

**Comment by servergeeks** [comment]
Thank you @vitabaks.
I'll need to take a good look into the docs of pgbackrest and patroni + postgres in order to understand more about their inner workings.
