### ISSUE TITLE
Testing in virtualbox VM ubuntu/bionic64.

### ISSUE THREAD

**Issue by sajusat** [vitabaks/postgresql_cluster#84]
First of all, thank you for your great work.
I was trying to run the stack on a two node virtualbox machine with one master and standby (B type). 
For some reason it always fail on the task "etcd: Enable and start etcd service]" It is trying to restart the service with systemd.
After failure, I am completely shut out of the connection and cannot login with ssh anymore. It is someway corrupted. Restarting the machines does not help. I have to destroy the machines to run it again.

Here are the changes I made 
1. main.yml
`vip_interface: "eth1" #"{{ ansible_eth1.ipv4.interface }}"`

```
[etcd_cluster]  # recommendation: 3 or 5-7 nodes
dbnode1 ansible_ssh_host=localhost ansible_ssh_port=2222 ansible_ssh_private_key_file=/home/mark/Work/Infra/servers/.vagrant/machines/dbnode1/virtualbox/private_key
dbnode2 ansible_ssh_host=localhost ansible_ssh_port=2200 ansible_ssh_private_key_file=/home/mark/Work/Infra/servers/.vagrant/machines/dbnode2/virtualbox/private_key

[etcd_cluster:vars]
ansible_connection='ssh'
ansible_ssh_pass='vagrant'
ansible_user='vagrant'
```

```
TASK [etcd : Enable and start etcd service] ********************************************************************************************************************
fatal: [dbnode1]: FAILED! => {"changed": false, "msg": "Unable to start service etcd: Job for etcd.service failed because the control process exited with error code.\nSee \"systemctl status etcd.service\" and \"journalctl -xe\" for details.\n"}
fatal: [dbnode2]: FAILED! => {"changed": false, "msg": "Unable to start service etcd: Job for etcd.service failed because the control process exited with error code.\nSee \"systemctl status etcd.service\" and \"journalctl -xe\" for details.\n"}
```
is it something related to systemd issues ? how can I recover from the error ?
I tried with other ubuntu/debian images, it all stops at the this task.

**Comment by vitabaks** [comment]
Hi @sajusat 

In the inventory file, you must specify the ip address (for inventory_hostname variable). 
The specified ip addresses will be used to listen by the cluster components.

See example jinja2 template
https://github.com/vitabaks/postgresql_cluster/blob/master/roles/etcd/templates/etcd.conf.j2

**Comment by vitabaks** [comment]
> After failure, I am completely shut out of the connection and cannot login with ssh anymore. It is someway corrupted.

Disable the firewall role for your vagrant test:
`firewall_enabled_at_boot: false` (In vars/system.yml)

**Comment by sajusat** [comment]
@vitabaks 
I was thinking the `inventory_hostname` is inferred from the `ansible_facts`.
