### ISSUE TITLE
What do you think of the integrated pgpool-ii at the front end of this cluster, using it to proxy read and write separation

### ISSUE THREAD

**Issue by marsdonne** [vitabaks/postgresql_cluster#9]
i try it，it‘s work。

i deployed pgpool-ii， set one backend host with cluster-vip, port 5000 and 'ALWAYS_MASTER' ,  and another backend host with cluster-vip, port 5001 and to 'DISALLOW_TO_FAILOVER' ,  and 'load_balance_mode = on'. 

then，the application only need to connect pgpool-ii, just like a pgsql server.

**Comment by vitabaks** [comment]
Thank you @marsdonne  for your offer.

But 
I do not plan to use pgpool in a production environment.

My opinion: 
The application have  to know which requests to send read-only.
Mayby the pgpool can be used, but its use will at least lead to an additional overhead. And also, this will complicate the scheme a little in terms of deployment and further maintenance.

**Comment by marsdonne** [comment]
thank you for response
i am understand, your opinion is very valuable.
