### ISSUE TITLE
HAproxy configuration keeps changing 

### ISSUE THREAD

**Issue by asobeeh** [vitabaks/postgresql_cluster#94]
really I appreciate your kind support and availability to answer all our issues and inquiry, and for making efforts to provide such a great book,
I have something weird and want to make sure if it is on the full solution or someone is playing with me on the env 
I have deployed the solution in many environments, but one of them 
the HAproxy configuration of the backend "the destination of DB traffic" keeps automatically deleted from the HAproxy configuration. is there anything in patroni or consul "since I switched from ETCD to consul" that have the authority to change the HAproxy config

**Comment by vitabaks** [comment]
confd manage local application configuration files using templates and data from etcd. Used to automate HAProxy configuration file management.

```
/etc/confd/
├── conf.d
│   └── haproxy.toml
├── confd.toml
└── templates
    └── haproxy.tmpl
```
Did you edit the configuration file confd.toml?

**Comment by asobeeh** [comment]
even before I switching from ETCD to consul it kept changing. 

Do you mean that I have to edit this file with consul data? 

now I changed the mentioned file with the below 

haproxy.tom1
backend = "consul" 
interval = 10 
watch = true 
nodes = [
       "http://192.168.102.149:8500",
       "http://192.168.102.150:8500", 
       "http://192.168.102.90:8500", 
]


and for the ha.proxy.tmpl is it ok to change it manually to keep the current config as it is.

**Comment by vitabaks** [comment]
I have not tested Consul, I just have to do it soon.

P.S. If you want to manage the Haproxy configuration file manually, you can disable confd.service

**Comment by asobeeh** [comment]
Thanks for that and i will
