### ISSUE TITLE
Add meta/main.yml to fix the ansible-galaxy incorrect behavior

### ISSUE THREAD

**Issue by sncodeGit** [vitabaks/postgresql_cluster#95]
Please add the file meta/main.yml to this role.
Now if you download the role via ansible-galaxy, it will download incorrectly.
Try this command `ansible-galaxy install -p roles -r requirements.yml --force` with the following requirements.yml file
```
---
- src: https://github.com/vitabaks/postgresql_cluster.git
  scm: git
  version: master
  path: ./roles/
```
This download subrole [ansible-role-firewall](https://github.com/vitabaks/postgresql_cluster/tree/master/roles/ansible-role-firewall) as the main one because it is the only one that has meta/main.yml

**Comment by vitabaks** [comment]
Why? 

Why aren't you using git clone?

git clone https://github.com/vitabaks/postgresql_cluster.git

**Comment by sncodeGit** [comment]
Of course, this is possible, but if you have a lot of roles on the project and are rolling out infrastracture via CI/CD, it is convenient to use a centralized `ansible-galaxy -r` file :)

**Comment by vitabaks** [comment]
Done (c52b46c9320c4505a4514da5bfd626a8c86c76ac).

**Comment by sncodeGit** [comment]
Thanks
