### ISSUE TITLE
Basic help with backup

### ISSUE THREAD

**Issue by avosluck** [vitabaks/postgresql_cluster#96]
I'm just learning how to work with databases, sorry for the stupid questions

pgbackrest_install: true  # or 'true'
pgbackrest_install_from_pgdg_repo: true  # or 'false'
pgbackrest_stanza: "stanza_name"  # specify your --stanza
pgbackrest_repo_type: "posix"  # or "s3"
pgbackrest_repo_host: "172.16.0.1"  # dedicated repository host (if repo_type: "posix")
pgbackrest_repo_user: "postgres"  # if "repo_host" is set
pgbackrest_conf_file: "/etc/pgbackrest/pgbackrest.conf"

In the pgBackRest chapter, I applied these settings, but I do not know what action I should take next. I just need to make a backup, there is too much in the documentation and I cannot highlight the information that will help me.

**Comment by vitabaks** [comment]
This playbook is not currently intended for configuring backups.
Please refer to the documentation: https://pgbackrest.org/user-guide.html
