### ISSUE TITLE
Problems with pgbackrest

### ISSUE THREAD

**Issue by avosluck** [vitabaks/postgresql_cluster#97]
when I try to set up a backup on pgBackRest 2.32, I get this error

sudo -u pgbackrest pgbackrest --stanza=main check
ERROR: [082]: WAL segment 000000010000000000000007 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.

my config on repo :
[main]
pg1-host=172.16.0.11
pg1-path=/var/lib/postgresql/13/main

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y

config on postgres node:
[global]
log-level-file=detail
log-path=/var/log/pgbackrest
repo1-type=posix
repo1-host=172.16.0.1
repo1-host-user=postgres

[main]
pg1-path=/var/lib/postgresql/13/main
process-max=2
recovery-option=recovery_target_action=promote

archive_command = 'pgbackrest --stanza=main archive-push %p'
archive_mode = 'True'

**Comment by vitabaks** [comment]
This playbook is not currently intended for configuring backups.
Please refer to the documentation: https://pgbackrest.org/user-guide.html

check the PostgreSQL server log for errors.

I can suggest that you have not yet created a stanza
https://pgbackrest.org/user-guide.html#quickstart/create-stanza

**Comment by vitabaks** [comment]
This is not the first question related to setting up a backup.  Apparently it's worth adding this functionality.

**Comment by avosluck** [comment]
> This playbook is not currently intended for configuring backups.
> Please refer to the documentation: https://pgbackrest.org/user-guide.html
> 
> check the PostgreSQL server log for errors.
> 
> I can suggest that you have not yet created a stanza
> https://pgbackrest.org/user-guide.html#quickstart/create-stanza

I read the logs and there was a problem with file access, thanks for the answer!

**Comment by avosluck** [comment]
But the question arose, before restoring from a backup, do you need to turn off the entire patroni cluster or master node? how to properly recover from a backup if I have a patroni cluster

**Comment by vitabaks** [comment]
> But the question arose, before restoring from a backup, do you need to turn off the entire patroni cluster or master node?

Manually stop no needed, everything will be performed automatically.

> how to properly recover from a backup if I have a patroni cluster

You can run automatic restore of your existing patroni cluster
for PITR, specify the required parameters in the main.yml variable file and run the playbook with the tag:

`ansible-playbook deploy_pgcluster.yml --tags point_in_time_recovery`

See Recovery steps with pgBackRest
https://github.com/vitabaks/postgresql_cluster#restore-and-cloning

**Comment by avosluck** [comment]
> > But the question arose, before restoring from a backup, do you need to turn off the entire patroni cluster or master node?
> 
> Manually stop no needed, everything will be performed automatically.
> 
> > how to properly recover from a backup if I have a patroni cluster
> 
> You can run automatic restore of your existing patroni cluster
> for PITR, specify the required parameters in the main.yml variable file and run the playbook with the tag:
> 
> `ansible-playbook deploy_pgcluster.yml --tags point_in_time_recovery`
> 
> See Recovery steps with pgBackRest
> https://github.com/vitabaks/postgresql_cluster#restore-and-cloning

thanks a lot!
