### ISSUE TITLE
Ошибка при настройке sysctl: cannot stat /proc/sys/net/netfilter/nf_conntrack_max: No such file or directory

### ISSUE THREAD

**Issue by xinferum** [vitabaks/postgresql_cluster#98]
Добрый день.

При развертывании кластера столкнулся с ошибкой настройки sysctl.conf на чистых машинах CentOS 7.9.2009, не применяется параметр net.netfilter.nf_conntrack_max с ошибкой:
`failed: [hostname] (item={'name': 'net.netfilter.nf_conntrack_max', 'value': '1048576'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "net.netfilter.nf_conntrack_max", "value": "1048576"}, "msg": "Failed to reload sysctl: vm.swappiness = 1\nvm.min_free_kbytes = 102400\nvm.dirty_expire_centisecs = 1000\nvm.dirty_background_bytes = 16777216\nvm.dirty_bytes = 67108864\nvm.nr_hugepages = 2727\nvm.zone_reclaim_mode = 0\nkernel.numa_balancing = 0\nkernel.sched_migration_cost_ns = 5000000\nkernel.sched_autogroup_enabled = 0\nnet.ipv4.ip_nonlocal_bind = 1\nnet.ipv4.ip_forward = 1\nnet.ipv4.ip_local_port_range = 1024 65535\nnet.core.netdev_max_backlog = 250000\nnet.ipv4.tcp_max_syn_backlog = 8192\nnet.core.somaxconn = 65535\nfs.file-max = 1000000\nfs.inotify.max_user_watches = 100000\nvm.admin_reserve_kbytes = 100000\nnet.ipv4.tcp_timestamps = 1\nnet.ipv4.tcp_sack = 1\nsysctl: cannot stat /proc/sys/net/netfilter/nf_conntrack_max: No such file or directory\n"`

В качестве решения необходимо проверить включен ли модуль:
`lsmod | grep conntrack`
и включить его, если результат предыдущей команды пустой:
`modprobe ip_conntrack`

У себя реализовал это в виде дополнительной роли преконфигурации сервера в виде:

    ## Check and enable ip_conntrack module
    - name: PostgreSQL install | Check enabled module ip_conntrack
      shell: "lsmod | grep conntrack | wc -l"
      register: ip_conntrack_check_result
    
    - name: PostgreSQL install | Enable module ip_conntrack
      shell: modprobe ip_conntrack
      when: ip_conntrack_check_result.stdout|int == 0

Предлагаю добавить данные таски в начало роли sysctl.

**Comment by sgrinko** [comment]
Поддерживаю!

**Comment by vitabaks** [comment]
Вы выключали роль firewall?

**Comment by xinferum** [comment]
Добрый день.

Да, роль firewall не запускалась. Нашел в коде роли включение данного модуля.
Спасибо, вопросов больше нет.

**Comment by vitabaks** [comment]
Потому что если iptables не включаем то и параметр nf_conntrack задавать не нужно.
