### ISSUE TITLE
Предложение добавить в vars/main.yml параметры таймаутов клиента и сервера для шаблонов haproxy

### ISSUE THREAD

**Issue by xinferum** [vitabaks/postgresql_cluster#99]
Добрый день.

Предлагаю в vars/main.yml завести два новых параметра для таймаутов:
`timeout client
timeout server`
И прописать их в шаблонах roles/haproxy/templates/haproxy.cfg.j2 и roles/confd/templates/haproxy.tmpl.j2 полей haproxy и confd.

Сейчас эти параметры в обоих шаблонах имеют значение 60m, но для некоторых длительных операций администрирования (например, ребилд индекса) требуется большее время.
Хотелось бы на этапе установки иметь возможность задать оба этих параметра, т.к. столкнулся с ситуацией когда в шаблоне роли haproxy перед развертыванием кластера увеличили значение до 180m, а в шаблоне роли confd забыли, в итоге, после переключения ролей, значения перезаписались на те что были в confd.

**Comment by sgrinko** [comment]
Поддерживаю!

**Comment by vitabaks** [comment]
Добавил (1f0ac50874a8975d6ed5677a4171e2494498f80e).

Обновите код плейбука, и запустите с тегом, чтобы обновить конфигурацию:
```
ansible-playbook balancers.yml --tags haproxy_tmpl
```

**Comment by xinferum** [comment]
Спасибо!
